# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2230', '0006_auto_20190204_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s2230emitente',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230emitente',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230fimafastamento',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230fimafastamento',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230infoatestado',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230infoatestado',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230infocessao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230infocessao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230infomandsind',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230infomandsind',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230inforetif',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230inforetif',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230iniafastamento',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230iniafastamento',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='s2230emitente',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230emitente',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230fimafastamento',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230fimafastamento',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230infoatestado',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230infoatestado',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230infocessao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230infocessao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230infomandsind',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230infomandsind',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230inforetif',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230inforetif',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230iniafastamento',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230iniafastamento',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
