# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2230', '0017_auto_20190620_1408'),
        ('controle_de_acesso', '0026_auto_20190620_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s2230emitente',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s2230fimafastamento',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s2230infoatestado',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s2230infocessao',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s2230infomandsind',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s2230inforetif',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s2230iniafastamento',
            name='excluido',
        ),
    ]
