# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r2099', '0008_auto_20190204_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2099iderespinf',
            name='cpfresp',
            field=models.CharField(default=b'A', max_length=11),
        ),
        migrations.AlterField(
            model_name='r2099iderespinf',
            name='nmresp',
            field=models.CharField(default=b'A', max_length=70),
        ),
        migrations.AlterField(
            model_name='r2099iderespinf',
            name='r2099_evtfechaevper',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r2099iderespinf_r2099_evtfechaevper', to='efdreinf.r2099evtFechaEvPer'),
        ),
    ]
