# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('r5011', '0007_auto_20190204_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='r5011infocrtom',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011infocrtom_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011infocrtom',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011infocrtom_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011infototalcontrib',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011infototalcontrib_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011infototalcontrib',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011infototalcontrib_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rcoml',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rcoml_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rcoml',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rcoml_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rcprb',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rcprb_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rcprb',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rcprb_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011regocorrs',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011regocorrs_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011regocorrs',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011regocorrs_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rprest',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rprest_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rprest',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rprest_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rrecrepad',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rrecrepad_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rrecrepad',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rrecrepad_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rtom',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rtom_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='r5011rtom',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r5011rtom_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
