# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissorEventosEfdreinf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=36)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('tabela', models.CharField(max_length=50)),
                ('tabela_salvar', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
                ('tpinsc', models.CharField(max_length=1, choices=[(b'1', '1 - CNPJ'), (b'2', '2 - CPF'), (b'3', '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (b'4', '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('url_recibo', models.CharField(max_length=100, null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'db_table': 'transmissor_eventos_efdreinf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventosEfdreinfTotalizacoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=36)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('tabela', models.CharField(max_length=50)),
                ('tabela_salvar', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
                ('tpinsc', models.CharField(max_length=1, choices=[(b'1', '1 - CNPJ'), (b'2', '2 - CPF'), (b'3', '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (b'4', '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('url_recibo', models.CharField(max_length=100, null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'db_table': 'transmissor_eventos_efdreinf_totalizacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventosEsocial',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=36)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('tabela', models.CharField(max_length=50)),
                ('tabela_salvar', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
                ('tpinsc', models.CharField(max_length=1, choices=[(b'1', '1 - CNPJ'), (b'2', '2 - CPF'), (b'3', '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (b'4', '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('processamento_codigo_resposta', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('url_recibo', models.CharField(max_length=100, null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'db_table': 'transmissor_eventos_esocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventosEsocialTotalizacoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=36)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('tabela', models.CharField(max_length=50)),
                ('tabela_salvar', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
                ('tpinsc', models.CharField(max_length=1, choices=[(b'1', '1 - CNPJ'), (b'2', '2 - CPF'), (b'3', '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (b'4', '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('processamento_codigo_resposta', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('url_recibo', models.CharField(max_length=100, null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'db_table': 'transmissor_eventos_esocial_totalizacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arquivo', models.CharField(max_length=300)),
                ('data_criacao', models.DateField()),
                ('permite_recuperacao', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='arquivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='arquivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'arquivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImportacaoArquivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arquivo', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Aguardando!'), (1, 'Sucesso!'), (2, 'Erro!'), (3, 'Arquivo inv\xe1lido!'), (4, 'Validado'), (5, 'ID do evento j\xe1 est\xe1 cadastrada em nossa base'), (6, 'Processado'), (7, 'Processando'), (8, 'Processado com erros'), (9, 'Vers\xe3o incompat\xedvel')])),
                ('data_hora', models.DateTimeField()),
                ('quant_total', models.IntegerField(null=True, blank=True)),
                ('quant_aguardando', models.IntegerField(null=True, blank=True)),
                ('quant_processado', models.IntegerField(null=True, blank=True)),
                ('quant_importado', models.IntegerField(null=True, blank=True)),
                ('quant_erros', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='importacaoarquivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('importado_por', models.ForeignKey(related_name='importacaoarquivos_importado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='importacaoarquivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['arquivo'],
                'db_table': 'importacao_arquivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImportacaoArquivosEventos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('evento', models.CharField(max_length=100, null=True, blank=True)),
                ('versao', models.CharField(max_length=30, null=True, blank=True)),
                ('identidade_evento', models.CharField(max_length=100, null=True, blank=True)),
                ('identidade', models.IntegerField(null=True, blank=True)),
                ('status', models.IntegerField(blank=True, null=True, choices=[(0, 'Aguardando!'), (1, 'Sucesso!'), (2, 'Erro!'), (3, 'Arquivo inv\xe1lido!'), (4, 'Validado'), (5, 'ID do evento j\xe1 est\xe1 cadastrada em nossa base'), (6, 'Processado'), (7, 'Processando'), (8, 'Processado com erros'), (9, 'Vers\xe3o incompat\xedvel')])),
                ('data_hora', models.DateTimeField(null=True, blank=True)),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='importacaoarquivoseventos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('importacao_arquivos', models.ForeignKey(related_name='importacaoarquivoseventos_importacao_arquivos', to='mensageiro.ImportacaoArquivos')),
                ('modificado_por', models.ForeignKey(related_name='importacaoarquivoseventos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['importacao_arquivos', 'arquivo', 'evento', 'versao', 'identidade_evento', 'identidade'],
                'db_table': 'importacao_arquivos_eventos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegrasDeValidacao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=5000)),
                ('versao', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('registro_campo', models.CharField(max_length=100)),
                ('registro_pai', models.CharField(max_length=100)),
                ('elemento', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=1)),
                ('ocorrencias', models.CharField(max_length=10)),
                ('tamanho', models.CharField(max_length=10)),
                ('casas_decimais', models.CharField(max_length=10)),
                ('obrigatorio', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('descricao', models.TextField()),
                ('tabela', models.CharField(max_length=200, null=True, blank=True)),
                ('valores_validos', models.TextField(null=True, blank=True)),
                ('validacoes_precedencia', models.TextField(null=True, blank=True)),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='regrasdevalidacao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='regrasdevalidacao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'regras_validacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.CharField(max_length=500)),
                ('campos', models.CharField(max_length=500)),
                ('sql', models.TextField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='relatorios_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='relatorios_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'relatorios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('tpinsc', models.IntegerField(blank=True, null=True, choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('empregador_tpinsc', models.IntegerField(blank=True, null=True, choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('empregador_nrinsc', models.CharField(max_length=15, null=True, blank=True)),
                ('nrinsc', models.CharField(max_length=15, null=True, blank=True)),
                ('cpftrab', models.CharField(max_length=11, null=True, blank=True)),
                ('nistrab', models.CharField(max_length=11, null=True, blank=True)),
                ('nmtrab', models.CharField(max_length=70, null=True, blank=True)),
                ('infocota', models.CharField(blank=True, max_length=50, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('matricula', models.CharField(max_length=30, null=True, blank=True)),
                ('dtadm', models.DateField(null=True, blank=True)),
                ('tpregjor', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Submetidos a Hor\xe1rio de Trabalho (Cap. II da CLT)'), (2, '2 - Atividade Externa especificada no Inciso I do Art. 62 da CLT'), (3, '3 - Fun\xe7\xf5es especificadas no Inciso II do Art. 62 da CLT'), (4, '4 - Teletrabalho, previsto no Inciso III do Art. 62 da CLT')])),
                ('dtbase', models.IntegerField(null=True, blank=True)),
                ('cnpjsindcategprof', models.CharField(max_length=14, null=True, blank=True)),
                ('dtposse', models.DateField(null=True, blank=True)),
                ('dtexercicio', models.DateField(null=True, blank=True)),
                ('codcargo', models.CharField(max_length=30, null=True, blank=True)),
                ('nmcargo', models.CharField(max_length=100, null=True, blank=True)),
                ('codcbocargo', models.CharField(max_length=6, null=True, blank=True)),
                ('codfuncao', models.CharField(max_length=30, null=True, blank=True)),
                ('dscfuncao', models.CharField(max_length=100, null=True, blank=True)),
                ('codcbofuncao', models.CharField(max_length=6, null=True, blank=True)),
                ('codcateg', models.IntegerField(null=True, blank=True)),
                ('vrsalfx', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('undsalfixo', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Por Hora'), (2, '2 - Por Dia'), (3, '3 - Por Semana'), (4, '4 - Por Quinzena'), (5, '5 - Por M\xeas'), (6, '6 - Por Tarefa'), (7, '7 - N\xe3o aplic\xe1vel - sal\xe1rio exclusivamente vari\xe1vel')])),
                ('dscsalvar', models.CharField(max_length=255, null=True, blank=True)),
                ('tpcontr', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Prazo indeterminado'), (2, '2 - Prazo determinado')])),
                ('dtterm', models.DateField(null=True, blank=True)),
                ('clauasseg', models.CharField(max_length=50, null=True, blank=True)),
                ('local_tpinsc', models.IntegerField(blank=True, null=True, choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('local_nrinsc', models.CharField(max_length=15, null=True, blank=True)),
                ('local_cnae', models.IntegerField(null=True, blank=True)),
                ('qtdhrssem', models.DecimalField(max_length=4, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('tpjornada', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Jornada com hor\xe1rio di\xe1rio e folga fixos'), (2, '2 - Jornada 12 x 36 (12 horas de trabalho seguidas de 36 horas ininterruptas de descanso)'), (3, '3 - Jornada com hor\xe1rio di\xe1rio fixo e folga vari\xe1vel'), (9, '9 - Demais tipos de jornada')])),
                ('dsctpjorn', models.CharField(max_length=100, null=True, blank=True)),
                ('tmpparc', models.IntegerField(blank=True, null=True, choices=[(0, '0 - N\xe3o \xe9 contrato em tempo parcial'), (1, '1 - Limitado a 25 horas semanais'), (2, '2 - Limitado a 30 horas semanais'), (3, '3 - Limitado a 26 horas semanais')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['transmissor_lote_esocial', 'identidade'],
                'db_table': 'retornos_eventos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventosHorarios',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dia', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Segunda-Feira'), (2, '2 - Ter\xe7a-Feira'), (3, '3 - Quarta-Feira'), (4, '4 - Quinta-Feira'), (5, '5 - Sexta-Feira'), (6, '6 - S\xe1bado'), (7, '7 - Domingo'), (8, '8 - Dia vari\xe1vel')])),
                ('codhorcontrat', models.CharField(max_length=30, null=True, blank=True)),
                ('hrentr', models.CharField(max_length=50, null=True, blank=True)),
                ('hrsaida', models.CharField(max_length=50, null=True, blank=True)),
                ('durjornada', models.IntegerField(null=True, blank=True)),
                ('perhorflexivel', models.CharField(blank=True, max_length=50, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventoshorarios_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventoshorarios_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_eventos', models.ForeignKey(related_name='retornoseventoshorarios_retornos_eventos', blank=True, to='mensageiro.RetornosEventos', null=True)),
            ],
            options={
                'db_table': 'retornos_eventos_horarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventosIntervalos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinterv', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Intervalo em Hor\xe1rio Fixo'), (2, '2 - Intervalo em Hor\xe1rio Vari\xe1vel')])),
                ('durinterv', models.IntegerField(null=True, blank=True)),
                ('iniinterv', models.CharField(max_length=50, null=True, blank=True)),
                ('terminterv', models.CharField(max_length=50, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventosintervalos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventosintervalos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_eventos_horarios', models.ForeignKey(related_name='retornoseventosintervalos_retornos_eventos_horarios', blank=True, to='mensageiro.RetornosEventosHorarios', null=True)),
            ],
            options={
                'db_table': 'retornos_eventos_intervalos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventosOcorrencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Advert\xeancia')])),
                ('codigo', models.IntegerField()),
                ('descricao', models.TextField()),
                ('localizacao', models.TextField(max_length=30, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventosocorrencias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventosocorrencias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_eventos', models.ForeignKey(related_name='retornoseventosocorrencias_retornos_eventos', to='mensageiro.RetornosEventos')),
            ],
            options={
                'db_table': 'retornos_eventos_ocorrencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLote',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome_empresa', models.CharField(unique=True, max_length=200)),
                ('efdreinf_pasta', models.CharField(max_length=200, null=True, blank=True)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('esocial_pasta', models.CharField(max_length=200, null=True, blank=True)),
                ('tipo_inscricao', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('data_abertura', models.DateField()),
                ('validar_eventos', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('envio_automatico', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('logotipo', models.FileField(null=True, upload_to=b'', blank=True)),
                ('endereco_completo', models.TextField()),
                ('esocial_lote_min', models.IntegerField()),
                ('esocial_lote_max', models.IntegerField()),
                ('esocial_timeout', models.DecimalField(max_digits=15, decimal_places=2)),
                ('esocial_intervalo', models.IntegerField()),
                ('esocial_tempo_prox_envio', models.IntegerField(null=True, blank=True)),
                ('esocial_certificado', models.FileField(null=True, upload_to=b'', blank=True)),
                ('esocial_senha', models.CharField(max_length=20, null=True, blank=True)),
                ('efdreinf_lote_min', models.IntegerField()),
                ('efdreinf_lote_max', models.IntegerField()),
                ('efdreinf_timeout', models.DecimalField(max_digits=15, decimal_places=2)),
                ('efdreinf_intervalo', models.IntegerField()),
                ('efdreinf_tempo_prox_envio', models.IntegerField(null=True, blank=True)),
                ('efdreinf_certificado', models.FileField(null=True, upload_to=b'', blank=True)),
                ('efdreinf_senha', models.CharField(max_length=20, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorlote_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorlote_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'transmissores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEfdreinf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contribuinte_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('contribuinte_nrinsc', models.CharField(max_length=15)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('identidade_transmissor', models.CharField(max_length=20, null=True, blank=True)),
                ('codigo_status', models.IntegerField(blank=True, null=True, choices=[(0, '0 - Sucesso'), (1, '1 - Erro'), (2, '2 - Em Processamento')])),
                ('retorno_descricao', models.TextField(null=True, blank=True)),
                ('recepcao_data_hora', models.DateTimeField(max_length=50, null=True, blank=True)),
                ('recepcao_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('protocolo', models.CharField(max_length=50, null=True, blank=True)),
                ('numero_protocolo_fechamento', models.CharField(max_length=50, null=True, blank=True)),
                ('processamento_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('tempo_estimado_conclusao', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteefdreinf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteefdreinf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor', models.ForeignKey(related_name='transmissorloteefdreinf_transmissor', blank=True, to='mensageiro.TransmissorLote', max_length=1, null=True)),
            ],
            options={
                'db_table': 'transmissor_lote_efdreinf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEfdreinfOcorrencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('resposta_codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, '1 - Aviso'), (2, '2 - Erro')])),
                ('localizacao', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteefdreinfocorrencias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteefdreinfocorrencias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor_lote_efdreinf', models.ForeignKey(related_name='transmissorloteefdreinfocorrencias_transmissor_lote_efdreinf', to='mensageiro.TransmissorLoteEfdreinf')),
            ],
            options={
                'db_table': 'transmissor_lote_efdreinf_ocorrencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEsocial',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empregador_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('empregador_nrinsc', models.CharField(max_length=15)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('resposta_codigo', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('resposta_descricao', models.TextField(null=True, blank=True)),
                ('recepcao_data_hora', models.DateTimeField(max_length=50, null=True, blank=True)),
                ('recepcao_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('protocolo', models.CharField(max_length=50, null=True, blank=True)),
                ('processamento_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('tempo_estimado_conclusao', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteesocial_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteesocial_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor', models.ForeignKey(related_name='transmissorloteesocial_transmissor', blank=True, to='mensageiro.TransmissorLote', max_length=1, null=True)),
            ],
            options={
                'db_table': 'transmissor_lote_esocial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEsocialOcorrencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('resposta_codigo', models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Advert\xeancia')])),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Advert\xeancia')])),
                ('localizacao', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteesocialocorrencias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteesocialocorrencias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor_lote_esocial', models.ForeignKey(related_name='transmissorloteesocialocorrencias_transmissor_lote_esocial', to='mensageiro.TransmissorLoteEsocial')),
            ],
            options={
                'db_table': 'transmissor_lote_esocial_ocorrencias',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='retornoseventos',
            name='transmissor_lote_esocial',
            field=models.ForeignKey(related_name='retornoseventos_transmissor_lote_esocial', to='mensageiro.TransmissorLoteEsocial'),
        ),
    ]
