# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 18:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensageiro', '0025_auto_20190513_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificados',
            options={'managed': True, 'ordering': ['certificado'], 'permissions': (('can_view_certificados', 'Can view certificados'),), 'verbose_name': 'Certificados'},
        ),
        migrations.RemoveField(
            model_name='certificados',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='certificados',
            name='certificado',
            field=models.FileField(default='aaa', storage=django.core.files.storage.FileSystemStorage(location=b'/Users/mvasconcellos/PycharmProjects/emensageriapro/certificado/'), upload_to=b''),
            preserve_default=False,
        ),
    ]
