# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r5001', '0012_auto_20190514_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r5001infocrtom',
            name='crtom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r5001infototal',
            name='nrinsc',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='r5001infototal',
            name='tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)'), (5, '5 - CGC')], null=True),
        ),
        migrations.AlterField(
            model_name='r5001rcoml',
            name='crcoml',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r5001rcoml',
            name='vlrcrcoml',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rcprb',
            name='crcprb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r5001rcprb',
            name='vlrcrcprb',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001regocorrs',
            name='codresp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='r5001regocorrs',
            name='dscresp',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='r5001regocorrs',
            name='localerroaviso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='r5001regocorrs',
            name='tpocorr',
            field=models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Aviso')], null=True),
        ),
        migrations.AlterField(
            model_name='r5001rprest',
            name='nrinsctomador',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rprest',
            name='tpinsctomador',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r5001rprest',
            name='vlrtotalbaseret',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rprest',
            name='vlrtotalretprinc',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecespetdesp',
            name='crrecespetdesp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecespetdesp',
            name='vlrcrrecespetdesp',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecespetdesp',
            name='vlrreceitatotal',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecrepad',
            name='cnpjassocdesp',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecrepad',
            name='crrecrepad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecrepad',
            name='vlrcrrecrepad',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rrecrepad',
            name='vlrtotalrep',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rtom',
            name='cnpjprestador',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='r5001rtom',
            name='vlrtotalbaseret',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
