# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r2020', '0014_auto_20190530_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r2020infoprocretad',
            options={'managed': True, 'ordering': ['r2020_evtservprest', 'tpprocretadic', 'nrprocretadic', 'valoradic'], 'permissions': (('can_view_r2020infoProcRetAd', 'Can view R2020INFOPROCRETAD'), ('can_view_menu_r2020infoProcRetAd', 'Can view menu R2020INFOPROCRETAD'))},
        ),
        migrations.AlterModelOptions(
            name='r2020infoprocretpr',
            options={'managed': True, 'ordering': ['r2020_evtservprest', 'tpprocretprinc', 'nrprocretprinc', 'valorprinc'], 'permissions': (('can_view_r2020infoProcRetPr', 'Can view R2020INFOPROCRETPR'), ('can_view_menu_r2020infoProcRetPr', 'Can view menu R2020INFOPROCRETPR'))},
        ),
        migrations.AlterModelOptions(
            name='r2020infotpserv',
            options={'managed': True, 'ordering': ['r2020_nfs', 'tpservico', 'vlrbaseret', 'vlrretencao'], 'permissions': (('can_view_r2020infoTpServ', 'Can view R2020INFOTPSERV'), ('can_view_menu_r2020infoTpServ', 'Can view menu R2020INFOTPSERV'))},
        ),
        migrations.AlterModelOptions(
            name='r2020nfs',
            options={'managed': True, 'ordering': ['r2020_evtservprest', 'serie', 'numdocto', 'dtemissaonf', 'vlrbruto'], 'permissions': (('can_view_r2020nfs', 'Can view R2020NFS'), ('can_view_menu_r2020nfs', 'Can view menu R2020NFS'))},
        ),
    ]
