# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2231', '0013_auto_20190525_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s2231fimcessao',
            options={'managed': True, 'ordering': ['s2231_evtcessao', 'dttermcessao'], 'permissions': (('can_view_s2231fimCessao', 'Can view S2231FIMCESSAO'), ('can_view_menu_s2231fimCessao', 'Can view menu S2231FIMCESSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s2231inicessao',
            options={'managed': True, 'ordering': ['s2231_evtcessao', 'dtinicessao', 'cnpjcess', 'infonus', 'indcessao'], 'permissions': (('can_view_s2231iniCessao', 'Can view S2231INICESSAO'), ('can_view_menu_s2231iniCessao', 'Can view menu S2231INICESSAO'))},
        ),
    ]
