# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1070', '0004_auto_20181213_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s1070alteracao',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070alteracaodadosprocjud',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070alteracaoinfosusp',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070alteracaonovavalidade',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070exclusao',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070inclusao',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070inclusaodadosprocjud',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s1070inclusaoinfosusp',
            name='excluido',
            field=models.NullBooleanField(default=False),
        ),
    ]
