# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1070', '0005_auto_20190202_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1070alteracao',
            options={'managed': True, 'ordering': ['s1070_evttabprocesso', 'tpproc', 'nrproc', 'inivalid', 'indmatproc'], 'permissions': (('can_view_s1070_alteracao', 'Can view s1070_alteracao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070alteracaodadosprocjud',
            options={'managed': True, 'ordering': ['s1070_alteracao', 'ufvara', 'codmunic', 'idvara'], 'permissions': (('can_view_s1070_alteracao_dadosprocjud', 'Can view s1070_alteracao_dadosprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070alteracaoinfosusp',
            options={'managed': True, 'ordering': ['s1070_alteracao', 'codsusp', 'indsusp', 'dtdecisao', 'inddeposito'], 'permissions': (('can_view_s1070_alteracao_infosusp', 'Can view s1070_alteracao_infosusp'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070alteracaonovavalidade',
            options={'managed': True, 'ordering': ['s1070_alteracao', 'inivalid'], 'permissions': (('can_view_s1070_alteracao_novavalidade', 'Can view s1070_alteracao_novavalidade'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070exclusao',
            options={'managed': True, 'ordering': ['s1070_evttabprocesso', 'tpproc', 'nrproc', 'inivalid'], 'permissions': (('can_view_s1070_exclusao', 'Can view s1070_exclusao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070inclusao',
            options={'managed': True, 'ordering': ['s1070_evttabprocesso', 'tpproc', 'nrproc', 'inivalid', 'indmatproc'], 'permissions': (('can_view_s1070_inclusao', 'Can view s1070_inclusao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070inclusaodadosprocjud',
            options={'managed': True, 'ordering': ['s1070_inclusao', 'ufvara', 'codmunic', 'idvara'], 'permissions': (('can_view_s1070_inclusao_dadosprocjud', 'Can view s1070_inclusao_dadosprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070inclusaoinfosusp',
            options={'managed': True, 'ordering': ['s1070_inclusao', 'codsusp', 'indsusp', 'dtdecisao', 'inddeposito'], 'permissions': (('can_view_s1070_inclusao_infosusp', 'Can view s1070_inclusao_infosusp'),)},
        ),
    ]
