# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efdreinf', '0010_auto_20180822_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r1000evtinfocontriocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontriocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontriocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocessoocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocessoocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocessoocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtomocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtomocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtomocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprestocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprestocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprestocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprecocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprecocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprecocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprepocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprepocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprepocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprodocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprodocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprodocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprbocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprbocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprbocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivsocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivsocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivsocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevperocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevperocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevperocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevperocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevperocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevperocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivoocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivoocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivoocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r5001evttotalocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r5001evttotalocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r5001evttotalocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontribocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontribocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontribocorrencias',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusaoocorrencias',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusaoocorrencias',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusaoocorrencias',
            name='modificado_por',
        ),
        migrations.DeleteModel(
            name='r1000evtInfoContriOcorrencias',
        ),
        migrations.DeleteModel(
            name='r1070evtTabProcessoOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2010evtServTomOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2020evtServPrestOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2030evtAssocDespRecOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2040evtAssocDespRepOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2050evtComProdOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2060evtCPRBOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2070evtPgtosDivsOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2098evtReabreEvPerOcorrencias',
        ),
        migrations.DeleteModel(
            name='r2099evtFechaEvPerOcorrencias',
        ),
        migrations.DeleteModel(
            name='r3010evtEspDesportivoOcorrencias',
        ),
        migrations.DeleteModel(
            name='r5001evtTotalOcorrencias',
        ),
        migrations.DeleteModel(
            name='r5011evtTotalContribOcorrencias',
        ),
        migrations.DeleteModel(
            name='r9000evtExclusaoOcorrencias',
        ),
    ]
