# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efdreinf', '0014_auto_20180824_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r1000evtinfocontri',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r1070evttabprocesso',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2010evtservtom',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2020evtservprest',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2030evtassocdesprec',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2040evtassocdesprep',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2050evtcomprod',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2060evtcprb',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2070evtpgtosdivs',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2098evtreabreevper',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r2099evtfechaevper',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r3010evtespdesportivo',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r5001evttotal',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r5011evttotalcontrib',
            name='recibo_numero',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='processamento_codigo_resposta',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='processamento_data_hora',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='processamento_descricao_resposta',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='processamento_versao_app_processamento',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='recepcao_data_hora',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='recepcao_protocolo_envio_lote',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='recepcao_tp_amb',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='recepcao_versao_app',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='recibo_hash',
        ),
        migrations.RemoveField(
            model_name='r9000evtexclusao',
            name='recibo_numero',
        ),
        migrations.AddField(
            model_name='r1000evtinfocontri',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r1000evtinfocontri',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r1000evtinfocontri',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r1070evttabprocesso',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r1070evttabprocesso',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r1070evttabprocesso',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2010evtservtom',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2010evtservtom',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2010evtservtom',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2020evtservprest',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2020evtservprest',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2020evtservprest',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2030evtassocdesprec',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2030evtassocdesprec',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2030evtassocdesprec',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2040evtassocdesprep',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2040evtassocdesprep',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2040evtassocdesprep',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2050evtcomprod',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2050evtcomprod',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2050evtcomprod',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2060evtcprb',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2060evtcprb',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2060evtcprb',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2070evtpgtosdivs',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2070evtpgtosdivs',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2070evtpgtosdivs',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2098evtreabreevper',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2098evtreabreevper',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2098evtreabreevper',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2099evtfechaevper',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2099evtfechaevper',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r2099evtfechaevper',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r9000evtexclusao',
            name='cdretorno',
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r9000evtexclusao',
            name='descretorno',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='r9000evtexclusao',
            name='dhprocess',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
