DELETE FROM public.esocial_logradouros_tipos;
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('A', 'Área', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AC', 'Acesso', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ACA', 'Acampamento', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ACL', 'Acesso Local', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AD', 'Adro', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AE', 'Área Especial', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AER', 'Aeroporto', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AL', 'Alameda', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ALD', 'Aldeia', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AMD', 'Avenida Marginal Direita', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AME', 'Avenida Marginal Esquerda', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AN', 'Anel Viário', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ANT', 'Antiga Estrada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ART', 'Artéria', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AT', 'Alto', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ATL', 'Atalho', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('A V', 'Área Verde', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AV', 'Avenida', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AVC', 'Avenida Contorno', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AVM', 'Avenida Marginal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('AVV', 'Avenida Velha', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BAL', 'Balneário', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BC', 'Beco', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BCO', 'Buraco', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BEL', 'Belvedere', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BL', 'Bloco', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BLO', 'Balão', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BLS', 'Blocos', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BLV', 'Bulevar', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BSQ', 'Bosque', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BVD', 'Boulevard', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('BX', 'Baixa', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('C', 'Cais', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CAL', 'Calçada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CAM', 'Caminho', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CAN', 'Canal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CH', 'Chácara', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CHA', 'Chapadão', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CIC', 'Ciclovia', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CIR', 'Circular', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CJ', 'Conjunto', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CJM', 'Conjunto Mutirão', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CMP', 'Complexo Viário', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('COL', 'Colônia', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('COM', 'Comunidade', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CON', 'Condomínio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('COND', 'Condomínio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('COR', 'Corredor', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CPO', 'Campo', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CRG', 'Córrego', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('CTN', 'Contorno', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('DSC', 'Descida', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('DSV', 'Desvio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('DT', 'Distrito', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EB', 'Entre Bloco', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EIM', 'Estrada Intermunicipal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ENS', 'Enseada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ENT', 'Entrada Particular', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EQ', 'Entre Quadra', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESC', 'Escada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESD', 'Escadaria', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESE', 'Estrada Estadual', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESI', 'Estrada Vicinal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESL', 'Estrada de Ligação', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESM', 'Estrada Municipal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESP', 'Esplanada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESS', 'Estrada de Servidão', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EST', 'Estrada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ESV', 'Estrada Velha', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ETA', 'Estrada Antiga', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ETC', 'Estação', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ETD', 'Estádio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ETN', 'Estância', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ETP', 'Estrada Particular', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ETT', 'Estacionamento', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EVA', 'Evangélica', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EVD', 'Elevada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('EX', 'Eixo Industrial', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('FAV', 'Favela', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('FAZ', 'Fazenda', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('FER', 'Ferrovia', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('FNT', 'Fonte', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('FRA', 'Feira', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('FTE', 'Forte', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('GAL', 'Galeria', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('GJA', 'Granja', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('HAB', 'Núcleo Habitacional', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('IA', 'Ilha', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('IGP', 'Igarapé', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('IND', 'Indeterminado', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('IOA', 'Ilhota', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('JD', 'Jardim', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('JDE', 'Jardinete', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('LD', 'Ladeira', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('LGA', 'Lagoa', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('LGO', 'Lago', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('LOT', 'Loteamento', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('LRG', 'Largo', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('LT', 'Lote', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('MER', 'Mercado', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('MNA', 'Marina', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('MOD', 'Modulo', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('MRG', 'Projeção', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('MRO', 'Morro', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('MTE', 'Monte', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('NUC', 'Núcleo', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('NUR', 'Núcleo Rural', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('O', 'Outros', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('OUT', 'Outeiro', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PAR', 'Paralela', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PAS', 'Passeio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PAT', 'Pátio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PC', 'Praça', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PCE', 'Praça de Esportes', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PDA', 'Parada', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PDO', 'Paradouro', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PNT', 'Ponta', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PR', 'Praia', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PRL', 'Prolongamento', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PRM', 'Parque Municipal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PRQ', 'Parque', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PRR', 'Parque Residencial', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PSA', 'Passarela', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PSG', 'Passagem', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PSP', 'Passagem de Pedestre', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PSS', 'Passagem Subterrânea', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PTE', 'Ponte', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('PTO', 'Porto', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('Q', 'Quadra', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('QTA', 'Quinta', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('QTS', 'Quintas', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('R', 'Rua', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('R I', 'Rua Integração', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('R L', 'Rua de Ligação', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('R P', 'Rua Particular', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('R V', 'Rua Velha', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RAM', 'Ramal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RCR', 'Recreio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('REC', 'Recanto', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RER', 'Retiro', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RES', 'Residencial', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RET', 'Reta', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RLA', 'Ruela', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RMP', 'Rampa', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ROA', 'Rodo Anel', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ROD', 'Rodovia', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ROT', 'Rotula', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RPE', 'Rua de Pedestre', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RPR', 'Margem', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RTN', 'Retorno', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('RTT', 'Rotatória', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('SEG', 'Segunda Avenida', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('SIT', 'Sitio', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('SRV', 'Servidão', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ST', 'Setor', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('SUB', 'Subida', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TCH', 'Trincheira', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TER', 'Terminal', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TR', 'Trecho', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TRV', 'Trevo', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TUN', 'Túnel', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TV', 'Travessa', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TVP', 'Travessa Particular', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('TVV', 'Travessa Velha', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('UNI', 'Unidade', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('V', 'Via', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('V C', 'Via Coletora', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('V L', 'Via Local', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VAC', 'Via de Acesso', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VAL', 'Vala', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VCO', 'Via Costeira', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VD', 'Viaduto', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('V-E', 'Via Expressa', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VER', 'Vereda', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VEV', 'Via Elevado', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VL', 'Vila', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VLA', 'Viela', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VLE', 'Vale', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VLT', 'Via Litorânea', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VPE', 'Via de Pedestre', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('VRT', 'Variante', now(), 1, False);
INSERT INTO public.esocial_logradouros_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('ZIG', 'Zigue-Zague', now(), 1, False);
