DELETE FROM public.esocial_naturezas_juridicas;
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1015', 'Órgão Público do Poder Executivo Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1023', 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1031', 'Órgão Público do Poder Executivo Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1040', 'Órgão Público do Poder Legislativo Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1058', 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1066', 'Órgão Público do Poder Legislativo Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1074', 'Órgão Público do Poder Judiciário Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1082', 'Órgão Público do Poder Judiciário Estadual', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1104', 'Autarquia Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1112', 'Autarquia Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1120', 'Autarquia Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1139', 'Fundação Pública de Direito Público Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1147', 'Fundação Pública de Direito Público Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1155', 'Fundação Pública de Direito Público Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1163', 'Órgão Público Autônomo Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1171', 'Órgão Público Autônomo Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1180', 'Órgão Público Autônomo Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1198', 'Comissão Polinacional', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1201', 'Fundo Público', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1210', 'Consórcio Público de Direito Público (Associação Pública)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1228', 'Consórcio Público de Direito Privado', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1236', 'Estado ou Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1244', 'Município', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1252', 'Fundação Pública de Direito Privado Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1260', 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '1279', 'Fundação Pública de Direito Privado Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2011', 'Empresa Pública', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2038', 'Sociedade de Economia Mista', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2046', 'Sociedade Anônima Aberta', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2054', 'Sociedade Anônima Fechada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2062', 'Sociedade Empresária Limitada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2070', 'Sociedade Empresária em Nome Coletivo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2089', 'Sociedade Empresária em Comandita Simples', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2097', 'Sociedade Empresária em Comandita por Ações', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2127', 'Sociedade em Conta de Participação', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2135', 'Empresário (Individual)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2143', 'Cooperativa', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2151', 'Consórcio de Sociedades', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2160', 'Grupo de Sociedades', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2178', 'Estabelecimento, no Brasil, de Sociedade Estrangeira', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2194', 'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2216', 'Empresa Domiciliada no Exterior', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2224', 'Clube/Fundo de Investimento', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2232', 'Sociedade Simples Pura', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2240', 'Sociedade Simples Limitada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2259', 'Sociedade Simples em Nome Coletivo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2267', 'Sociedade Simples em Comandita Simples', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2275', 'Empresa Binacional', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2283', 'Consórcio de Empregadores', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2291', 'Consórcio Simples', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2305', 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2313', 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2321', 'Sociedade Unipessoal de Advogados', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '2330', 'Cooperativas de Consumo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3034', 'Serviço Notarial e Registral (Cartório)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3069', 'Fundação Privada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3077', 'Serviço Social Autônomo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3085', 'Condomínio Edilício', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3107', 'Comissão de Conciliação Prévia', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3115', 'Entidade de Mediação e Arbitragem', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3131', 'Entidade Sindical', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3204', 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3212', 'Fundação ou Associação Domiciliada no Exterior', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3220', 'Organização Religiosa', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3239', 'Comunidade Indígena', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3247', 'Fundo Privado', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3255', 'Órgão de Direção Nacional de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3263', 'Órgão de Direção Regional de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3271', 'Órgão de Direção Local de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3280', 'Comitê Financeiro de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3298', 'Frente Plebiscitária ou Referendária', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3306', 'Organização Social (OS)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3310', 'Demais Condomínios', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '3999', 'Associação Privada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '4014', 'Empresa Individual Imobiliária', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '4022', 'Segurado Especial', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '4081', 'Contribuinte individual', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '4090', 'Candidato a Cargo Político Eletivo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '4111', 'Leiloeiro', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '4124', 'Produtor Rural (Pessoa Física)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('5', '5010', 'Organização Internacional', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('5', '5029', 'Representação Diplomática Estrangeira', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('5', '5037', 'Outras Instituições Extraterritoriais', now(), 1, False);
