DELETE FROM public.esocial_paises;
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('008', 'Abu Dhabi', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('009', 'Dirce', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('013', 'Afeganistao', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('017', 'Albania, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('020', 'Alboran-Perejil,Ilhas', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('023', 'Alemanha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('025', 'Alemanha, Republica Democratica', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('031', 'Burkina Faso', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('037', 'Andorra', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('040', 'Angola', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('041', 'Anguilla', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('043', 'Antigua E Barbuda', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('047', 'Antilhas Holandesas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('053', 'Arabia Saudita', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('059', 'Argelia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('063', 'Argentina', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('064', 'Armenia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('065', 'Aruba', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('069', 'Australia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('072', 'Austria', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('073', 'Azerbaijao, Republica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('077', 'Bahamas, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('080', 'Bahrein, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('081', 'Bangladesh', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('083', 'Barbados', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('085', 'Belarus, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('087', 'Belgica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('088', 'Belize', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('090', 'Bermudas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('093', 'Mianmar (BIRMANIA)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('097', 'Bolivia, Estado Plurinacional Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('098', 'Bosnia-Herzegovina (REPUBLICA Da)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('100', 'Int.Z.F.Manaus', 1991-12-01, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('101', 'Botsuana', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('105', 'Brasil', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('106', 'Fretado P/Brasil', 1991-12-01, 1996-11-14, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('108', 'Brunei', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('111', 'Bulgaria, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('115', 'Burundi', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('119', 'Butao', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('127', 'Cabo Verde, Republica De', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('131', 'Cachemira', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('137', 'Cayman, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('141', 'Camboja', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('145', 'Camaroes', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('149', 'Canada', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('150', 'Jersey, Ilha Do Canal', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('151', 'Canarias, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('152', 'Canal,Ilhas', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('153', 'Cazaquistao, Republica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('154', 'Catar', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('158', 'Chile', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('160', 'China, Republica Popular', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('161', 'Formosa (TAIWAN)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('163', 'Chipre', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('165', 'Cocos(Keeling),Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('169', 'Colombia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('173', 'Comores, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('177', 'Congo', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('183', 'Cook, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('187', 'Coreia (DO Norte), Rep.Pop.Democratica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('190', 'Coreia (DO Sul), Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('193', 'Costa Do Marfim', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('195', 'Croacia (REPUBLICA Da)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('196', 'Costa Rica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('198', 'Coveite', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('199', 'Cuba', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('229', 'Benin', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('232', 'Dinamarca', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('235', 'Dominica,Ilha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('237', 'Dubai', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('239', 'Equador', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('240', 'Egito', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('243', 'Eritreia', 2006-07-17, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('244', 'Emirados Arabes Unidos', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('245', 'Espanha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('246', 'Eslovenia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('247', 'Eslovaca, Republica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('249', 'Estados Unidos', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('251', 'Estonia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('253', 'Etiopia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('255', 'Falkland (ILHAS Malvinas)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('259', 'Feroe, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('263', 'Fezzan', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('267', 'Filipinas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('271', 'Finlandia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('275', 'Franca', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('281', 'Gabao', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('285', 'Gambia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('289', 'Gana', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('291', 'Georgia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('293', 'Gibraltar', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('297', 'Granada', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('301', 'Grecia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('305', 'Groenlandia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('309', 'Guadalupe', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('313', 'Guam', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('317', 'Guatemala', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('325', 'Guiana Francesa', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('329', 'Guine', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('331', 'Guine-Equatorial', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('334', 'Guine-Bissau', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('337', 'Guiana', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('341', 'Haiti', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('345', 'Honduras', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('351', 'Hong Kong', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('355', 'Hungria, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('357', 'Iemen', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('358', 'Iemem Do Sul', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('359', 'Man, Ilha De', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('361', 'India', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('365', 'Indonesia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('367', 'Inglaterra', Null, 1997-03-18, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('369', 'Iraque', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('372', 'Ira, Republica Islamica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('375', 'Irlanda', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('379', 'Islandia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('383', 'Israel', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('386', 'Italia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('388', 'Servia E Montenegro', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('391', 'Jamaica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('395', 'Jammu', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('396', 'Johnston, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('399', 'Japao', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('403', 'Jordania', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('411', 'Kiribati', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('420', 'Laos, Rep.Pop.Democr.Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('423', 'Lebuan,Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('426', 'Lesoto', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('427', 'Letonia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('431', 'Libano', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('434', 'Liberia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('438', 'Libia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('440', 'Liechtenstein', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('442', 'Lituania, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('445', 'Luxemburgo', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('447', 'Macau', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('449', 'Macedonia, Ant.Rep.Iugoslava', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('450', 'Madagascar', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('452', 'Ilha Da Madeira', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('455', 'Malasia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('458', 'Malavi', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('461', 'Maldivas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('464', 'Mali', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('467', 'Malta', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('472', 'Marianas Do Norte', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('474', 'Marrocos', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('476', 'Marshall,Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('477', 'Martinica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('485', 'Mauricio', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('488', 'Mauritania', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('490', 'Midway, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('493', 'Mexico', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('494', 'Moldavia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('495', 'Monaco', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('497', 'Mongolia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('499', 'Micronesia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('501', 'Montserrat,Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('505', 'Mocambique', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('507', 'Namibia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('508', 'Nauru', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('511', 'Christmas,Ilha (NAVIDAD)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('517', 'Nepal', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('521', 'Nicaragua', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('525', 'Niger', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('528', 'Nigeria', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('531', 'Niue,Ilha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('535', 'Norfolk,Ilha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('538', 'Noruega', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('542', 'Nova Caledonia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('545', 'Papua Nova Guine', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('548', 'Nova Zelandia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('551', 'Vanuatu', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('556', 'Oma', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('563', 'Pacifico,Ilhas Do (ADMINISTRACAO Dos Eua)', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('566', 'Pacifico,Ilhas Do (POSSESSAO Dos Eua)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('569', 'Pacifico,Ilhas Do (TERRITORIO Em Fideicomisso Dos', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('573', 'Paises Baixos (HOLANDA)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('575', 'Palau', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('576', 'Paquistao', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('578', 'Palestina', 2011-01-25, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('580', 'Panama', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('583', 'Papua Nova Guiné', 1991-12-01, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('586', 'Paraguai', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('589', 'Peru', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('593', 'Pitcairn,Ilha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('599', 'Polinesia Francesa', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('603', 'Polonia, Republica Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('607', 'Portugal', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('611', 'Porto Rico', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('623', 'Quenia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('625', 'Quirguiz, Republica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('628', 'Reino Unido', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('640', 'Republica Centro-Africana', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('647', 'Republica Dominicana', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('660', 'Reuniao, Ilha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('665', 'Zimbabue', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('670', 'Romenia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('675', 'Ruanda', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('676', 'Russia, Federacao Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('677', 'Salomao, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('678', 'Saint Kitts E Nevis', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('685', 'Saara Ocidental', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('687', 'El Salvador', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('690', 'Samoa', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('691', 'Samoa Americana', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('695', 'Sao Cristovao E Neves,Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('697', 'San Marino', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('700', 'Sao Pedro E Miquelon', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('705', 'Sao Vicente E Granadinas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('710', 'Santa Helena', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('715', 'Santa Lucia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('720', 'Sao Tome E Principe, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('728', 'Senegal', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('731', 'Seychelles', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('735', 'Serra Leoa', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('738', 'Sikkim', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('741', 'Cingapura', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('744', 'Siria, Republica Arabe Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('748', 'Somalia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('750', 'Sri Lanka', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('754', 'Suazilandia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('756', 'Africa Do Sul', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('759', 'Sudao', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('764', 'Suecia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('767', 'Suica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('770', 'Suriname', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('772', 'Tadjiquistao, Republica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('776', 'Tailandia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('780', 'Tanzania, Rep.Unida Da', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('782', 'Territorio Brit.Oc.Indico', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('783', 'Djibuti', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('785', 'Territorio da Alta Comissao do Pacifico Ocidental', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('788', 'Chade', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('790', 'Tchecoslovaquia', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('791', 'Tcheca, Republica', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('795', 'Timor Leste', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('800', 'Togo', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('805', 'Toquelau,Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('810', 'Tonga', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('815', 'Trinidad E Tobago', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('820', 'Tunisia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('823', 'Turcas E Caicos,Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('824', 'Turcomenistao, Republica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('827', 'Turquia', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('828', 'Tuvalu', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('831', 'Ucrania', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('833', 'Uganda', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('840', 'Uniao Das Republicas Socialistas Sovieticas', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('845', 'Uruguai', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('847', 'Uzbequistao, Republica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('848', 'Vaticano, Est.Da Cidade Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('850', 'Venezuela', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('855', 'Vietname Norte', Null, 1996-12-13, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('858', 'Vietna', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('863', 'Virgens,Ilhas (BRITANICAS)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('866', 'Virgens,Ilhas (E.U.A.)', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('870', 'Fiji', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('873', 'Wake, Ilha', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('875', 'Wallis E Futuna, Ilhas', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('888', 'Congo, Republica Democratica Do', Null, Null, now(), 1, False);
INSERT INTO public.esocial_paises (codigo, nome, data_criacao, data_extincao, criado_em, criado_por_id, excluido) VALUES ('890', 'Zambia', Null, Null, now(), 1, False);