DELETE FROM public.esocial_arquivos_esocial_tipos;
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1000', 'Informações do Empregador/Contribuinte/Órgão Público', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1005', 'Tabela de Estabelecimentos, Obras de Construção Civil ou Unidades de Órgãos Públicos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1010', 'Tabela de Rubricas', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1020', 'Tabela de Lotações Tributárias', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1030', 'Tabela de Cargos/Empregos Públicos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1035', 'Tabela de Carreiras Públicas', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1040', 'Tabela de Funções/Cargos em Comissão', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1050', 'Tabela de Horários/Turnos de Trabalho', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1060', 'Tabela de Ambientes de Trabalho', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1065', 'Tabela de Equipamentos de Proteção', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1070', 'Tabela de Processos Administrativos/Judiciais', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1080', 'Tabela de Operadores Portuários', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1200', 'Remuneração do Trabalhador vinculado ao Regime Geral de Previdência Social - RGPS', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1202', 'Remuneração do Trabalhador vinculado a Regime Próprio de Previdência Social - RPPS', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1207', 'Benefícios - Entes Públicos–', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1210', 'Pagamentos de Rendimentos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1250', 'Aquisição de Produção Rural', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1260', 'Comercialização da Produção Rural Pessoa Física', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1270', 'Contratação de Trabalhadores Avulsos Não Portuários', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1280', 'Informações Complementares aos Eventos Periódicos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1295', 'Solicitação de Totalização para Pagamento em Contingência', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1298', 'Reabertura dos Eventos Periódicos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1299', 'Fechamento dos Eventos Periódicos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-1300', 'Contribuição Sindical Patronal', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2190', 'Admissão de Trabalhador - Registro Preliminar', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2200', 'Admissão / Ingresso de Trabalhador', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2205', 'Alteração de Dados Cadastrais do Trabalhador', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2206', 'Alteração de Contrato de Trabalho/Relação Estatutária', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2210', 'Comunicação de Acidente de Trabalho', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2220', 'Monitoramento da saúde do trabalhador', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2230', 'Afastamento Temporário', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2231', 'Cessão/Exercício em Outro Órgão', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2240', 'Condições Ambientais do Trabalho - Fatores de Risco', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2245', 'Treinamentos e Capacitações', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2250', 'Aviso Prévio', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2260', 'Convocação para Trabalho Intermitente', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2298', 'Reintegração/Outros Provimentos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2299', 'Desligamento', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2300', 'Trabalhador Sem Vínculo de Emprego/Estatutário - Início', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2306', 'Trabalhador Sem Vínculo de Emprego/Estatutário - Alteração Contratual', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2399', 'Trabalhador Sem Vínculo de Emprego/Estatutário - Término', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2400', 'Cadastro de Beneficiários - Entes Públicos - Início', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2405', 'Cadastro de Beneficiários - Entes Públicos - Alteração', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2410', 'Cadastro de Benefícios - Entes Públicos - Início', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2416', 'Cadastro de Benefícios - Entes Públicos - Alteração', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-2420', 'Cadastro de Benefícios - Entes Públicos - Término', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-3000', 'Exclusão de Eventos', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-5001', 'Informações das contribuições sociais por Trabalhador', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-5002', 'Imposto de Renda Retido na Fonte por Trabalhador', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-5011', 'Informações das contribuições sociais consolidadas por contribuinte', now(), 1, False);
INSERT INTO public.esocial_arquivos_esocial_tipos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('S-5012', 'Informações do IRRF consolidadas por Contribuinte', now(), 1, False);