DELETE FROM public.esocial_naturezas_juridicas;
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '101-5', 'Órgão Público do Poder Executivo Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '102-3', 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '103-1', 'Órgão Público do Poder Executivo Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '104-0', 'Órgão Público do Poder Legislativo Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '105-8', 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '106-6', 'Órgão Público do Poder Legislativo Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '107-4', 'Órgão Público do Poder Judiciário Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '108-2', 'Órgão Público do Poder Judiciário Estadual', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '110-4', 'Autarquia Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '111-2', 'Autarquia Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '112-0', 'Autarquia Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '113-9', 'Fundação Pública de Direito Público Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '114-7', 'Fundação Pública de Direito Público Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '115-5', 'Fundação Pública de Direito Público Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '116-3', 'Órgão Público Autônomo Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '117-1', 'Órgão Público Autônomo Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '118-0', 'Órgão Público Autônomo Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '119-8', 'Comissão Polinacional', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '120-1', 'Fundo Público', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '121-0', 'Consórcio Público de Direito Público (Associação Pública)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '122-8', 'Consórcio Público de Direito Privado', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '123-6', 'Estado ou Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '124-4', 'Município', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '125-2', 'Fundação Pública de Direito Privado Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '126-0', 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1', '127-9', 'Fundação Pública de Direito Privado Municipal', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '201-1', 'Empresa Pública', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '203-8', 'Sociedade de Economia Mista', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '204-6', 'Sociedade Anônima Aberta', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '205-4', 'Sociedade Anônima Fechada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '206-2', 'Sociedade Empresária Limitada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '207-0', 'Sociedade Empresária em Nome Coletivo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '208-9', 'Sociedade Empresária em Comandita Simples', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '209-7', 'Sociedade Empresária em Comandita por Ações', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '212-7', 'Sociedade em Conta de Participação', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '213-5', 'Empresário (Individual)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '214-3', 'Cooperativa', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '215-1', 'Consórcio de Sociedades', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '216-0', 'Grupo de Sociedades', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '217-8', 'Estabelecimento, no Brasil, de Sociedade Estrangeira', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '219-4', 'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '221-6', 'Empresa Domiciliada no Exterior', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '222-4', 'Clube/Fundo de Investimento', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '223-2', 'Sociedade Simples Pura', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '224-0', 'Sociedade Simples Limitada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '225-9', 'Sociedade Simples em Nome Coletivo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '226-7', 'Sociedade Simples em Comandita Simples', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '227-5', 'Empresa Binacional', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '228-3', 'Consórcio de Empregadores', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '229-1', 'Consórcio Simples', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '230-5', 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '231-3', 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '232-1', 'Sociedade Unipessoal de Advogados', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2', '233-0', 'Cooperativas de Consumo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '303-4', 'Serviço Notarial e Registral (Cartório)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '306-9', 'Fundação Privada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '307-7', 'Serviço Social Autônomo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '308-5', 'Condomínio Edilício', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '310-7', 'Comissão de Conciliação Prévia', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '311-5', 'Entidade de Mediação e Arbitragem', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '313-1', 'Entidade Sindical', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '320-4', 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '321-2', 'Fundação ou Associação Domiciliada no Exterior', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '322-0', 'Organização Religiosa', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '323-9', 'Comunidade Indígena', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '324-7', 'Fundo Privado', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '325-5', 'Órgão de Direção Nacional de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '326-3', 'Órgão de Direção Regional de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '327-1', 'Órgão de Direção Local de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '328-0', 'Comitê Financeiro de Partido Político', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '329-8', 'Frente Plebiscitária ou Referendária', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '330-6', 'Organização Social (OS)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '331-0', 'Demais Condomínios', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3', '399-9', 'Associação Privada', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '401-4', 'Empresa Individual Imobiliária', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '402-2', 'Segurado Especial', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '408-1', 'Contribuinte individual', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '409-0', 'Candidato a Cargo Político Eletivo', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '411-1', 'Leiloeiro', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('4', '412-4', 'Produtor Rural (Pessoa Física)', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('5', '501-0', 'Organização Internacional', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('5', '502-9', 'Representação Diplomática Estrangeira', now(), 1, False);
INSERT INTO public.esocial_naturezas_juridicas (grupo, codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('5', '503-7', 'Outras Instituições Extraterritoriais', now(), 1, False);