DELETE FROM public.esocial_programas_planos_documentos;
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('201', 'Declaração das Instalações – NR2', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('501', 'Mapa de Riscos – NR5', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('701', 'Programa de Controle Médico de Saúde Ocupacional (PCMSO) – NR7', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('702', 'Relatório Anual do PCMSO – NR7', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('703', 'Kit Primeiros Socorros – NR7', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('704', 'Programa de Conservação Auditiva (PCA) – Anexo I, Quadro II, NR7', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('901', 'Programa de Prevenção de Riscos Ambientais (PPRA) – NR9', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('902', 'Análise Global do PPRA – NR9', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1001', 'Prontuário das Instalações Elétricas – NR10', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1002', 'Diagramas unifilares – NR10', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1003', 'Plano de Emergência – NR10', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1201', 'Inventário das máquinas e equipamentos – NR12', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1202', 'Plano de movimentação de carga (Plano de Rigging) – NR12', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1203', 'Plano de movimentação de pessoas – NR12', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1301', 'Plano de Ação (Vasos de pressão sem códigos de projeto) – NR13', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1302', 'Plano de Inspeção (Tubulações) – NR13', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1303', 'Plano de Manutenção (Tubulações de vapor de água e acessórios) – NR13', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1304', 'Programa de Inspeção (Tubulações) – NR13', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1501', 'Programa de Prevenção à Exposição Ocupacional ao Benzeno (PPEOB) – Anexo 13, NR15', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1701', 'Análise Ergonômica do Trabalho (AET) – NR17', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1702', 'Programa de vigilância epidemiológica – Anexo II, NR17', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1801', 'Plano de Emergência – NR18', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1802', 'Plano de cargas para Gruas – NR18', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1803', 'Programa de Condições e Meio Ambiente de Trabalho na Indústria da Construção (PCMAT) – NR18', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1804', 'Programa de Manutenção Preventiva (Equipamentos de movimentação e transporte de materiais e ou pessoas) – NR18', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1805', 'Programa de manutenção preventiva para PTA - Plataformas de Transporte Aéreo – NR18', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1901', 'Plano de Emergência e Combate a Incêndio e Explosão – Anexo I, NR19', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1902', 'Plano de manutenção preventiva de máquinas e equipamentos – Anexo I, NR19', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1903', 'Procedimentos operacionais para fabricação, armazenamento e manipulação de produtos ou misturas explosivas – Anexo I, NR19', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1904', 'Inventário geral dos riscos – Anexo I, NR19', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('1905', 'Inventário de produtos utilizados – Anexo I, NR19', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2001', 'Prontuário da Instalação – NR20', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2201', 'Programa de Gerenciamento de Riscos (PGR) – NR22', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2202', 'Programa de Proteção Respiratória (PPR) – NR22', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2901', 'Plano de Controle de Emergência (PCE) – NR29', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('2902', 'Plano de Ajuda Mútua (PAM) – NR29', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3001', 'Plano de Emergência – Anexo II, NR30', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3002', 'Livro de Primeiros Socorros – NR30', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3201', 'Programa de Controle de Animais Sinantrópicos – NR32', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3202', 'Plano de Proteção Radiológica (PPR) – NR32', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3401', 'Plano de auto resgate e resgate dos profissionais – NR34', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3402', 'Programa de Proteção Respiratória (PPR) – NR34', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3403', 'Plano de Proteção Radiológica (PPR) – NR34', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3501', 'Plano de Emergência – NR35', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3502', 'Plano de resgate – NR35', now(), 1, False);
INSERT INTO public.esocial_programas_planos_documentos (codigo, descricao, criado_em, criado_por_id, excluido) VALUES ('3601', 'Programa de Conservação Auditiva (PCA) – NR36', now(), 1, False);