# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r3010', '0012_auto_20190514_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r3010boletim',
            name='categevento',
            field=models.IntegerField(choices=[(1, '1 - Internacional'), (2, '2 - Interestadual'), (3, '3 - Estadual'), (4, '4 - Local.')], null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='cnpjmandante',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='moddesportiva',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='nomecompeticao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='nrboletim',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='pracadesportiva',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='qtdenaopagantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='qtdepagantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='tpcompeticao',
            field=models.IntegerField(choices=[(1, '1 - Oficial'), (2, '2 - N\xe3o Oficial.')], null=True),
        ),
        migrations.AlterField(
            model_name='r3010boletim',
            name='uf',
            field=models.CharField(choices=[(b'AC', 'Acre'), (b'AL', 'Alagoas'), (b'AM', 'Amazonas'), (b'AP', 'Amap\xe1'), (b'BA', 'Bahia'), (b'CE', 'Cear\xe1'), (b'DF', 'Distrito Federal'), (b'ES', 'Esp\xedrito Santo'), (b'GO', 'Goi\xe1s'), (b'MA', 'Maranh\xe3o'), (b'MG', 'Minas Gerais'), (b'MS', 'Mato Grosso do Sul'), (b'MT', 'Mato Grosso'), (b'PA', 'Par\xe1'), (b'PB', 'Para\xedba'), (b'PE', 'Pernambuco'), (b'PI', 'Piau\xed'), (b'PR', 'Paran\xe1'), (b'RJ', 'Rio de Janeiro'), (b'RN', 'Rio Grande do Norte'), (b'RO', 'Rond\xf4nia'), (b'RR', 'Roraima'), (b'RS', 'Rio Grande do Sul'), (b'SC', 'Santa Catarina'), (b'SE', 'Sergipe'), (b'SP', 'S\xe3o Paulo'), (b'TO', 'Tocantins')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='r3010infoproc',
            name='nrproc',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='r3010infoproc',
            name='tpproc',
            field=models.IntegerField(choices=[(1, '1 - Administrativo'), (2, '2 - Judicial.')], null=True),
        ),
        migrations.AlterField(
            model_name='r3010infoproc',
            name='vlrcpsusp',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r3010outrasreceitas',
            name='descreceita',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='r3010outrasreceitas',
            name='tpreceita',
            field=models.IntegerField(choices=[(1, '1 - Transmiss\xe3o'), (2, '2 - Propaganda'), (3, '3 - Publicidade'), (4, '4 - Sorteio'), (5, '5 - Outros.')], null=True),
        ),
        migrations.AlterField(
            model_name='r3010outrasreceitas',
            name='vlrreceita',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='descingr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='precoindiv',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='qtdeingrdev',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='qtdeingrvenda',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='qtdeingrvendidos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='tpingresso',
            field=models.IntegerField(choices=[(1, '1 - Arquibancada'), (2, '2 - Geral'), (3, '3 - Cadeiras'), (4, '4 - Camarote.')], null=True),
        ),
        migrations.AlterField(
            model_name='r3010receitaingressos',
            name='vlrtotal',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
