# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0005_auto_20181119_0958'),
        ('s2241', '0002_auto_20180912_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s2241aposentesp',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2241aposentesp',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2241aposentesp',
            name='s2241_evtinsapo',
        ),
        migrations.RemoveField(
            model_name='s2241insalperic',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2241insalperic',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2241insalperic',
            name='s2241_evtinsapo',
        ),
        migrations.AlterModelOptions(
            name='s2241altaposentesp',
            options={'managed': True, 'ordering': ['s2241_evtinsapo', 'dtaltcondicao']},
        ),
        migrations.AlterModelOptions(
            name='s2241altinsalperic',
            options={'managed': True, 'ordering': ['s2241_evtinsapo', 'dtaltcondicao']},
        ),
        migrations.AlterModelOptions(
            name='s2241fimaposentesp',
            options={'managed': True, 'ordering': ['s2241_evtinsapo', 'dtfimcondicao']},
        ),
        migrations.AlterModelOptions(
            name='s2241fiminsalperic',
            options={'managed': True, 'ordering': ['s2241_evtinsapo', 'dtfimcondicao']},
        ),
        migrations.AlterModelOptions(
            name='s2241iniaposentesp',
            options={'managed': True, 'ordering': ['s2241_evtinsapo', 'dtinicondicao']},
        ),
        migrations.AlterModelOptions(
            name='s2241iniinsalperic',
            options={'managed': True, 'ordering': ['s2241_evtinsapo', 'dtinicondicao']},
        ),
        migrations.RemoveField(
            model_name='s2241altaposentesp',
            name='s2241_aposentesp',
        ),
        migrations.RemoveField(
            model_name='s2241altinsalperic',
            name='s2241_insalperic',
        ),
        migrations.RemoveField(
            model_name='s2241fimaposentesp',
            name='s2241_aposentesp',
        ),
        migrations.RemoveField(
            model_name='s2241fiminsalperic',
            name='s2241_insalperic',
        ),
        migrations.RemoveField(
            model_name='s2241iniaposentesp',
            name='s2241_aposentesp',
        ),
        migrations.RemoveField(
            model_name='s2241iniinsalperic',
            name='s2241_insalperic',
        ),
        migrations.AddField(
            model_name='s2241altaposentesp',
            name='s2241_evtinsapo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241altaposentesp_s2241_evtinsapo', to='esocial.s2241evtInsApo'),
        ),
        migrations.AddField(
            model_name='s2241altinsalperic',
            name='s2241_evtinsapo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241altinsalperic_s2241_evtinsapo', to='esocial.s2241evtInsApo'),
        ),
        migrations.AddField(
            model_name='s2241fimaposentesp',
            name='s2241_evtinsapo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241fimaposentesp_s2241_evtinsapo', to='esocial.s2241evtInsApo'),
        ),
        migrations.AddField(
            model_name='s2241fiminsalperic',
            name='s2241_evtinsapo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241fiminsalperic_s2241_evtinsapo', to='esocial.s2241evtInsApo'),
        ),
        migrations.AddField(
            model_name='s2241iniaposentesp',
            name='s2241_evtinsapo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241iniaposentesp_s2241_evtinsapo', to='esocial.s2241evtInsApo'),
        ),
        migrations.AddField(
            model_name='s2241iniinsalperic',
            name='s2241_evtinsapo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241iniinsalperic_s2241_evtinsapo', to='esocial.s2241evtInsApo'),
        ),
        migrations.AlterField(
            model_name='s2241altaposentesp',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241altaposentesp',
            name='dtaltcondicao',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2241altaposentespfatrisco',
            name='codfatris',
            field=models.TextField(default=b'A', max_length=10),
        ),
        migrations.AlterField(
            model_name='s2241altaposentespfatrisco',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241altaposentespfatrisco',
            name='s2241_altaposentesp_infoamb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241altaposentespfatrisco_s2241_altaposentesp_infoamb', to='s2241.s2241altAposentEspinfoamb'),
        ),
        migrations.AlterField(
            model_name='s2241altaposentespinfoamb',
            name='codamb',
            field=models.CharField(default=b'A', max_length=30),
        ),
        migrations.AlterField(
            model_name='s2241altaposentespinfoamb',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241altaposentespinfoamb',
            name='s2241_altaposentesp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241altaposentespinfoamb_s2241_altaposentesp', to='s2241.s2241altAposentEsp'),
        ),
        migrations.AlterField(
            model_name='s2241altinsalperic',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241altinsalperic',
            name='dtaltcondicao',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2241altinsalpericfatrisco',
            name='codfatris',
            field=models.TextField(default=b'A', max_length=10),
        ),
        migrations.AlterField(
            model_name='s2241altinsalpericfatrisco',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241altinsalpericfatrisco',
            name='s2241_altinsalperic_infoamb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241altinsalpericfatrisco_s2241_altinsalperic_infoamb', to='s2241.s2241altInsalPericinfoamb'),
        ),
        migrations.AlterField(
            model_name='s2241altinsalpericinfoamb',
            name='codamb',
            field=models.CharField(default=b'A', max_length=30),
        ),
        migrations.AlterField(
            model_name='s2241altinsalpericinfoamb',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241altinsalpericinfoamb',
            name='s2241_altinsalperic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241altinsalpericinfoamb_s2241_altinsalperic', to='s2241.s2241altInsalPeric'),
        ),
        migrations.AlterField(
            model_name='s2241fimaposentesp',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241fimaposentesp',
            name='dtfimcondicao',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2241fimaposentespinfoamb',
            name='codamb',
            field=models.CharField(default=b'A', max_length=30),
        ),
        migrations.AlterField(
            model_name='s2241fimaposentespinfoamb',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241fimaposentespinfoamb',
            name='s2241_fimaposentesp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241fimaposentespinfoamb_s2241_fimaposentesp', to='s2241.s2241fimAposentEsp'),
        ),
        migrations.AlterField(
            model_name='s2241fiminsalperic',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241fiminsalperic',
            name='dtfimcondicao',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2241fiminsalpericinfoamb',
            name='codamb',
            field=models.CharField(default=b'A', max_length=30),
        ),
        migrations.AlterField(
            model_name='s2241fiminsalpericinfoamb',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241fiminsalpericinfoamb',
            name='s2241_fiminsalperic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241fiminsalpericinfoamb_s2241_fiminsalperic', to='s2241.s2241fimInsalPeric'),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentesp',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentesp',
            name='dtinicondicao',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentespfatrisco',
            name='codfatris',
            field=models.TextField(default=b'A', max_length=10),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentespfatrisco',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentespfatrisco',
            name='s2241_iniaposentesp_infoamb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241iniaposentespfatrisco_s2241_iniaposentesp_infoamb', to='s2241.s2241iniAposentEspinfoAmb'),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentespinfoamb',
            name='codamb',
            field=models.CharField(default=b'A', max_length=30),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentespinfoamb',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241iniaposentespinfoamb',
            name='s2241_iniaposentesp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241iniaposentespinfoamb_s2241_iniaposentesp', to='s2241.s2241iniAposentEsp'),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalperic',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalperic',
            name='dtinicondicao',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalpericfatrisco',
            name='codfatris',
            field=models.TextField(default=b'A', max_length=10),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalpericfatrisco',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalpericfatrisco',
            name='s2241_iniinsalperic_infoamb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241iniinsalpericfatrisco_s2241_iniinsalperic_infoamb', to='s2241.s2241iniInsalPericinfoAmb'),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalpericinfoamb',
            name='codamb',
            field=models.CharField(default=b'A', max_length=30),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalpericinfoamb',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2241iniinsalpericinfoamb',
            name='s2241_iniinsalperic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2241iniinsalpericinfoamb_s2241_iniinsalperic', to='s2241.s2241iniInsalPeric'),
        ),
        migrations.DeleteModel(
            name='s2241aposentEsp',
        ),
        migrations.DeleteModel(
            name='s2241insalPeric',
        ),
    ]
