# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3000', '0014_auto_20190531_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s3000idefolhapagto',
            options={'managed': True, 'ordering': ['s3000_evtexclusao', 'indapuracao', 'perapur'], 'permissions': (('can_see_list_s3000ideFolhaPagto', 'Pode ver listagem do modelo S3000IDEFOLHAPAGTO'), ('can_see_data_s3000ideFolhaPagto', 'Pode visualizar o conte\xfado do modelo S3000IDEFOLHAPAGTO'), ('can_see_menu_s3000ideFolhaPagto', 'Pode visualizar no menu o modelo S3000IDEFOLHAPAGTO'), ('can_print_list_s3000ideFolhaPagto', 'Pode imprimir listagem do modelo S3000IDEFOLHAPAGTO'), ('can_print_data_s3000ideFolhaPagto', 'Pode imprimir o conte\xfado do modelo S3000IDEFOLHAPAGTO'))},
        ),
        migrations.AlterModelOptions(
            name='s3000idetrabalhador',
            options={'managed': True, 'ordering': ['s3000_evtexclusao', 'cpftrab'], 'permissions': (('can_see_list_s3000ideTrabalhador', 'Pode ver listagem do modelo S3000IDETRABALHADOR'), ('can_see_data_s3000ideTrabalhador', 'Pode visualizar o conte\xfado do modelo S3000IDETRABALHADOR'), ('can_see_menu_s3000ideTrabalhador', 'Pode visualizar no menu o modelo S3000IDETRABALHADOR'), ('can_print_list_s3000ideTrabalhador', 'Pode imprimir listagem do modelo S3000IDETRABALHADOR'), ('can_print_data_s3000ideTrabalhador', 'Pode imprimir o conte\xfado do modelo S3000IDETRABALHADOR'))},
        ),
    ]
