# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1005', '0015_auto_20190525_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1005alteracao',
            options={'managed': True, 'ordering': ['s1005_evttabestab', 'tpinsc', 'nrinsc', 'inivalid', 'cnaeprep', 'aliqrat', 'regpt', 'contapr'], 'permissions': (('can_view_s1005alteracao', 'Can view S1005ALTERACAO'), ('can_view_menu_s1005alteracao', 'Can view menu S1005ALTERACAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaoinfocaepf',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'tpcaepf'], 'permissions': (('can_view_s1005alteracaoinfoCaepf', 'Can view S1005ALTERACAOINFOCAEPF'), ('can_view_menu_s1005alteracaoinfoCaepf', 'Can view menu S1005ALTERACAOINFOCAEPF'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaoinfoenteduc',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'nrinsc'], 'permissions': (('can_view_s1005alteracaoinfoEntEduc', 'Can view S1005ALTERACAOINFOENTEDUC'), ('can_view_menu_s1005alteracaoinfoEntEduc', 'Can view menu S1005ALTERACAOINFOENTEDUC'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaoinfoobra',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'indsubstpatrobra'], 'permissions': (('can_view_s1005alteracaoinfoObra', 'Can view S1005ALTERACAOINFOOBRA'), ('can_view_menu_s1005alteracaoinfoObra', 'Can view menu S1005ALTERACAOINFOOBRA'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaoinfopcd',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'contpcd'], 'permissions': (('can_view_s1005alteracaoinfoPCD', 'Can view S1005ALTERACAOINFOPCD'), ('can_view_menu_s1005alteracaoinfoPCD', 'Can view menu S1005ALTERACAOINFOPCD'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaonovavalidade',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'inivalid'], 'permissions': (('can_view_s1005alteracaonovaValidade', 'Can view S1005ALTERACAONOVAVALIDADE'), ('can_view_menu_s1005alteracaonovaValidade', 'Can view menu S1005ALTERACAONOVAVALIDADE'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaoprocadmjudfap',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'tpproc', 'nrproc', 'codsusp'], 'permissions': (('can_view_s1005alteracaoprocAdmJudFap', 'Can view S1005ALTERACAOPROCADMJUDFAP'), ('can_view_menu_s1005alteracaoprocAdmJudFap', 'Can view menu S1005ALTERACAOPROCADMJUDFAP'))},
        ),
        migrations.AlterModelOptions(
            name='s1005alteracaoprocadmjudrat',
            options={'managed': True, 'ordering': ['s1005_alteracao', 'tpproc', 'nrproc', 'codsusp'], 'permissions': (('can_view_s1005alteracaoprocAdmJudRat', 'Can view S1005ALTERACAOPROCADMJUDRAT'), ('can_view_menu_s1005alteracaoprocAdmJudRat', 'Can view menu S1005ALTERACAOPROCADMJUDRAT'))},
        ),
        migrations.AlterModelOptions(
            name='s1005exclusao',
            options={'managed': True, 'ordering': ['s1005_evttabestab', 'tpinsc', 'nrinsc', 'inivalid'], 'permissions': (('can_view_s1005exclusao', 'Can view S1005EXCLUSAO'), ('can_view_menu_s1005exclusao', 'Can view menu S1005EXCLUSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusao',
            options={'managed': True, 'ordering': ['s1005_evttabestab', 'tpinsc', 'nrinsc', 'inivalid', 'cnaeprep', 'aliqrat', 'regpt', 'contapr'], 'permissions': (('can_view_s1005inclusao', 'Can view S1005INCLUSAO'), ('can_view_menu_s1005inclusao', 'Can view menu S1005INCLUSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusaoinfocaepf',
            options={'managed': True, 'ordering': ['s1005_inclusao', 'tpcaepf'], 'permissions': (('can_view_s1005inclusaoinfoCaepf', 'Can view S1005INCLUSAOINFOCAEPF'), ('can_view_menu_s1005inclusaoinfoCaepf', 'Can view menu S1005INCLUSAOINFOCAEPF'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusaoinfoenteduc',
            options={'managed': True, 'ordering': ['s1005_inclusao', 'nrinsc'], 'permissions': (('can_view_s1005inclusaoinfoEntEduc', 'Can view S1005INCLUSAOINFOENTEDUC'), ('can_view_menu_s1005inclusaoinfoEntEduc', 'Can view menu S1005INCLUSAOINFOENTEDUC'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusaoinfoobra',
            options={'managed': True, 'ordering': ['s1005_inclusao', 'indsubstpatrobra'], 'permissions': (('can_view_s1005inclusaoinfoObra', 'Can view S1005INCLUSAOINFOOBRA'), ('can_view_menu_s1005inclusaoinfoObra', 'Can view menu S1005INCLUSAOINFOOBRA'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusaoinfopcd',
            options={'managed': True, 'ordering': ['s1005_inclusao', 'contpcd'], 'permissions': (('can_view_s1005inclusaoinfoPCD', 'Can view S1005INCLUSAOINFOPCD'), ('can_view_menu_s1005inclusaoinfoPCD', 'Can view menu S1005INCLUSAOINFOPCD'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusaoprocadmjudfap',
            options={'managed': True, 'ordering': ['s1005_inclusao', 'tpproc', 'nrproc', 'codsusp'], 'permissions': (('can_view_s1005inclusaoprocAdmJudFap', 'Can view S1005INCLUSAOPROCADMJUDFAP'), ('can_view_menu_s1005inclusaoprocAdmJudFap', 'Can view menu S1005INCLUSAOPROCADMJUDFAP'))},
        ),
        migrations.AlterModelOptions(
            name='s1005inclusaoprocadmjudrat',
            options={'managed': True, 'ordering': ['s1005_inclusao', 'tpproc', 'nrproc', 'codsusp'], 'permissions': (('can_view_s1005inclusaoprocAdmJudRat', 'Can view S1005INCLUSAOPROCADMJUDRAT'), ('can_view_menu_s1005inclusaoprocAdmJudRat', 'Can view menu S1005INCLUSAOPROCADMJUDRAT'))},
        ),
    ]
