# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0001_initial'),
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1000alteracao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('nmrazao', models.CharField(max_length=100)),
                ('classtrib', models.CharField(max_length=2, choices=[(b'01', '01 - Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria substitu\xedda'), (b'02', '02 - Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria n\xe3o substitu\xedda'), (b'03', '03 - Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria substitu\xedda e n\xe3o substitu\xedda'), (b'04', '04 - MEI - Micro Empreendedor Individual'), (b'06', '06 - Agroind\xfastria'), (b'07', '07 - Produtor Rural Pessoa Jur\xeddica'), (b'08', '08 - Cons\xf3rcio Simplificado de Produtores Rurais'), (b'09', '09 - \xd3rg\xe3o Gestor de M\xe3o de Obra'), (b'10', '10 - Entidade Sindical a que se refere a Lei 12.023/2009'), (b'11', '11 - Associa\xe7\xe3o Desportiva que mant\xe9m Clube de Futebol Profissional'), (b'13', '13 - Banco, caixa econ\xf4mica, sociedade de cr\xe9dito, financiamento e investimento e demais empresas relacionadas no par\xe1grafo 1\xba do art. 22 da Lei 8.212./91'), (b'14', '14 - Sindicatos em geral, exceto aquele classificado no c\xf3digo [10]'), (b'21', '21 - Pessoa F\xedsica, exceto Segurado Especial'), (b'22', '22 - Segurado Especial'), (b'60', '60 - Miss\xe3o Diplom\xe1tica ou Reparti\xe7\xe3o Consular de carreira estrangeira'), (b'70', '70 - Empresa de que trata o Decreto 5.436/2005'), (b'80', '80 - Entidade Beneficente de Assist\xeancia Social isenta de contribui\xe7\xf5es sociais'), (b'85', '85 - Ente Federativo, \xd3rg\xe3os da Uni\xe3o, Autarquias e Funda\xe7\xf5es P\xfablicas'), (b'99', '99 - Pessoas Jur\xeddicas em Geral')])),
                ('natjurid', models.CharField(blank=True, max_length=4, null=True, choices=[(b'1015', '1015 - \xd3rg\xe3o P\xfablico do Poder Executivo Federal'), (b'1023', '1023 - \xd3rg\xe3o P\xfablico do Poder Executivo Estadual ou do Distrito Federal'), (b'1031', '1031 - \xd3rg\xe3o P\xfablico do Poder Executivo Municipal'), (b'1040', '1040 - \xd3rg\xe3o P\xfablico do Poder Legislativo Federal'), (b'1058', '1058 - \xd3rg\xe3o P\xfablico do Poder Legislativo Estadual ou do Distrito Federal'), (b'1066', '1066 - \xd3rg\xe3o P\xfablico do Poder Legislativo Municipal'), (b'1074', '1074 - \xd3rg\xe3o P\xfablico do Poder Judici\xe1rio Federal'), (b'1082', '1082 - \xd3rg\xe3o P\xfablico do Poder Judici\xe1rio Estadual'), (b'1104', '1104 - Autarquia Federal'), (b'1112', '1112 - Autarquia Estadual ou do Distrito Federal'), (b'1120', '1120 - Autarquia Municipal'), (b'1139', '1139 - Funda\xe7\xe3o P\xfablica de Direito P\xfablico Federal'), (b'1147', '1147 - Funda\xe7\xe3o P\xfablica de Direito P\xfablico Estadual ou do Distrito Federal'), (b'1155', '1155 - Funda\xe7\xe3o P\xfablica de Direito P\xfablico Municipal'), (b'1163', '1163 - \xd3rg\xe3o P\xfablico Aut\xf4nomo Federal'), (b'1171', '1171 - \xd3rg\xe3o P\xfablico Aut\xf4nomo Estadual ou do Distrito Federal'), (b'1180', '1180 - \xd3rg\xe3o P\xfablico Aut\xf4nomo Municipal'), (b'1198', '1198 - Comiss\xe3o Polinacional'), (b'1201', '1201 - Fundo P\xfablico'), (b'1210', '1210 - Cons\xf3rcio P\xfablico de Direito P\xfablico (Associa\xe7\xe3o P\xfablica)'), (b'1228', '1228 - Cons\xf3rcio P\xfablico de Direito Privado'), (b'1236', '1236 - Estado ou Distrito Federal'), (b'1244', '1244 - Munic\xedpio'), (b'1252', '1252 - Funda\xe7\xe3o P\xfablica de Direito Privado Federal'), (b'1260', '1260 - Funda\xe7\xe3o P\xfablica de Direito Privado Estadual ou do Distrito Federal'), (b'1279', '1279 - Funda\xe7\xe3o P\xfablica de Direito Privado Municipal'), (b'2011', '2011 - Empresa P\xfablica'), (b'2038', '2038 - Sociedade de Economia Mista'), (b'2046', '2046 - Sociedade An\xf4nima Aberta'), (b'2054', '2054 - Sociedade An\xf4nima Fechada'), (b'2062', '2062 - Sociedade Empres\xe1ria Limitada'), (b'2070', '2070 - Sociedade Empres\xe1ria em Nome Coletivo'), (b'2089', '2089 - Sociedade Empres\xe1ria em Comandita Simples'), (b'2097', '2097 - Sociedade Empres\xe1ria em Comandita por A\xe7\xf5es'), (b'2127', '2127 - Sociedade em Conta de Participa\xe7\xe3o'), (b'2135', '2135 - Empres\xe1rio (Individual)'), (b'2143', '2143 - Cooperativa'), (b'2151', '2151 - Cons\xf3rcio de Sociedades'), (b'2160', '2160 - Grupo de Sociedades'), (b'2178', '2178 - Estabelecimento, no Brasil, de Sociedade Estrangeira'), (b'2194', '2194 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira'), (b'2216', '2216 - Empresa Domiciliada no Exterior'), (b'2224', '2224 - Clube/Fundo de Investimento'), (b'2232', '2232 - Sociedade Simples Pura'), (b'2240', '2240 - Sociedade Simples Limitada'), (b'2259', '2259 - Sociedade Simples em Nome Coletivo'), (b'2267', '2267 - Sociedade Simples em Comandita Simples'), (b'2275', '2275 - Empresa Binacional'), (b'2283', '2283 - Cons\xf3rcio de Empregadores'), (b'2291', '2291 - Cons\xf3rcio Simples'), (b'2305', '2305 - Empresa Individual de Responsabilidade Limitada (de Natureza Empres\xe1ria)'), (b'2313', '2313 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)'), (b'2321', '2321 - Sociedade Unipessoal de Advogados'), (b'2330', '2330 - Cooperativas de Consumo'), (b'3034', '3034 - Servi\xe7o Notarial e Registral (Cart\xf3rio)'), (b'3069', '3069 - Funda\xe7\xe3o Privada'), (b'3077', '3077 - Servi\xe7o Social Aut\xf4nomo'), (b'3085', '3085 - Condom\xednio Edil\xedcio'), (b'3107', '3107 - Comiss\xe3o de Concilia\xe7\xe3o Pr\xe9via'), (b'3115', '3115 - Entidade de Media\xe7\xe3o e Arbitragem'), (b'3131', '3131 - Entidade Sindical'), (b'3204', '3204 - Estabelecimento, no Brasil, de Funda\xe7\xe3o ou Associa\xe7\xe3o Estrangeiras'), (b'3212', '3212 - Funda\xe7\xe3o ou Associa\xe7\xe3o Domiciliada no Exterior'), (b'3220', '3220 - Organiza\xe7\xe3o Religiosa'), (b'3239', '3239 - Comunidade Ind\xedgena'), (b'3247', '3247 - Fundo Privado'), (b'3255', '3255 - \xd3rg\xe3o de Dire\xe7\xe3o Nacional de Partido Pol\xedtico'), (b'3263', '3263 - \xd3rg\xe3o de Dire\xe7\xe3o Regional de Partido Pol\xedtico'), (b'3271', '3271 - \xd3rg\xe3o de Dire\xe7\xe3o Local de Partido Pol\xedtico'), (b'3280', '3280 - Comit\xea Financeiro de Partido Pol\xedtico'), (b'3298', '3298 - Frente Plebiscit\xe1ria ou Referend\xe1ria'), (b'3306', '3306 - Organiza\xe7\xe3o Social (OS)'), (b'3310', '3310 - Demais Condom\xednios'), (b'3999', '3999 - Associa\xe7\xe3o Privada'), (b'4014', '4014 - Empresa Individual Imobili\xe1ria'), (b'4022', '4022 - Segurado Especial'), (b'4081', '4081 - Contribuinte individual'), (b'4090', '4090 - Candidato a Cargo Pol\xedtico Eletivo'), (b'4111', '4111 - Leiloeiro'), (b'4124', '4124 - Produtor Rural (Pessoa F\xedsica)'), (b'5010', '5010 - Organiza\xe7\xe3o Internacional'), (b'5029', '5029 - Representa\xe7\xe3o Diplom\xe1tica Estrangeira'), (b'5037', '5037 - Outras Institui\xe7\xf5es Extraterritoriais')])),
                ('indcoop', models.IntegerField(blank=True, null=True, choices=[(0, '0 - N\xe3o \xe9 cooperativa'), (1, '1 - Cooperativa de Trabalho'), (2, '2 - Cooperativa de Produ\xe7\xe3o'), (3, '3 - Outras Cooperativas')])),
                ('indconstr', models.IntegerField(blank=True, null=True, choices=[(0, '0 - N\xe3o \xe9 Construtora'), (1, '1 - Empresa Construtora')])),
                ('inddesfolha', models.IntegerField(choices=[(0, '0 - N\xe3o Aplic\xe1vel'), (1, '1 - Empresa enquadrada nos art. 7\xba a 9\xba da Lei 12.546/2011')])),
                ('indoptregeletron', models.IntegerField(choices=[(0, '0 - N\xe3o optou pelo registro eletr\xf4nico de empregados'), (1, '1 - Optou pelo registro eletr\xf4nico de empregados')])),
                ('indented', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('indett', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o \xe9 Empresa de Trabalho Tempor\xe1rio'), (b'S', 'S - Empresa de Trabalho Tempor\xe1rio')])),
                ('nrregett', models.CharField(max_length=30, null=True, blank=True)),
                ('nmctt', models.CharField(max_length=70)),
                ('cpfctt', models.CharField(max_length=11)),
                ('fonefixo', models.CharField(max_length=13, null=True, blank=True)),
                ('fonecel', models.CharField(max_length=13, null=True, blank=True)),
                ('email', models.CharField(max_length=60, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_evtinfoempregador', models.OneToOneField(related_name='s1000alteracao_s1000_evtinfoempregador', to='esocial.s1000evtInfoEmpregador')),
            ],
            options={
                'ordering': ['s1000_evtinfoempregador', 'inivalid', 'fimvalid', 'nmrazao', 'classtrib', 'natjurid', 'indcoop', 'indconstr', 'inddesfolha', 'indoptregeletron', 'indented', 'indett', 'nrregett', 'nmctt', 'cpfctt', 'fonefixo', 'fonecel', 'email'],
                'db_table': 's1000_alteracao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaodadosIsencao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ideminlei', models.CharField(max_length=70)),
                ('nrcertif', models.CharField(max_length=40)),
                ('dtemiscertif', models.DateField()),
                ('dtvenccertif', models.DateField()),
                ('nrprotrenov', models.CharField(max_length=40, null=True, blank=True)),
                ('dtprotrenov', models.DateField(null=True, blank=True)),
                ('dtdou', models.DateField(null=True, blank=True)),
                ('pagdou', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaodadosisencao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaodadosisencao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.OneToOneField(related_name='s1000alteracaodadosisencao_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'ideminlei', 'nrcertif', 'dtemiscertif', 'dtvenccertif', 'nrprotrenov', 'dtprotrenov', 'dtdou', 'pagdou'],
                'db_table': 's1000_alteracao_dadosisencao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaoinfoEFR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ideefr', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o \xe9 EFR'), (b'S', 'S - \xc9 EFR')])),
                ('cnpjefr', models.CharField(max_length=14, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaoinfoefr_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaoinfoefr_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['s1000_alteracao_infoop', 'ideefr', 'cnpjefr'],
                'db_table': 's1000_alteracao_infoefr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaoinfoEnte',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nmente', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, choices=[(b'AC', 'Acre'), (b'AL', 'Alagoas'), (b'AM', 'Amazonas'), (b'AP', 'Amap\xe1'), (b'BA', 'Bahia'), (b'CE', 'Cear\xe1'), (b'DF', 'Distrito Federal'), (b'ES', 'Esp\xedrito Santo'), (b'GO', 'Goi\xe1s'), (b'MA', 'Maranh\xe3o'), (b'MG', 'Minas Gerais'), (b'MS', 'Mato Grosso do Sul'), (b'MT', 'Mato Grosso'), (b'PA', 'Par\xe1'), (b'PB', 'Para\xedba'), (b'PE', 'Pernambuco'), (b'PI', 'Piau\xed'), (b'PR', 'Paran\xe1'), (b'RJ', 'Rio de Janeiro'), (b'RN', 'Rio Grande do Norte'), (b'RO', 'Rond\xf4nia'), (b'RR', 'Roraima'), (b'RS', 'Rio Grande do Sul'), (b'SC', 'Santa Catarina'), (b'SE', 'Sergipe'), (b'SP', 'S\xe3o Paulo'), (b'TO', 'Tocantins')])),
                ('codmunic', models.TextField(max_length=7, null=True, blank=True)),
                ('indrpps', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('subteto', models.IntegerField(choices=[(1, '1 - Executivo'), (2, '2 - Judici\xe1rio'), (3, '3 - Legislativo'), (9, '9 - Todos os poderes')])),
                ('vrsubteto', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaoinfoente_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaoinfoente_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['s1000_alteracao_infoop', 'nmente', 'uf', 'codmunic', 'indrpps', 'subteto', 'vrsubteto'],
                'db_table': 's1000_alteracao_infoente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaoinfoOP',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nrsiafi', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaoinfoop_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaoinfoop_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.OneToOneField(related_name='s1000alteracaoinfoop_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'nrsiafi'],
                'db_table': 's1000_alteracao_infoop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaoinfoOrgInternacional',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indacordoisenmulta', models.IntegerField(choices=[(0, '0 - Sem acordo'), (1, '1 - Com acordo')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaoinfoorginternacional_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaoinfoorginternacional_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.OneToOneField(related_name='s1000alteracaoinfoorginternacional_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'indacordoisenmulta'],
                'db_table': 's1000_alteracao_infoorginternacional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaonovaValidade',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaonovavalidade_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaonovavalidade_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.OneToOneField(related_name='s1000alteracaonovavalidade_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'inivalid', 'fimvalid'],
                'db_table': 's1000_alteracao_novavalidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaosituacaoPF',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indsitpf', models.IntegerField(choices=[(0, '0 - Situa\xe7\xe3o Normal'), (1, '1 - Encerramento de esp\xf3lio'), (2, '2 - Sa\xedda do pa\xeds em car\xe1ter permanente')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaosituacaopf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaosituacaopf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.OneToOneField(related_name='s1000alteracaosituacaopf_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'indsitpf'],
                'db_table': 's1000_alteracao_situacaopf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaosituacaoPJ',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indsitpj', models.IntegerField(choices=[(0, '0 - Situa\xe7\xe3o Normal'), (1, '1 - Extin\xe7\xe3o'), (2, '2 - Fus\xe3o'), (3, '3 - Cis\xe3o'), (4, '4 - Incorpora\xe7\xe3o')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaosituacaopj_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaosituacaopj_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.OneToOneField(related_name='s1000alteracaosituacaopj_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'indsitpj'],
                'db_table': 's1000_alteracao_situacaopj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000alteracaosoftwareHouse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cnpjsofthouse', models.CharField(max_length=14)),
                ('nmrazao', models.CharField(max_length=100)),
                ('nmcont', models.CharField(max_length=70)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=60, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000alteracaosoftwarehouse_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000alteracaosoftwarehouse_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_alteracao', models.ForeignKey(related_name='s1000alteracaosoftwarehouse_s1000_alteracao', to='s1000.s1000alteracao')),
            ],
            options={
                'ordering': ['s1000_alteracao', 'cnpjsofthouse', 'nmrazao', 'nmcont', 'telefone', 'email'],
                'db_table': 's1000_alteracao_softwarehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000exclusao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000exclusao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000exclusao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_evtinfoempregador', models.OneToOneField(related_name='s1000exclusao_s1000_evtinfoempregador', to='esocial.s1000evtInfoEmpregador')),
            ],
            options={
                'ordering': ['s1000_evtinfoempregador', 'inivalid', 'fimvalid'],
                'db_table': 's1000_exclusao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2017-01', 'Janeiro/2017'), (b'2017-02', 'Fevereiro/2017'), (b'2017-03', 'Mar\xe7o/2017'), (b'2017-04', 'Abril/2017'), (b'2017-05', 'Maio/2017'), (b'2017-06', 'Junho/2017'), (b'2017-07', 'Julho/2017'), (b'2017-08', 'Agosto/2017'), (b'2017-09', 'Setembro/2017'), (b'2017-10', 'Outubro/2017'), (b'2017-11', 'Novembro/2017'), (b'2017-12', 'Dezembro/2017'), (b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('nmrazao', models.CharField(max_length=100)),
                ('classtrib', models.CharField(max_length=2, choices=[(b'01', '01 - Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria substitu\xedda'), (b'02', '02 - Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria n\xe3o substitu\xedda'), (b'03', '03 - Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria substitu\xedda e n\xe3o substitu\xedda'), (b'04', '04 - MEI - Micro Empreendedor Individual'), (b'06', '06 - Agroind\xfastria'), (b'07', '07 - Produtor Rural Pessoa Jur\xeddica'), (b'08', '08 - Cons\xf3rcio Simplificado de Produtores Rurais'), (b'09', '09 - \xd3rg\xe3o Gestor de M\xe3o de Obra'), (b'10', '10 - Entidade Sindical a que se refere a Lei 12.023/2009'), (b'11', '11 - Associa\xe7\xe3o Desportiva que mant\xe9m Clube de Futebol Profissional'), (b'13', '13 - Banco, caixa econ\xf4mica, sociedade de cr\xe9dito, financiamento e investimento e demais empresas relacionadas no par\xe1grafo 1\xba do art. 22 da Lei 8.212./91'), (b'14', '14 - Sindicatos em geral, exceto aquele classificado no c\xf3digo [10]'), (b'21', '21 - Pessoa F\xedsica, exceto Segurado Especial'), (b'22', '22 - Segurado Especial'), (b'60', '60 - Miss\xe3o Diplom\xe1tica ou Reparti\xe7\xe3o Consular de carreira estrangeira'), (b'70', '70 - Empresa de que trata o Decreto 5.436/2005'), (b'80', '80 - Entidade Beneficente de Assist\xeancia Social isenta de contribui\xe7\xf5es sociais'), (b'85', '85 - Ente Federativo, \xd3rg\xe3os da Uni\xe3o, Autarquias e Funda\xe7\xf5es P\xfablicas'), (b'99', '99 - Pessoas Jur\xeddicas em Geral')])),
                ('natjurid', models.CharField(max_length=4, null=True, blank=True)),
                ('indcoop', models.IntegerField(blank=True, null=True, choices=[(0, '0 - N\xe3o \xe9 cooperativa'), (1, '1 - Cooperativa de Trabalho'), (2, '2 - Cooperativa de Produ\xe7\xe3o'), (3, '3 - Outras Cooperativas')])),
                ('indconstr', models.IntegerField(blank=True, null=True, choices=[(0, '0 - N\xe3o \xe9 Construtora'), (1, '1 - Empresa Construtora')])),
                ('inddesfolha', models.IntegerField(choices=[(0, '0 - N\xe3o Aplic\xe1vel'), (1, '1 - Empresa enquadrada nos art. 7\xba a 9\xba da Lei 12.546/2011')])),
                ('indoptregeletron', models.IntegerField(choices=[(0, '0 - N\xe3o optou pelo registro eletr\xf4nico de empregados'), (1, '1 - Optou pelo registro eletr\xf4nico de empregados')])),
                ('indented', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('indett', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o \xe9 Empresa de Trabalho Tempor\xe1rio'), (b'S', 'S - Empresa de Trabalho Tempor\xe1rio')])),
                ('nrregett', models.CharField(max_length=30, null=True, blank=True)),
                ('nmctt', models.CharField(max_length=70)),
                ('cpfctt', models.CharField(max_length=11)),
                ('fonefixo', models.CharField(max_length=13, null=True, blank=True)),
                ('fonecel', models.CharField(max_length=13, null=True, blank=True)),
                ('email', models.CharField(max_length=60, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_evtinfoempregador', models.OneToOneField(related_name='s1000inclusao_s1000_evtinfoempregador', to='esocial.s1000evtInfoEmpregador')),
            ],
            options={
                'ordering': ['s1000_evtinfoempregador', 'inivalid', 'fimvalid', 'nmrazao', 'classtrib', 'natjurid', 'indcoop', 'indconstr', 'inddesfolha', 'indoptregeletron', 'indented', 'indett', 'nrregett', 'nmctt', 'cpfctt', 'fonefixo', 'fonecel', 'email'],
                'db_table': 's1000_inclusao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaodadosIsencao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ideminlei', models.CharField(max_length=70)),
                ('nrcertif', models.CharField(max_length=40)),
                ('dtemiscertif', models.DateField()),
                ('dtvenccertif', models.DateField()),
                ('nrprotrenov', models.CharField(max_length=40, null=True, blank=True)),
                ('dtprotrenov', models.DateField(null=True, blank=True)),
                ('dtdou', models.DateField(null=True, blank=True)),
                ('pagdou', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaodadosisencao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaodadosisencao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_inclusao', models.OneToOneField(related_name='s1000inclusaodadosisencao_s1000_inclusao', to='s1000.s1000inclusao')),
            ],
            options={
                'ordering': ['s1000_inclusao', 'ideminlei', 'nrcertif', 'dtemiscertif', 'dtvenccertif', 'nrprotrenov', 'dtprotrenov', 'dtdou', 'pagdou'],
                'db_table': 's1000_inclusao_dadosisencao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaoinfoEFR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ideefr', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o \xe9 EFR'), (b'S', 'S - \xc9 EFR')])),
                ('cnpjefr', models.CharField(max_length=14, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaoinfoefr_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaoinfoefr_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['s1000_inclusao_infoop', 'ideefr', 'cnpjefr'],
                'db_table': 's1000_inclusao_infoefr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaoinfoEnte',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nmente', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, choices=[(b'AC', 'Acre'), (b'AL', 'Alagoas'), (b'AM', 'Amazonas'), (b'AP', 'Amap\xe1'), (b'BA', 'Bahia'), (b'CE', 'Cear\xe1'), (b'DF', 'Distrito Federal'), (b'ES', 'Esp\xedrito Santo'), (b'GO', 'Goi\xe1s'), (b'MA', 'Maranh\xe3o'), (b'MG', 'Minas Gerais'), (b'MS', 'Mato Grosso do Sul'), (b'MT', 'Mato Grosso'), (b'PA', 'Par\xe1'), (b'PB', 'Para\xedba'), (b'PE', 'Pernambuco'), (b'PI', 'Piau\xed'), (b'PR', 'Paran\xe1'), (b'RJ', 'Rio de Janeiro'), (b'RN', 'Rio Grande do Norte'), (b'RO', 'Rond\xf4nia'), (b'RR', 'Roraima'), (b'RS', 'Rio Grande do Sul'), (b'SC', 'Santa Catarina'), (b'SE', 'Sergipe'), (b'SP', 'S\xe3o Paulo'), (b'TO', 'Tocantins')])),
                ('codmunic', models.TextField(max_length=7, null=True, blank=True)),
                ('indrpps', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('subteto', models.IntegerField(choices=[(1, '1 - Executivo'), (2, '2 - Judici\xe1rio'), (3, '3 - Legislativo'), (9, '9 - Todos os poderes')])),
                ('vrsubteto', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaoinfoente_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaoinfoente_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['s1000_inclusao_infoop', 'nmente', 'uf', 'codmunic', 'indrpps', 'subteto', 'vrsubteto'],
                'db_table': 's1000_inclusao_infoente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaoinfoOP',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nrsiafi', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaoinfoop_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaoinfoop_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_inclusao', models.OneToOneField(related_name='s1000inclusaoinfoop_s1000_inclusao', to='s1000.s1000inclusao')),
            ],
            options={
                'ordering': ['s1000_inclusao', 'nrsiafi'],
                'db_table': 's1000_inclusao_infoop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaoinfoOrgInternacional',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indacordoisenmulta', models.IntegerField(choices=[(0, '0 - Sem acordo'), (1, '1 - Com acordo')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaoinfoorginternacional_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaoinfoorginternacional_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_inclusao', models.OneToOneField(related_name='s1000inclusaoinfoorginternacional_s1000_inclusao', to='s1000.s1000inclusao')),
            ],
            options={
                'ordering': ['s1000_inclusao', 'indacordoisenmulta'],
                'db_table': 's1000_inclusao_infoorginternacional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaosituacaoPF',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indsitpf', models.IntegerField(choices=[(0, '0 - Situa\xe7\xe3o Normal'), (1, '1 - Encerramento de esp\xf3lio'), (2, '2 - Sa\xedda do pa\xeds em car\xe1ter permanente')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaosituacaopf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaosituacaopf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_inclusao', models.OneToOneField(related_name='s1000inclusaosituacaopf_s1000_inclusao', to='s1000.s1000inclusao')),
            ],
            options={
                'ordering': ['s1000_inclusao', 'indsitpf'],
                'db_table': 's1000_inclusao_situacaopf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaosituacaoPJ',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indsitpj', models.IntegerField(choices=[(0, '0 - Situa\xe7\xe3o Normal'), (1, '1 - Extin\xe7\xe3o'), (2, '2 - Fus\xe3o'), (3, '3 - Cis\xe3o'), (4, '4 - Incorpora\xe7\xe3o')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaosituacaopj_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaosituacaopj_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_inclusao', models.OneToOneField(related_name='s1000inclusaosituacaopj_s1000_inclusao', to='s1000.s1000inclusao')),
            ],
            options={
                'ordering': ['s1000_inclusao', 'indsitpj'],
                'db_table': 's1000_inclusao_situacaopj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1000inclusaosoftwareHouse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cnpjsofthouse', models.CharField(max_length=14)),
                ('nmrazao', models.CharField(max_length=100)),
                ('nmcont', models.CharField(max_length=70)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=60, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1000inclusaosoftwarehouse_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1000inclusaosoftwarehouse_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1000_inclusao', models.ForeignKey(related_name='s1000inclusaosoftwarehouse_s1000_inclusao', to='s1000.s1000inclusao')),
            ],
            options={
                'ordering': ['s1000_inclusao', 'cnpjsofthouse', 'nmrazao', 'nmcont', 'telefone', 'email'],
                'db_table': 's1000_inclusao_softwarehouse',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='s1000inclusaoinfoente',
            name='s1000_inclusao_infoop',
            field=models.OneToOneField(related_name='s1000inclusaoinfoente_s1000_inclusao_infoop', to='s1000.s1000inclusaoinfoOP'),
        ),
        migrations.AddField(
            model_name='s1000inclusaoinfoefr',
            name='s1000_inclusao_infoop',
            field=models.OneToOneField(related_name='s1000inclusaoinfoefr_s1000_inclusao_infoop', to='s1000.s1000inclusaoinfoOP'),
        ),
        migrations.AddField(
            model_name='s1000alteracaoinfoente',
            name='s1000_alteracao_infoop',
            field=models.OneToOneField(related_name='s1000alteracaoinfoente_s1000_alteracao_infoop', to='s1000.s1000alteracaoinfoOP'),
        ),
        migrations.AddField(
            model_name='s1000alteracaoinfoefr',
            name='s1000_alteracao_infoop',
            field=models.OneToOneField(related_name='s1000alteracaoinfoefr_s1000_alteracao_infoop', to='s1000.s1000alteracaoinfoOP'),
        ),
    ]
