# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1000', '0007_auto_20190202_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1000alteracao',
            options={'managed': True, 'ordering': ['s1000_evtinfoempregador', 'inivalid', 'nmrazao', 'classtrib', 'inddesfolha', 'indoptregeletron', 'indett', 'nmctt', 'cpfctt'], 'permissions': (('can_view_s1000_alteracao', 'Can view s1000_alteracao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaodadosisencao',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'ideminlei', 'nrcertif', 'dtemiscertif', 'dtvenccertif'], 'permissions': (('can_view_s1000_alteracao_dadosisencao', 'Can view s1000_alteracao_dadosisencao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoefr',
            options={'managed': True, 'ordering': ['s1000_alteracao_infoop', 'ideefr', 'indrpps', 'prevcomp'], 'permissions': (('can_view_s1000_alteracao_infoefr', 'Can view s1000_alteracao_infoefr'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoente',
            options={'managed': True, 'ordering': ['s1000_alteracao_infoop', 'nmente', 'uf', 'indrpps', 'subteto', 'vrsubteto'], 'permissions': (('can_view_s1000_alteracao_infoente', 'Can view s1000_alteracao_infoente'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoop',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'nrsiafi', 'indugrpps', 'poderop', 'vrtetorem', 'ideefr'], 'permissions': (('can_view_s1000_alteracao_infoop', 'Can view s1000_alteracao_infoop'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoorginternacional',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'indacordoisenmulta'], 'permissions': (('can_view_s1000_alteracao_infoorginternacional', 'Can view s1000_alteracao_infoorginternacional'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaonovavalidade',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'inivalid'], 'permissions': (('can_view_s1000_alteracao_novavalidade', 'Can view s1000_alteracao_novavalidade'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaosituacaopf',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'indsitpf'], 'permissions': (('can_view_s1000_alteracao_situacaopf', 'Can view s1000_alteracao_situacaopf'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaosituacaopj',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'indsitpj'], 'permissions': (('can_view_s1000_alteracao_situacaopj', 'Can view s1000_alteracao_situacaopj'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaosoftwarehouse',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'cnpjsofthouse', 'nmrazao', 'nmcont', 'telefone'], 'permissions': (('can_view_s1000_alteracao_softwarehouse', 'Can view s1000_alteracao_softwarehouse'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000exclusao',
            options={'managed': True, 'ordering': ['s1000_evtinfoempregador', 'inivalid'], 'permissions': (('can_view_s1000_exclusao', 'Can view s1000_exclusao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusao',
            options={'managed': True, 'ordering': ['s1000_evtinfoempregador', 'inivalid', 'nmrazao', 'classtrib', 'inddesfolha', 'indoptregeletron', 'indett', 'nmctt', 'cpfctt'], 'permissions': (('can_view_s1000_inclusao', 'Can view s1000_inclusao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaodadosisencao',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'ideminlei', 'nrcertif', 'dtemiscertif', 'dtvenccertif'], 'permissions': (('can_view_s1000_inclusao_dadosisencao', 'Can view s1000_inclusao_dadosisencao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoefr',
            options={'managed': True, 'ordering': ['s1000_inclusao_infoop', 'ideefr', 'indrpps', 'prevcomp'], 'permissions': (('can_view_s1000_inclusao_infoefr', 'Can view s1000_inclusao_infoefr'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoente',
            options={'managed': True, 'ordering': ['s1000_inclusao_infoop', 'nmente', 'uf', 'indrpps', 'subteto', 'vrsubteto'], 'permissions': (('can_view_s1000_inclusao_infoente', 'Can view s1000_inclusao_infoente'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoop',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'nrsiafi', 'indugrpps', 'poderop', 'vrtetorem', 'ideefr'], 'permissions': (('can_view_s1000_inclusao_infoop', 'Can view s1000_inclusao_infoop'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoorginternacional',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'indacordoisenmulta'], 'permissions': (('can_view_s1000_inclusao_infoorginternacional', 'Can view s1000_inclusao_infoorginternacional'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaosituacaopf',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'indsitpf'], 'permissions': (('can_view_s1000_inclusao_situacaopf', 'Can view s1000_inclusao_situacaopf'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaosituacaopj',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'indsitpj'], 'permissions': (('can_view_s1000_inclusao_situacaopj', 'Can view s1000_inclusao_situacaopj'),)},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaosoftwarehouse',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'cnpjsofthouse', 'nmrazao', 'nmcont', 'telefone'], 'permissions': (('can_view_s1000_inclusao_softwarehouse', 'Can view s1000_inclusao_softwarehouse'),)},
        ),
    ]
