# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1065evtTabEquipamento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial.')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('operacao', models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')])),
            ],
            options={
                'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'],
                'db_table': 's1065_evttabequipamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2231evtCessao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpftrab', models.CharField(max_length=11)),
                ('nistrab', models.CharField(max_length=11)),
                ('matricula', models.CharField(max_length=30)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula'],
                'db_table': 's2231_evtcessao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2245evtTreiCap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpftrab', models.CharField(max_length=11)),
                ('nistrab', models.CharField(max_length=11, null=True, blank=True)),
                ('matricula', models.CharField(max_length=30, null=True, blank=True)),
                ('codcateg', models.TextField(max_length=3, null=True, blank=True)),
                ('codtreicap', models.CharField(max_length=4)),
                ('dttreicap', models.DateField()),
                ('durtreicap', models.DecimalField(max_length=6, max_digits=15, decimal_places=2)),
                ('modtreicap', models.IntegerField(choices=[(1, '1 - Presencial'), (2, '2 - Educa\xe7\xe3o a Dist\xe2ncia (EaD)'), (3, '3 - Mista')])),
                ('tptreicap', models.IntegerField(choices=[(1, '1 - Inicial'), (2, '2 - Peri\xf3dico'), (3, '3 - Reciclagem'), (4, '4 - Eventual'), (5, '5 - Outros')])),
                ('observacao', models.CharField(max_length=999, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('operacao', models.IntegerField(choices=[(1, 'Insalubridade/Periculosidade - Incluir'), (2, 'Insalubridade/Periculosidade - Alterar'), (3, 'Insalubridade/Periculosidade - Excluir'), (4, 'Aposentadoria Especial - Incluir'), (5, 'Aposentadoria Especial - Alterar'), (6, 'Aposentadoria Especial - Excluir')])),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'codcateg', 'codtreicap', 'dttreicap', 'durtreicap', 'modtreicap', 'tptreicap', 'observacao'],
                'db_table': 's2245_evttreicap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2400evtCdBenefIn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpfbenef', models.CharField(max_length=11)),
                ('nisbenef', models.CharField(max_length=11, null=True, blank=True)),
                ('nmbenefic', models.CharField(max_length=70)),
                ('dtinicio', models.DateField()),
                ('sexo', models.CharField(max_length=1, choices=[(b'F', 'F - Feminino'), (b'M', 'M - Masculino')])),
                ('racacor', models.IntegerField(choices=[(1, '1 - Branca'), (2, '2 - Preta'), (3, '3 - Parda'), (4, '4 - Amarela'), (5, '5 - Ind\xedgena'), (6, '6 - N\xe3o informado')])),
                ('estciv', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Solteiro'), (2, '2 - Casado'), (3, '3 - Divorciado'), (4, '4 - Separado'), (5, '5 - Vi\xfavo')])),
                ('incfismen', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'N', 'N - N\xe3o'), (b'S', 'S - Sim'), (b'S', 'S - Sim')])),
                ('dtincfismen', models.DateField(max_length=1, null=True, blank=True)),
                ('dtnascto', models.DateField()),
                ('codmunic', models.TextField(max_length=7, null=True, blank=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True, choices=[(b'AC', 'Acre'), (b'AL', 'Alagoas'), (b'AM', 'Amazonas'), (b'AP', 'Amap\xe1'), (b'BA', 'Bahia'), (b'CE', 'Cear\xe1'), (b'DF', 'Distrito Federal'), (b'ES', 'Esp\xedrito Santo'), (b'GO', 'Goi\xe1s'), (b'MA', 'Maranh\xe3o'), (b'MG', 'Minas Gerais'), (b'MS', 'Mato Grosso do Sul'), (b'MT', 'Mato Grosso'), (b'PA', 'Par\xe1'), (b'PB', 'Para\xedba'), (b'PE', 'Pernambuco'), (b'PI', 'Piau\xed'), (b'PR', 'Paran\xe1'), (b'RJ', 'Rio de Janeiro'), (b'RN', 'Rio Grande do Norte'), (b'RO', 'Rond\xf4nia'), (b'RR', 'Roraima'), (b'RS', 'Rio Grande do Sul'), (b'SC', 'Santa Catarina'), (b'SE', 'Sergipe'), (b'SP', 'S\xe3o Paulo'), (b'TO', 'Tocantins')])),
                ('paisnascto', models.TextField(max_length=3, null=True, blank=True)),
                ('paisnac', models.TextField(max_length=3)),
                ('nmmae', models.CharField(max_length=70, null=True, blank=True)),
                ('nmpai', models.CharField(max_length=70, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'nisbenef', 'nmbenefic', 'dtinicio', 'sexo', 'racacor', 'estciv', 'incfismen', 'dtincfismen', 'dtnascto', 'codmunic', 'uf', 'paisnascto', 'paisnac', 'nmmae', 'nmpai'],
                'db_table': 's2400_evtcdbenefin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2405evtCdBenefAlt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpfbenef', models.CharField(max_length=11)),
                ('dtalteracao', models.DateField()),
                ('nisbenef', models.CharField(max_length=11, null=True, blank=True)),
                ('nmbenefic', models.CharField(max_length=70)),
                ('sexo', models.CharField(max_length=1, choices=[(b'F', 'F - Feminino'), (b'M', 'M - Masculino')])),
                ('racacor', models.IntegerField(choices=[(1, '1 - Branca'), (2, '2 - Preta'), (3, '3 - Parda'), (4, '4 - Amarela'), (5, '5 - Ind\xedgena'), (6, '6 - N\xe3o informado')])),
                ('estciv', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Solteiro'), (2, '2 - Casado'), (3, '3 - Divorciado'), (4, '4 - Separado'), (5, '5 - Vi\xfavo')])),
                ('incfismen', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'N', 'N - N\xe3o'), (b'S', 'S - Sim'), (b'S', 'S - Sim')])),
                ('dtincfismen', models.DateField(max_length=1, null=True, blank=True)),
                ('paisnac', models.TextField(max_length=3)),
                ('nmmae', models.CharField(max_length=70, null=True, blank=True)),
                ('nmpai', models.CharField(max_length=70, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'dtalteracao', 'nisbenef', 'nmbenefic', 'sexo', 'racacor', 'estciv', 'incfismen', 'dtincfismen', 'paisnac', 'nmmae', 'nmpai'],
                'db_table': 's2405_evtcdbenefalt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2410evtCdBenIn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpfbenef', models.CharField(max_length=11)),
                ('matricula', models.CharField(max_length=30, null=True, blank=True)),
                ('cnpjorigem', models.CharField(max_length=14, null=True, blank=True)),
                ('cadini', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('nrbeneficio', models.CharField(max_length=20)),
                ('dtinibeneficio', models.DateField()),
                ('tpbeneficio', models.CharField(max_length=4)),
                ('vrbeneficio', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('tpplanrp', models.IntegerField(choices=[(0, '0 - Sem segrega\xe7\xe3o da massa'), (1, '1 - Fundo em capitaliza\xe7\xe3o'), (2, '2 - Fundo em reparti\xe7\xe3o'), (3, '3 - Mantido pelo Tesouro')])),
                ('dsc', models.CharField(max_length=255, null=True, blank=True)),
                ('inddecjud', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('indhomologtc', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'matricula', 'cnpjorigem', 'cadini', 'nrbeneficio', 'dtinibeneficio', 'tpbeneficio', 'vrbeneficio', 'tpplanrp', 'dsc', 'inddecjud', 'indhomologtc'],
                'db_table': 's2410_evtcdbenin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2416evtCdBenAlt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpfbenef', models.CharField(max_length=11)),
                ('nrbeneficio', models.CharField(max_length=20)),
                ('dtaltbeneficio', models.DateField()),
                ('tpbeneficio', models.CharField(max_length=4)),
                ('tpplanrp', models.IntegerField(choices=[(0, '0 - Sem segrega\xe7\xe3o da massa'), (1, '1 - Fundo em capitaliza\xe7\xe3o'), (2, '2 - Fundo em reparti\xe7\xe3o'), (3, '3 - Mantido pelo Tesouro')])),
                ('dsc', models.CharField(max_length=255, null=True, blank=True)),
                ('inddecjud', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('indhomologtc', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('indsuspensao', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('operacao', models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')])),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'nrbeneficio', 'dtaltbeneficio', 'tpbeneficio', 'tpplanrp', 'dsc', 'inddecjud', 'indhomologtc', 'indsuspensao'],
                'db_table': 's2416_evtcdbenalt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s2420evtCdBenTerm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v02_04_02', max_length=20, choices=[(b'v02_04_02', 'Vers\xe3o 2.04.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=40, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do empregador'), (2, '2 - Aplicativo governamental - Empregador Dom\xe9stico'), (3, '3 - Aplicativo governamental - Web Geral'), (4, '4 - Aplicativo governamental - Microempreendedor Individual (MEI)'), (5, '5 - Aplicativo governamental - Segurado Especial')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField()),
                ('nrinsc', models.CharField(max_length=15)),
                ('cpfbenef', models.CharField(max_length=11)),
                ('nrbeneficio', models.CharField(max_length=20)),
                ('dttermbeneficio', models.DateField()),
                ('mtvtermino', models.CharField(max_length=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('operacao', models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')])),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'nrbeneficio', 'dttermbeneficio', 'mtvtermino'],
                'db_table': 's2420_evtcdbenterm',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenprrp',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenprrp',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenprrp',
            name='retornos_eventos',
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenprrp',
            name='transmissor_lote_esocial',
        ),
        migrations.AlterModelOptions(
            name='s2200evtadmissao',
            options={'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'nmtrab', 'sexo', 'racacor', 'estciv', 'grauinstr', 'indpriempr', 'nmsoc', 'dtnascto', 'codmunic', 'uf', 'paisnascto', 'paisnac', 'nmmae', 'nmpai', 'matricula', 'tpregtrab', 'tpregprev', 'nrrecinfprelim', 'cadini', 'codcargo', 'dtingrcargo', 'codfuncao', 'codcateg', 'codcarreira', 'dtingrcarr', 'vrsalfx', 'undsalfixo', 'dscsalvar', 'tpcontr', 'dtterm', 'clauassec'], 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='s2210evtcat',
            options={'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpregistrador', 'tpinsc', 'nrinsc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'codcateg', 'dtacid', 'tpacid', 'hracid', 'hrstrabantesacid', 'tpcat', 'indcatobito', 'dtobito', 'indcomunpolicia', 'codsitgeradora', 'iniciatcat', 'observacao', 'tplocal', 'dsclocal', 'codamb', 'dsclograd', 'nrlograd', 'complemento', 'bairro', 'cep', 'codmunic', 'uf', 'cnpjlocalacid', 'pais', 'codpostal', 'tpinsc', 'nrinsc'], 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='s2220evtmonit',
            options={'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'codcateg', 'tpexame', 'dtaso', 'tpaso', 'resaso', 'cpfmed', 'nismed', 'nmmed', 'nrcrm', 'ufcrm', 'codcnes', 'frmctt', 'email', 'nmmed'], 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='s2240evtexprisco',
            options={'ordering': ['identidade', 'indretif', 'nrrecibo', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'codcateg'], 'managed': True},
        ),
        migrations.AddField(
            model_name='s2200evtadmissao',
            name='dtingrcargo',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='bairro',
            field=models.CharField(max_length=60, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='cep',
            field=models.CharField(max_length=8, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='codamb',
            field=models.CharField(max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='codcateg',
            field=models.TextField(max_length=3, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='complemento',
            field=models.CharField(max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='matricula',
            field=models.CharField(max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='codcateg',
            field=models.TextField(max_length=3, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='cpfmed',
            field=models.CharField(default=999, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='nismed',
            field=models.CharField(default=999, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='nrcrm',
            field=models.CharField(default=999, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='tpexame',
            field=models.IntegerField(default=1, choices=[(0, '0 - Exame m\xe9dico ocupacional'), (1, '1 - Exame toxicol\xf3gico do motorista profissional')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='ufcrm',
            field=models.CharField(default='CE', max_length=2, choices=[(b'AC', 'Acre'), (b'AL', 'Alagoas'), (b'AM', 'Amazonas'), (b'AP', 'Amap\xe1'), (b'BA', 'Bahia'), (b'CE', 'Cear\xe1'), (b'DF', 'Distrito Federal'), (b'ES', 'Esp\xedrito Santo'), (b'GO', 'Goi\xe1s'), (b'MA', 'Maranh\xe3o'), (b'MG', 'Minas Gerais'), (b'MS', 'Mato Grosso do Sul'), (b'MT', 'Mato Grosso'), (b'PA', 'Par\xe1'), (b'PB', 'Para\xedba'), (b'PE', 'Pernambuco'), (b'PI', 'Piau\xed'), (b'PR', 'Paran\xe1'), (b'RJ', 'Rio de Janeiro'), (b'RN', 'Rio Grande do Norte'), (b'RO', 'Rond\xf4nia'), (b'RR', 'Roraima'), (b'RS', 'Rio Grande do Sul'), (b'SC', 'Santa Catarina'), (b'SE', 'Sergipe'), (b'SP', 'S\xe3o Paulo'), (b'TO', 'Tocantins')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s2240evtexprisco',
            name='codcateg',
            field=models.TextField(max_length=3, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='s2200evtadmissao',
            name='codcateg',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2200evtadmissao',
            name='paisnac',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2200evtadmissao',
            name='paisnascto',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2205evtaltcadastral',
            name='paisnac',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2205evtaltcadastral',
            name='paisnascto',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2206evtaltcontratual',
            name='codcateg',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2210evtcat',
            name='pais',
            field=models.TextField(max_length=3, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='s2210evtcat',
            name='tpinsc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='s2230evtafasttemp',
            name='codcateg',
            field=models.TextField(max_length=3, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='s2300evttsvinicio',
            name='codcateg',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2300evttsvinicio',
            name='paisnac',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2300evttsvinicio',
            name='paisnascto',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2306evttsvaltcontr',
            name='codcateg',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='s2399evttsvtermino',
            name='codcateg',
            field=models.TextField(max_length=3),
        ),
    ]
