# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0016_auto_20190202_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1000evtinfoempregador',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1000_evtinfoempregador', 'Can view s1000_evtinfoempregador'),)},
        ),
        migrations.AlterModelOptions(
            name='s1005evttabestab',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1005_evttabestab', 'Can view s1005_evttabestab'),)},
        ),
        migrations.AlterModelOptions(
            name='s1010evttabrubrica',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1010_evttabrubrica', 'Can view s1010_evttabrubrica'),)},
        ),
        migrations.AlterModelOptions(
            name='s1020evttablotacao',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1020_evttablotacao', 'Can view s1020_evttablotacao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1030evttabcargo',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1030_evttabcargo', 'Can view s1030_evttabcargo'),)},
        ),
        migrations.AlterModelOptions(
            name='s1035evttabcarreira',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1035_evttabcarreira', 'Can view s1035_evttabcarreira'),)},
        ),
        migrations.AlterModelOptions(
            name='s1040evttabfuncao',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1040_evttabfuncao', 'Can view s1040_evttabfuncao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1050evttabhortur',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1050_evttabhortur', 'Can view s1050_evttabhortur'),)},
        ),
        migrations.AlterModelOptions(
            name='s1060evttabambiente',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1060_evttabambiente', 'Can view s1060_evttabambiente'),)},
        ),
        migrations.AlterModelOptions(
            name='s1070evttabprocesso',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1070_evttabprocesso', 'Can view s1070_evttabprocesso'),)},
        ),
        migrations.AlterModelOptions(
            name='s1080evttaboperport',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1080_evttaboperport', 'Can view s1080_evttaboperport'),)},
        ),
        migrations.AlterModelOptions(
            name='s1200evtremun',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s1200_evtremun', 'Can view s1200_evtremun'),)},
        ),
        migrations.AlterModelOptions(
            name='s1202evtrmnrpps',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s1202_evtrmnrpps', 'Can view s1202_evtrmnrpps'),)},
        ),
        migrations.AlterModelOptions(
            name='s1207evtbenprrp',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef'], 'permissions': (('can_view_s1207_evtbenprrp', 'Can view s1207_evtbenprrp'),)},
        ),
        migrations.AlterModelOptions(
            name='s1210evtpgtos',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef'], 'permissions': (('can_view_s1210_evtpgtos', 'Can view s1210_evtpgtos'),)},
        ),
        migrations.AlterModelOptions(
            name='s1250evtaqprod',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscadq', 'nrinscadq'], 'permissions': (('can_view_s1250_evtaqprod', 'Can view s1250_evtaqprod'),)},
        ),
        migrations.AlterModelOptions(
            name='s1260evtcomprod',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'nrinscestabrural'], 'permissions': (('can_view_s1260_evtcomprod', 'Can view s1260_evtcomprod'),)},
        ),
        migrations.AlterModelOptions(
            name='s1270evtcontratavnp',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1270_evtcontratavnp', 'Can view s1270_evtcontratavnp'),)},
        ),
        migrations.AlterModelOptions(
            name='s1280evtinfocomplper',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1280_evtinfocomplper', 'Can view s1280_evtinfocomplper'),)},
        ),
        migrations.AlterModelOptions(
            name='s1295evttotconting',
            options={'managed': True, 'ordering': ['identidade', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1295_evttotconting', 'Can view s1295_evttotconting'),)},
        ),
        migrations.AlterModelOptions(
            name='s1298evtreabreevper',
            options={'managed': True, 'ordering': ['identidade', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1298_evtreabreevper', 'Can view s1298_evtreabreevper'),)},
        ),
        migrations.AlterModelOptions(
            name='s1299evtfechaevper',
            options={'managed': True, 'ordering': ['identidade', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'evtremun', 'evtpgtos', 'evtaqprod', 'evtcomprod', 'evtcontratavnp', 'evtinfocomplper'], 'permissions': (('can_view_s1299_evtfechaevper', 'Can view s1299_evtfechaevper'),)},
        ),
        migrations.AlterModelOptions(
            name='s1300evtcontrsindpatr',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'indapuracao', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s1300_evtcontrsindpatr', 'Can view s1300_evtcontrsindpatr'),)},
        ),
        migrations.AlterModelOptions(
            name='s2190evtadmprelim',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'dtnascto', 'dtadm'], 'permissions': (('can_view_s2190_evtadmprelim', 'Can view s2190_evtadmprelim'),)},
        ),
        migrations.AlterModelOptions(
            name='s2200evtadmissao',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'nmtrab', 'sexo', 'racacor', 'grauinstr', 'dtnascto', 'paisnascto', 'paisnac', 'matricula', 'tpregtrab', 'tpregprev', 'cadini', 'codcateg', 'vrsalfx', 'undsalfixo', 'tpcontr'], 'permissions': (('can_view_s2200_evtadmissao', 'Can view s2200_evtadmissao'),)},
        ),
        migrations.AlterModelOptions(
            name='s2205evtaltcadastral',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'dtalteracao', 'nmtrab', 'sexo', 'racacor', 'grauinstr', 'dtnascto', 'paisnascto', 'paisnac'], 'permissions': (('can_view_s2205_evtaltcadastral', 'Can view s2205_evtaltcadastral'),)},
        ),
        migrations.AlterModelOptions(
            name='s2206evtaltcontratual',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'dtalteracao', 'tpregprev', 'codcateg', 'vrsalfx', 'undsalfixo', 'tpcontr'], 'permissions': (('can_view_s2206_evtaltcontratual', 'Can view s2206_evtaltcontratual'),)},
        ),
        migrations.AlterModelOptions(
            name='s2210evtcat',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'dtacid', 'tpacid', 'hrstrabantesacid', 'tpcat', 'indcatobito', 'indcomunpolicia', 'codsitgeradora', 'iniciatcat', 'tplocal', 'tplograd', 'dsclograd', 'nrlograd'], 'permissions': (('can_view_s2210_evtcat', 'Can view s2210_evtcat'),)},
        ),
        migrations.AlterModelOptions(
            name='s2220evtmonit',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'tpexameocup', 'dtaso', 'tpaso', 'resaso', 'nmmed', 'nrcrm', 'ufcrm', 'nisresp', 'nrconsclasse', 'nmresp', 'nrcrm', 'ufcrm'], 'permissions': (('can_view_s2220_evtmonit', 'Can view s2220_evtmonit'),)},
        ),
        migrations.AlterModelOptions(
            name='s2221evttoxic',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'dtexame', 'indrecusa'], 'permissions': (('can_view_s2221_evttoxic', 'Can view s2221_evttoxic'),)},
        ),
        migrations.AlterModelOptions(
            name='s2230evtafasttemp',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s2230_evtafasttemp', 'Can view s2230_evtafasttemp'),)},
        ),
        migrations.AlterModelOptions(
            name='s2231evtcessao',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula'], 'permissions': (('can_view_s2231_evtcessao', 'Can view s2231_evtcessao'),)},
        ),
        migrations.AlterModelOptions(
            name='s2240evtexprisco',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'dtinicondicao', 'dscativdes'], 'permissions': (('can_view_s2240_evtexprisco', 'Can view s2240_evtexprisco'),)},
        ),
        migrations.AlterModelOptions(
            name='s2241evtinsapo',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s2241_evtinsapo', 'Can view s2241_evtinsapo'),)},
        ),
        migrations.AlterModelOptions(
            name='s2245evttreicap',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'codtreicap'], 'permissions': (('can_view_s2245_evttreicap', 'Can view s2245_evttreicap'),)},
        ),
        migrations.AlterModelOptions(
            name='s2250evtavprevio',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula'], 'permissions': (('can_view_s2250_evtavprevio', 'Can view s2250_evtavprevio'),)},
        ),
        migrations.AlterModelOptions(
            name='s2260evtconvinterm',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'codconv', 'dtinicio', 'dtfim', 'dtprevpgto', 'indlocal'], 'permissions': (('can_view_s2260_evtconvinterm', 'Can view s2260_evtconvinterm'),)},
        ),
        migrations.AlterModelOptions(
            name='s2298evtreintegr',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'tpreint', 'dtefetretorno', 'dtefeito', 'indpagtojuizo'], 'permissions': (('can_view_s2298_evtreintegr', 'Can view s2298_evtreintegr'),)},
        ),
        migrations.AlterModelOptions(
            name='s2299evtdeslig',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nistrab', 'matricula', 'mtvdeslig', 'dtdeslig', 'indpagtoapi', 'pensalim', 'indcumprparc'], 'permissions': (('can_view_s2299_evtdeslig', 'Can view s2299_evtdeslig'),)},
        ),
        migrations.AlterModelOptions(
            name='s2300evttsvinicio',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'nmtrab', 'sexo', 'racacor', 'grauinstr', 'dtnascto', 'paisnascto', 'paisnac', 'cadini', 'codcateg', 'dtinicio'], 'permissions': (('can_view_s2300_evttsvinicio', 'Can view s2300_evttsvinicio'),)},
        ),
        migrations.AlterModelOptions(
            name='s2306evttsvaltcontr',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'codcateg', 'dtalteracao'], 'permissions': (('can_view_s2306_evttsvaltcontr', 'Can view s2306_evttsvaltcontr'),)},
        ),
        migrations.AlterModelOptions(
            name='s2399evttsvtermino',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpftrab', 'codcateg', 'dtterm'], 'permissions': (('can_view_s2399_evttsvtermino', 'Can view s2399_evttsvtermino'),)},
        ),
        migrations.AlterModelOptions(
            name='s2400evtcdbenefin',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'nmbenefic', 'dtinicio', 'sexo', 'racacor', 'incfismen', 'dtnascto', 'paisnac'], 'permissions': (('can_view_s2400_evtcdbenefin', 'Can view s2400_evtcdbenefin'),)},
        ),
        migrations.AlterModelOptions(
            name='s2405evtcdbenefalt',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'dtalteracao', 'nmbenefic', 'sexo', 'racacor', 'incfismen', 'paisnac'], 'permissions': (('can_view_s2405_evtcdbenefalt', 'Can view s2405_evtcdbenefalt'),)},
        ),
        migrations.AlterModelOptions(
            name='s2410evtcdbenin',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'cadini', 'nrbeneficio', 'dtinibeneficio', 'tpbeneficio', 'vrbeneficio', 'tpplanrp', 'inddecjud', 'indhomologtc'], 'permissions': (('can_view_s2410_evtcdbenin', 'Can view s2410_evtcdbenin'),)},
        ),
        migrations.AlterModelOptions(
            name='s2416evtcdbenalt',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'nrbeneficio', 'dtaltbeneficio', 'tpbeneficio', 'tpplanrp', 'inddecjud', 'indhomologtc', 'indsuspensao'], 'permissions': (('can_view_s2416_evtcdbenalt', 'Can view s2416_evtcdbenalt'),)},
        ),
        migrations.AlterModelOptions(
            name='s2420evtcdbenterm',
            options={'managed': True, 'ordering': ['identidade', 'indretif', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'cpfbenef', 'nrbeneficio', 'dttermbeneficio', 'mtvtermino'], 'permissions': (('can_view_s2420_evtcdbenterm', 'Can view s2420_evtcdbenterm'),)},
        ),
        migrations.AlterModelOptions(
            name='s3000evtexclusao',
            options={'managed': True, 'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpevento', 'nrrecevt'], 'permissions': (('can_view_s3000_evtexclusao', 'Can view s3000_evtexclusao'),)},
        ),
        migrations.AlterModelOptions(
            name='s5001evtbasestrab',
            options={'managed': True, 'ordering': ['identidade', 'nrrecarqbase', 'indapuracao', 'perapur', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s5001_evtbasestrab', 'Can view s5001_evtbasestrab'),)},
        ),
        migrations.AlterModelOptions(
            name='s5002evtirrfbenef',
            options={'managed': True, 'ordering': ['identidade', 'nrrecarqbase', 'perapur', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s5002_evtirrfbenef', 'Can view s5002_evtirrfbenef'),)},
        ),
        migrations.AlterModelOptions(
            name='s5003evtbasesfgts',
            options={'managed': True, 'ordering': ['identidade', 'nrrecarqbase', 'perapur', 'tpinsc', 'nrinsc', 'cpftrab'], 'permissions': (('can_view_s5003_evtbasesfgts', 'Can view s5003_evtbasesfgts'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011evtcs',
            options={'managed': True, 'ordering': ['identidade', 'indapuracao', 'perapur', 'tpinsc', 'nrinsc', 'nrrecarqbase', 'indexistinfo', 'classtrib'], 'permissions': (('can_view_s5011_evtcs', 'Can view s5011_evtcs'),)},
        ),
        migrations.AlterModelOptions(
            name='s5012evtirrf',
            options={'managed': True, 'ordering': ['identidade', 'perapur', 'tpinsc', 'nrinsc', 'nrrecarqbase', 'indexistinfo'], 'permissions': (('can_view_s5012_evtirrf', 'Can view s5012_evtirrf'),)},
        ),
        migrations.AlterModelOptions(
            name='s5013evtfgts',
            options={'managed': True, 'ordering': ['identidade', 'perapur', 'tpinsc', 'nrinsc', 'nrrecarqbase', 'indexistinfo'], 'permissions': (('can_view_s5013_evtfgts', 'Can view s5013_evtfgts'),)},
        ),
    ]
