# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2220', '0014_auto_20190514_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s2220exame',
            name='dtexm',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='s2220exame',
            name='dtinimonit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='s2220exame',
            name='interprexm',
            field=models.IntegerField(choices=[(1, '1 - EE'), (2, '2 - SC'), (3, '3 - SC+.')], null=True),
        ),
        migrations.AlterField(
            model_name='s2220exame',
            name='ordexame',
            field=models.IntegerField(choices=[(1, '1 - Inicial'), (2, '2 - Sequencial.')], null=True),
        ),
        migrations.AlterField(
            model_name='s2220exame',
            name='procrealizado',
            field=models.IntegerField(null=True),
        ),
    ]
