# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1050', '0014_auto_20190531_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1050alteracao',
            options={'managed': True, 'ordering': ['s1050_evttabhortur', 'codhorcontrat', 'inivalid', 'hrentr', 'hrsaida', 'durjornada', 'perhorflexivel'], 'permissions': (('can_see_list_s1050alteracao', 'Pode ver listagem do modelo S1050ALTERACAO'), ('can_see_data_s1050alteracao', 'Pode visualizar o conte\xfado do modelo S1050ALTERACAO'), ('can_see_menu_s1050alteracao', 'Pode visualizar no menu o modelo S1050ALTERACAO'), ('can_print_list_s1050alteracao', 'Pode imprimir listagem do modelo S1050ALTERACAO'), ('can_print_data_s1050alteracao', 'Pode imprimir o conte\xfado do modelo S1050ALTERACAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1050alteracaohorariointervalo',
            options={'managed': True, 'ordering': ['s1050_alteracao', 'tpinterv', 'durinterv'], 'permissions': (('can_see_list_s1050alteracaohorarioIntervalo', 'Pode ver listagem do modelo S1050ALTERACAOHORARIOINTERVALO'), ('can_see_data_s1050alteracaohorarioIntervalo', 'Pode visualizar o conte\xfado do modelo S1050ALTERACAOHORARIOINTERVALO'), ('can_see_menu_s1050alteracaohorarioIntervalo', 'Pode visualizar no menu o modelo S1050ALTERACAOHORARIOINTERVALO'), ('can_print_list_s1050alteracaohorarioIntervalo', 'Pode imprimir listagem do modelo S1050ALTERACAOHORARIOINTERVALO'), ('can_print_data_s1050alteracaohorarioIntervalo', 'Pode imprimir o conte\xfado do modelo S1050ALTERACAOHORARIOINTERVALO'))},
        ),
        migrations.AlterModelOptions(
            name='s1050alteracaonovavalidade',
            options={'managed': True, 'ordering': ['s1050_alteracao', 'inivalid'], 'permissions': (('can_see_list_s1050alteracaonovaValidade', 'Pode ver listagem do modelo S1050ALTERACAONOVAVALIDADE'), ('can_see_data_s1050alteracaonovaValidade', 'Pode visualizar o conte\xfado do modelo S1050ALTERACAONOVAVALIDADE'), ('can_see_menu_s1050alteracaonovaValidade', 'Pode visualizar no menu o modelo S1050ALTERACAONOVAVALIDADE'), ('can_print_list_s1050alteracaonovaValidade', 'Pode imprimir listagem do modelo S1050ALTERACAONOVAVALIDADE'), ('can_print_data_s1050alteracaonovaValidade', 'Pode imprimir o conte\xfado do modelo S1050ALTERACAONOVAVALIDADE'))},
        ),
        migrations.AlterModelOptions(
            name='s1050exclusao',
            options={'managed': True, 'ordering': ['s1050_evttabhortur', 'codhorcontrat', 'inivalid'], 'permissions': (('can_see_list_s1050exclusao', 'Pode ver listagem do modelo S1050EXCLUSAO'), ('can_see_data_s1050exclusao', 'Pode visualizar o conte\xfado do modelo S1050EXCLUSAO'), ('can_see_menu_s1050exclusao', 'Pode visualizar no menu o modelo S1050EXCLUSAO'), ('can_print_list_s1050exclusao', 'Pode imprimir listagem do modelo S1050EXCLUSAO'), ('can_print_data_s1050exclusao', 'Pode imprimir o conte\xfado do modelo S1050EXCLUSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1050inclusao',
            options={'managed': True, 'ordering': ['s1050_evttabhortur', 'codhorcontrat', 'inivalid', 'hrentr', 'hrsaida', 'durjornada', 'perhorflexivel'], 'permissions': (('can_see_list_s1050inclusao', 'Pode ver listagem do modelo S1050INCLUSAO'), ('can_see_data_s1050inclusao', 'Pode visualizar o conte\xfado do modelo S1050INCLUSAO'), ('can_see_menu_s1050inclusao', 'Pode visualizar no menu o modelo S1050INCLUSAO'), ('can_print_list_s1050inclusao', 'Pode imprimir listagem do modelo S1050INCLUSAO'), ('can_print_data_s1050inclusao', 'Pode imprimir o conte\xfado do modelo S1050INCLUSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1050inclusaohorariointervalo',
            options={'managed': True, 'ordering': ['s1050_inclusao', 'tpinterv', 'durinterv'], 'permissions': (('can_see_list_s1050inclusaohorarioIntervalo', 'Pode ver listagem do modelo S1050INCLUSAOHORARIOINTERVALO'), ('can_see_data_s1050inclusaohorarioIntervalo', 'Pode visualizar o conte\xfado do modelo S1050INCLUSAOHORARIOINTERVALO'), ('can_see_menu_s1050inclusaohorarioIntervalo', 'Pode visualizar no menu o modelo S1050INCLUSAOHORARIOINTERVALO'), ('can_print_list_s1050inclusaohorarioIntervalo', 'Pode imprimir listagem do modelo S1050INCLUSAOHORARIOINTERVALO'), ('can_print_data_s1050inclusaohorarioIntervalo', 'Pode imprimir o conte\xfado do modelo S1050INCLUSAOHORARIOINTERVALO'))},
        ),
    ]
