# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1040', '0006_auto_20190204_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s1040alteracao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1040alteracao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1040alteracaonovavalidade',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1040alteracaonovavalidade',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1040exclusao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1040exclusao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1040inclusao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1040inclusao',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='s1040alteracao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040alteracao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040alteracaonovavalidade',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040alteracaonovavalidade',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040exclusao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040exclusao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040inclusao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040inclusao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
