# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0001_initial'),
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1005alteracao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('cnaeprep', models.IntegerField()),
                ('aliqrat', models.IntegerField(choices=[(1, '1 - 1'), (2, '2 - 2'), (3, '3 - 3')])),
                ('fap', models.DecimalField(max_length=5, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('aliqratajust', models.DecimalField(max_length=5, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('regpt', models.IntegerField(choices=[(0, '0 - N\xe3o utiliza'), (1, '1 - Manual'), (2, '2 - Mec\xe2nico'), (3, '3 - Eletr\xf4nico (portaria MTE 1.510/2009)'), (4, '4 - N\xe3o eletr\xf4nico alternativo (art. 1\xb0 da Portaria MTE 373/2011)'), (5, '5 - Eletr\xf4nico alternativo ( art. 2\xb0 da Portaria MTE 373/2011)'), (6, '6 - Eletr\xf4nico - outros')])),
                ('contapr', models.IntegerField(choices=[(0, '0 - Dispensado de acordo com a lei'), (1, '1 - Dispensado, mesmo que parcialmente, em virtude de processo judicial'), (2, '2 - Obrigado')])),
                ('nrprocjud', models.CharField(max_length=20, null=True, blank=True)),
                ('contented', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_evttabestab', models.OneToOneField(related_name='s1005alteracao_s1005_evttabestab', to='esocial.s1005evtTabEstab')),
            ],
            options={
                'ordering': ['s1005_evttabestab', 'tpinsc', 'nrinsc', 'inivalid', 'fimvalid', 'cnaeprep', 'aliqrat', 'fap', 'aliqratajust', 'regpt', 'contapr', 'nrprocjud', 'contented'],
                'db_table': 's1005_alteracao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaoinfoCaepf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpcaepf', models.IntegerField(choices=[(1, '1 - Contribuinte Individual'), (2, '2 - Produtor Rural'), (3, '3 - Segurado Especial')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaoinfocaepf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaoinfocaepf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.OneToOneField(related_name='s1005alteracaoinfocaepf_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'tpcaepf'],
                'db_table': 's1005_alteracao_infocaepf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaoinfoEntEduc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nrinsc', models.CharField(max_length=15)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaoinfoenteduc_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaoinfoenteduc_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.ForeignKey(related_name='s1005alteracaoinfoenteduc_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'nrinsc'],
                'db_table': 's1005_alteracao_infoenteduc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaoinfoObra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indsubstpatrobra', models.IntegerField(choices=[(1, '1 - Contribui\xe7\xe3o Patronal Substitu\xedda'), (2, '2 - Contribui\xe7\xe3o Patronal N\xe3o Substitu\xedda')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaoinfoobra_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaoinfoobra_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.OneToOneField(related_name='s1005alteracaoinfoobra_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'indsubstpatrobra'],
                'db_table': 's1005_alteracao_infoobra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaoinfoPCD',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contpcd', models.IntegerField(choices=[(0, '0 - Dispensado de acordo com a lei'), (1, '1 - Dispensado, mesmo que parcialmente, em virtude de processo judicial'), (2, '2 - Com exigibilidade suspensa, mesmo que parcialmente em virtude de Termo de Compromisso firmado com o Minist\xe9rio do Trabalho'), (9, '9 - Obrigado')])),
                ('nrprocjud', models.CharField(max_length=20, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaoinfopcd_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaoinfopcd_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.OneToOneField(related_name='s1005alteracaoinfopcd_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'contpcd', 'nrprocjud'],
                'db_table': 's1005_alteracao_infopcd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaonovaValidade',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaonovavalidade_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaonovavalidade_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.OneToOneField(related_name='s1005alteracaonovavalidade_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'inivalid', 'fimvalid'],
                'db_table': 's1005_alteracao_novavalidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaoprocAdmJudFap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpproc', models.IntegerField(choices=[(1, '1 - Administrativo'), (1, '1 - Administrativo'), (2, '2 - Judicial'), (2, '2 - Judicial')])),
                ('nrproc', models.CharField(max_length=21)),
                ('codsusp', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaoprocadmjudfap_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaoprocadmjudfap_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.OneToOneField(related_name='s1005alteracaoprocadmjudfap_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'tpproc', 'nrproc', 'codsusp'],
                'db_table': 's1005_alteracao_procadmjudfap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005alteracaoprocAdmJudRat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpproc', models.IntegerField(choices=[(1, '1 - Administrativo'), (1, '1 - Administrativo'), (2, '2 - Judicial'), (2, '2 - Judicial')])),
                ('nrproc', models.CharField(max_length=21)),
                ('codsusp', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005alteracaoprocadmjudrat_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005alteracaoprocadmjudrat_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_alteracao', models.OneToOneField(related_name='s1005alteracaoprocadmjudrat_s1005_alteracao', to='s1005.s1005alteracao')),
            ],
            options={
                'ordering': ['s1005_alteracao', 'tpproc', 'nrproc', 'codsusp'],
                'db_table': 's1005_alteracao_procadmjudrat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005exclusao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005exclusao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005exclusao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_evttabestab', models.OneToOneField(related_name='s1005exclusao_s1005_evttabestab', to='esocial.s1005evtTabEstab')),
            ],
            options={
                'ordering': ['s1005_evttabestab', 'tpinsc', 'nrinsc', 'inivalid', 'fimvalid'],
                'db_table': 's1005_exclusao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('inivalid', models.CharField(max_length=7, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('fimvalid', models.CharField(blank=True, max_length=7, null=True, choices=[(b'2018-01', 'Janeiro/2018'), (b'2018-02', 'Fevereiro/2018'), (b'2018-03', 'Mar\xe7o/2018'), (b'2018-04', 'Abril/2018'), (b'2018-05', 'Maio/2018'), (b'2018-06', 'Junho/2018'), (b'2018-07', 'Julho/2018'), (b'2018-08', 'Agosto/2018'), (b'2018-09', 'Setembro/2018'), (b'2018-10', 'Outubro/2018'), (b'2018-11', 'Novembro/2018'), (b'2018-12', 'Dezembro/2018')])),
                ('cnaeprep', models.IntegerField()),
                ('aliqrat', models.IntegerField(choices=[(1, '1 - 1'), (2, '2 - 2'), (3, '3 - 3')])),
                ('fap', models.DecimalField(max_length=5, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('aliqratajust', models.DecimalField(max_length=5, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('regpt', models.IntegerField(choices=[(0, '0 - N\xe3o utiliza'), (1, '1 - Manual'), (2, '2 - Mec\xe2nico'), (3, '3 - Eletr\xf4nico (portaria MTE 1.510/2009)'), (4, '4 - N\xe3o eletr\xf4nico alternativo (art. 1\xb0 da Portaria MTE 373/2011)'), (5, '5 - Eletr\xf4nico alternativo ( art. 2\xb0 da Portaria MTE 373/2011)'), (6, '6 - Eletr\xf4nico - outros')])),
                ('contapr', models.IntegerField(choices=[(0, '0 - Dispensado de acordo com a lei'), (1, '1 - Dispensado, mesmo que parcialmente, em virtude de processo judicial'), (2, '2 - Obrigado')])),
                ('nrprocjud', models.CharField(max_length=20, null=True, blank=True)),
                ('contented', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_evttabestab', models.OneToOneField(related_name='s1005inclusao_s1005_evttabestab', to='esocial.s1005evtTabEstab')),
            ],
            options={
                'ordering': ['s1005_evttabestab', 'tpinsc', 'nrinsc', 'inivalid', 'fimvalid', 'cnaeprep', 'aliqrat', 'fap', 'aliqratajust', 'regpt', 'contapr', 'nrprocjud', 'contented'],
                'db_table': 's1005_inclusao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusaoinfoCaepf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpcaepf', models.IntegerField(choices=[(1, '1 - Contribuinte Individual'), (2, '2 - Produtor Rural'), (3, '3 - Segurado Especial')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusaoinfocaepf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusaoinfocaepf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_inclusao', models.OneToOneField(related_name='s1005inclusaoinfocaepf_s1005_inclusao', to='s1005.s1005inclusao')),
            ],
            options={
                'ordering': ['s1005_inclusao', 'tpcaepf'],
                'db_table': 's1005_inclusao_infocaepf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusaoinfoEntEduc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nrinsc', models.CharField(max_length=15)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusaoinfoenteduc_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusaoinfoenteduc_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_inclusao', models.ForeignKey(related_name='s1005inclusaoinfoenteduc_s1005_inclusao', to='s1005.s1005inclusao')),
            ],
            options={
                'ordering': ['s1005_inclusao', 'nrinsc'],
                'db_table': 's1005_inclusao_infoenteduc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusaoinfoObra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indsubstpatrobra', models.IntegerField(choices=[(1, '1 - Contribui\xe7\xe3o Patronal Substitu\xedda'), (2, '2 - Contribui\xe7\xe3o Patronal N\xe3o Substitu\xedda')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusaoinfoobra_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusaoinfoobra_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_inclusao', models.OneToOneField(related_name='s1005inclusaoinfoobra_s1005_inclusao', to='s1005.s1005inclusao')),
            ],
            options={
                'ordering': ['s1005_inclusao', 'indsubstpatrobra'],
                'db_table': 's1005_inclusao_infoobra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusaoinfoPCD',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contpcd', models.IntegerField(choices=[(0, '0 - Dispensado de acordo com a lei'), (1, '1 - Dispensado, mesmo que parcialmente, em virtude de processo judicial'), (2, '2 - Com exigibilidade suspensa, mesmo que parcialmente em virtude de Termo de Compromisso firmado com o Minist\xe9rio do Trabalho'), (9, '9 - Obrigado')])),
                ('nrprocjud', models.CharField(max_length=20, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusaoinfopcd_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusaoinfopcd_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_inclusao', models.OneToOneField(related_name='s1005inclusaoinfopcd_s1005_inclusao', to='s1005.s1005inclusao')),
            ],
            options={
                'ordering': ['s1005_inclusao', 'contpcd', 'nrprocjud'],
                'db_table': 's1005_inclusao_infopcd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusaoprocAdmJudFap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpproc', models.IntegerField(choices=[(1, '1 - Administrativo'), (1, '1 - Administrativo'), (2, '2 - Judicial'), (2, '2 - Judicial')])),
                ('nrproc', models.CharField(max_length=21)),
                ('codsusp', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusaoprocadmjudfap_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusaoprocadmjudfap_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_inclusao', models.OneToOneField(related_name='s1005inclusaoprocadmjudfap_s1005_inclusao', to='s1005.s1005inclusao')),
            ],
            options={
                'ordering': ['s1005_inclusao', 'tpproc', 'nrproc', 'codsusp'],
                'db_table': 's1005_inclusao_procadmjudfap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='s1005inclusaoprocAdmJudRat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpproc', models.IntegerField(choices=[(1, '1 - Administrativo'), (1, '1 - Administrativo'), (2, '2 - Judicial'), (2, '2 - Judicial')])),
                ('nrproc', models.CharField(max_length=21)),
                ('codsusp', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='s1005inclusaoprocadmjudrat_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='s1005inclusaoprocadmjudrat_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('s1005_inclusao', models.OneToOneField(related_name='s1005inclusaoprocadmjudrat_s1005_inclusao', to='s1005.s1005inclusao')),
            ],
            options={
                'ordering': ['s1005_inclusao', 'tpproc', 'nrproc', 'codsusp'],
                'db_table': 's1005_inclusao_procadmjudrat',
                'managed': True,
            },
        ),
    ]
