# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r2030', '0013_auto_20190525_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r2030infoproc',
            options={'managed': True, 'ordering': ['r2030_recursosrec', 'tpproc', 'nrproc', 'vlrnret'], 'permissions': (('can_view_r2030infoProc', 'Can view R2030INFOPROC'), ('can_view_menu_r2030infoProc', 'Can view menu R2030INFOPROC'))},
        ),
        migrations.AlterModelOptions(
            name='r2030inforecurso',
            options={'managed': True, 'ordering': ['r2030_recursosrec', 'tprepasse', 'descrecurso', 'vlrbruto', 'vlrretapur'], 'permissions': (('can_view_r2030infoRecurso', 'Can view R2030INFORECURSO'), ('can_view_menu_r2030infoRecurso', 'Can view menu R2030INFORECURSO'))},
        ),
        migrations.AlterModelOptions(
            name='r2030recursosrec',
            options={'managed': True, 'ordering': ['r2030_evtassocdesprec', 'cnpjorigrecurso', 'vlrtotalrec', 'vlrtotalret'], 'permissions': (('can_view_r2030recursosRec', 'Can view R2030RECURSOSREC'), ('can_view_menu_r2030recursosRec', 'Can view menu R2030RECURSOSREC'))},
        ),
    ]
