# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissorEventosEfdreinf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=36)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('tabela', models.CharField(max_length=50)),
                ('tabela_salvar', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
                ('tpinsc', models.CharField(max_length=1, choices=[(b'1', '1 - CNPJ'), (b'2', '2 - CPF'), (b'3', '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (b'4', '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('processamento_codigo_resposta', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('url_recibo', models.CharField(max_length=100, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'db_table': 'transmissor_eventos_efdreinf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissorEventosEsocial',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=36)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('tabela', models.CharField(max_length=50)),
                ('tabela_salvar', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
                ('tpinsc', models.CharField(max_length=1, choices=[(b'1', '1 - CNPJ'), (b'2', '2 - CPF'), (b'3', '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (b'4', '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15)),
                ('processamento_codigo_resposta', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('url_recibo', models.CharField(max_length=100, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
            ],
            options={
                'db_table': 'transmissor_eventos_esocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportacaoArquivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=10)),
                ('versao', models.CharField(max_length=30)),
                ('identidade_evento', models.CharField(max_length=100)),
                ('identidade', models.IntegerField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Importa\xe7\xe3o realizada com sucesso!'), (2, 'Erro na importa\xe7\xe3o!')])),
                ('data_hora', models.DateTimeField()),
                ('origem', models.IntegerField(choices=[(1, 'Manual'), (2, 'Autom\xe1tico')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='importacaoarquivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('importado_por', models.ForeignKey(related_name='importacaoarquivos_importado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='importacaoarquivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['evento', 'versao', 'identidade_evento', 'identidade', 'arquivo'],
                'db_table': 'importacao_arquivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegrasDeValidacao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('evento', models.CharField(max_length=5000)),
                ('versao', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('registro_campo', models.CharField(max_length=100)),
                ('registro_pai', models.CharField(max_length=100)),
                ('elemento', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=1)),
                ('ocorrencias', models.CharField(max_length=10)),
                ('tamanho', models.CharField(max_length=10)),
                ('casas_decimais', models.CharField(max_length=10)),
                ('obrigatorio', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('descricao', models.TextField()),
                ('tabela', models.CharField(max_length=200, null=True, blank=True)),
                ('valores_validos', models.TextField(null=True, blank=True)),
                ('validacoes_precedencia', models.TextField(null=True, blank=True)),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='regrasdevalidacao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='regrasdevalidacao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'regras_validacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLote',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome_empresa', models.CharField(unique=True, max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('tipo_inscricao', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('data_abertura', models.DateField()),
                ('validar_eventos', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('envio_automatico', models.IntegerField(choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('logotipo', models.ImageField(upload_to=b'')),
                ('endereco_completo', models.TextField()),
                ('esocial_lote_min', models.IntegerField()),
                ('esocial_lote_max', models.IntegerField()),
                ('esocial_timeout', models.IntegerField()),
                ('reinf_lote_min', models.IntegerField()),
                ('reinf_lote_max', models.IntegerField()),
                ('reinf_timeout', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorlote_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorlote_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'transmissores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEfdreinf',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contribuinte_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('contribuinte_nrinsc', models.CharField(max_length=15)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (2, 'Erro na valida\xe7\xe3o'), (3, 'Validado'), (4, 'Erro no envio'), (5, 'Aguardando envio'), (6, 'Enviado com sucesso'), (7, 'Erro na consulta'), (8, 'Consultado com sucesso')])),
                ('codigo_status', models.IntegerField(blank=True, null=True, choices=[(0, '0 - Sucesso'), (1, '1 - Erro'), (2, '2 - Em Processamento')])),
                ('identidade_transmissor', models.CharField(max_length=20, null=True, blank=True)),
                ('retorno_descricao', models.TextField(null=True, blank=True)),
                ('recepcao_data_hora', models.DateTimeField(max_length=50, null=True, blank=True)),
                ('recepcao_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('numero_protocolo_fechamento', models.CharField(max_length=50, null=True, blank=True)),
                ('protocolo', models.CharField(max_length=50, null=True, blank=True)),
                ('processamento_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('tempo_estimado_conclusao', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteefdreinf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteefdreinf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor', models.ForeignKey(related_name='transmissorloteefdreinf_transmissor', blank=True, to='mensageiro.TransmissorLote', max_length=1, null=True)),
            ],
            options={
                'db_table': 'transmissor_lote_efdreinf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEfdreinfOcorrencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('resposta_codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, '1 - Aviso'), (2, '2 - Erro')])),
                ('localizacao', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteefdreinfocorrencias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteefdreinfocorrencias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor_lote_efdreinf', models.ForeignKey(related_name='transmissorloteefdreinfocorrencias_transmissor_lote_efdreinf', to='mensageiro.TransmissorLoteEfdreinf')),
            ],
            options={
                'db_table': 'transmissor_lote_efdreinf_ocorrencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEsocial',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empregador_tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('empregador_nrinsc', models.CharField(max_length=15)),
                ('grupo', models.IntegerField(choices=[(1, '1 - Eventos de Tabelas'), (2, '2 - Eventos N\xe3o Peri\xf3dicos'), (3, '3 - Eventos Peri\xf3dicos')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (2, 'Erro na valida\xe7\xe3o'), (3, 'Validado'), (4, 'Erro no envio'), (5, 'Aguardando envio'), (6, 'Enviado com sucesso'), (7, 'Erro na consulta'), (8, 'Consultado com sucesso')])),
                ('resposta_codigo', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('resposta_descricao', models.TextField(null=True, blank=True)),
                ('recepcao_data_hora', models.DateTimeField(max_length=50, null=True, blank=True)),
                ('recepcao_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('protocolo', models.CharField(max_length=50, null=True, blank=True)),
                ('processamento_versao_aplicativo', models.CharField(max_length=50, null=True, blank=True)),
                ('tempo_estimado_conclusao', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteesocial_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteesocial_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor', models.ForeignKey(related_name='transmissorloteesocial_transmissor', blank=True, to='mensageiro.TransmissorLote', max_length=1, null=True)),
            ],
            options={
                'db_table': 'transmissor_lote_esocial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissorLoteEsocialOcorrencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('resposta_codigo', models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Advert\xeancia')])),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Advert\xeancia')])),
                ('localizacao', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='transmissorloteesocialocorrencias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='transmissorloteesocialocorrencias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('transmissor_lote_esocial', models.ForeignKey(related_name='transmissorloteesocialocorrencias_transmissor_lote_esocial', to='mensageiro.TransmissorLoteEsocial')),
            ],
            options={
                'db_table': 'transmissor_lote_esocial_ocorrencias',
                'managed': True,
            },
        ),
    ]
