# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensageiro', '0003_auto_20180911_2127'),
    ]

    operations = [

        migrations.RunSQL("""
        
CREATE OR REPLACE VIEW public.transmissor_eventos_efdreinf AS 
 SELECT r1000_evtinfocontri.id,
    'r1000'::text AS evento,
    r1000_evtinfocontri.identidade,
    r1000_evtinfocontri.transmissor_lote_efdreinf_id,
    r1000_evtinfocontri.criado_em,
    r1000_evtinfocontri.criado_por_id,
    r1000_evtinfocontri.modificado_em,
    r1000_evtinfocontri.modificado_por_id,
    r1000_evtinfocontri.excluido,
    1 AS grupo,
    'r1000_evtinfocontri'::text AS tabela,
    'r1000_evtinfocontri_salvar'::text AS tabela_salvar,
    r1000_evtinfocontri.id AS ordem,
    r1000_evtinfocontri.tpinsc,
    r1000_evtinfocontri.nrinsc,
    'r1000_evtinfocontri_recibo'::text AS url_recibo,
    r1000_evtinfocontri.validacao_precedencia,
    r1000_evtinfocontri.validacoes,
    r1000_evtinfocontri.status,
    r1000_evtinfocontri.retornos_evttotal_id,
    r1000_evtinfocontri.retornos_evttotalcontrib_id,
    r1000_evtinfocontri.ocorrencias
   FROM r1000_evtinfocontri
  WHERE r1000_evtinfocontri.excluido = false
UNION
 SELECT r1070_evttabprocesso.id,
    'r1070'::text AS evento,
    r1070_evttabprocesso.identidade,
    r1070_evttabprocesso.transmissor_lote_efdreinf_id,
    r1070_evttabprocesso.criado_em,
    r1070_evttabprocesso.criado_por_id,
    r1070_evttabprocesso.modificado_em,
    r1070_evttabprocesso.modificado_por_id,
    r1070_evttabprocesso.excluido,
    1 AS grupo,
    'r1070_evttabprocesso'::text AS tabela,
    'r1070_evttabprocesso_salvar'::text AS tabela_salvar,
    r1070_evttabprocesso.id AS ordem,
    r1070_evttabprocesso.tpinsc,
    r1070_evttabprocesso.nrinsc,
    'r1070_evttabprocesso_recibo'::text AS url_recibo,
    r1070_evttabprocesso.validacao_precedencia,
    r1070_evttabprocesso.validacoes,
    r1070_evttabprocesso.status,
    r1070_evttabprocesso.retornos_evttotal_id,
    r1070_evttabprocesso.retornos_evttotalcontrib_id,
    r1070_evttabprocesso.ocorrencias
   FROM r1070_evttabprocesso
  WHERE r1070_evttabprocesso.excluido = false
UNION
 SELECT r2010_evtservtom.id,
    'r2010'::text AS evento,
    r2010_evtservtom.identidade,
    r2010_evtservtom.transmissor_lote_efdreinf_id,
    r2010_evtservtom.criado_em,
    r2010_evtservtom.criado_por_id,
    r2010_evtservtom.modificado_em,
    r2010_evtservtom.modificado_por_id,
    r2010_evtservtom.excluido,
    3 AS grupo,
    'r2010_evtservtom'::text AS tabela,
    'r2010_evtservtom_salvar'::text AS tabela_salvar,
    r2010_evtservtom.id AS ordem,
    r2010_evtservtom.tpinsc,
    r2010_evtservtom.nrinsc,
    'r2010_evtservtom_recibo'::text AS url_recibo,
    r2010_evtservtom.validacao_precedencia,
    r2010_evtservtom.validacoes,
    r2010_evtservtom.status,
    r2010_evtservtom.retornos_evttotal_id,
    r2010_evtservtom.retornos_evttotalcontrib_id,
    r2010_evtservtom.ocorrencias
   FROM r2010_evtservtom
  WHERE r2010_evtservtom.excluido = false
UNION
 SELECT r2020_evtservprest.id,
    'r2020'::text AS evento,
    r2020_evtservprest.identidade,
    r2020_evtservprest.transmissor_lote_efdreinf_id,
    r2020_evtservprest.criado_em,
    r2020_evtservprest.criado_por_id,
    r2020_evtservprest.modificado_em,
    r2020_evtservprest.modificado_por_id,
    r2020_evtservprest.excluido,
    3 AS grupo,
    'r2020_evtservprest'::text AS tabela,
    'r2020_evtservprest_salvar'::text AS tabela_salvar,
    r2020_evtservprest.id AS ordem,
    r2020_evtservprest.tpinsc,
    r2020_evtservprest.nrinsc,
    'r2020_evtservprest_recibo'::text AS url_recibo,
    r2020_evtservprest.validacao_precedencia,
    r2020_evtservprest.validacoes,
    r2020_evtservprest.status,
    r2020_evtservprest.retornos_evttotal_id,
    r2020_evtservprest.retornos_evttotalcontrib_id,
    r2020_evtservprest.ocorrencias
   FROM r2020_evtservprest
  WHERE r2020_evtservprest.excluido = false
UNION
 SELECT r2030_evtassocdesprec.id,
    'r2030'::text AS evento,
    r2030_evtassocdesprec.identidade,
    r2030_evtassocdesprec.transmissor_lote_efdreinf_id,
    r2030_evtassocdesprec.criado_em,
    r2030_evtassocdesprec.criado_por_id,
    r2030_evtassocdesprec.modificado_em,
    r2030_evtassocdesprec.modificado_por_id,
    r2030_evtassocdesprec.excluido,
    3 AS grupo,
    'r2030_evtassocdesprec'::text AS tabela,
    'r2030_evtassocdesprec_salvar'::text AS tabela_salvar,
    r2030_evtassocdesprec.id AS ordem,
    r2030_evtassocdesprec.tpinsc,
    r2030_evtassocdesprec.nrinsc,
    'r2030_evtassocdesprec_recibo'::text AS url_recibo,
    r2030_evtassocdesprec.validacao_precedencia,
    r2030_evtassocdesprec.validacoes,
    r2030_evtassocdesprec.status,
    r2030_evtassocdesprec.retornos_evttotal_id,
    r2030_evtassocdesprec.retornos_evttotalcontrib_id,
    r2030_evtassocdesprec.ocorrencias
   FROM r2030_evtassocdesprec
  WHERE r2030_evtassocdesprec.excluido = false
UNION
 SELECT r2040_evtassocdesprep.id,
    'r2040'::text AS evento,
    r2040_evtassocdesprep.identidade,
    r2040_evtassocdesprep.transmissor_lote_efdreinf_id,
    r2040_evtassocdesprep.criado_em,
    r2040_evtassocdesprep.criado_por_id,
    r2040_evtassocdesprep.modificado_em,
    r2040_evtassocdesprep.modificado_por_id,
    r2040_evtassocdesprep.excluido,
    3 AS grupo,
    'r2040_evtassocdesprep'::text AS tabela,
    'r2040_evtassocdesprep_salvar'::text AS tabela_salvar,
    r2040_evtassocdesprep.id AS ordem,
    r2040_evtassocdesprep.tpinsc,
    r2040_evtassocdesprep.nrinsc,
    'r2040_evtassocdesprep_recibo'::text AS url_recibo,
    r2040_evtassocdesprep.validacao_precedencia,
    r2040_evtassocdesprep.validacoes,
    r2040_evtassocdesprep.status,
    r2040_evtassocdesprep.retornos_evttotal_id,
    r2040_evtassocdesprep.retornos_evttotalcontrib_id,
    r2040_evtassocdesprep.ocorrencias
   FROM r2040_evtassocdesprep
  WHERE r2040_evtassocdesprep.excluido = false
UNION
 SELECT r2050_evtcomprod.id,
    'r2050'::text AS evento,
    r2050_evtcomprod.identidade,
    r2050_evtcomprod.transmissor_lote_efdreinf_id,
    r2050_evtcomprod.criado_em,
    r2050_evtcomprod.criado_por_id,
    r2050_evtcomprod.modificado_em,
    r2050_evtcomprod.modificado_por_id,
    r2050_evtcomprod.excluido,
    3 AS grupo,
    'r2050_evtcomprod'::text AS tabela,
    'r2050_evtcomprod_salvar'::text AS tabela_salvar,
    r2050_evtcomprod.id AS ordem,
    r2050_evtcomprod.tpinsc,
    r2050_evtcomprod.nrinsc,
    'r2050_evtcomprod_recibo'::text AS url_recibo,
    r2050_evtcomprod.validacao_precedencia,
    r2050_evtcomprod.validacoes,
    r2050_evtcomprod.status,
    r2050_evtcomprod.retornos_evttotal_id,
    r2050_evtcomprod.retornos_evttotalcontrib_id,
    r2050_evtcomprod.ocorrencias
   FROM r2050_evtcomprod
  WHERE r2050_evtcomprod.excluido = false
UNION
 SELECT r2060_evtcprb.id,
    'r2060'::text AS evento,
    r2060_evtcprb.identidade,
    r2060_evtcprb.transmissor_lote_efdreinf_id,
    r2060_evtcprb.criado_em,
    r2060_evtcprb.criado_por_id,
    r2060_evtcprb.modificado_em,
    r2060_evtcprb.modificado_por_id,
    r2060_evtcprb.excluido,
    3 AS grupo,
    'r2060_evtcprb'::text AS tabela,
    'r2060_evtcprb_salvar'::text AS tabela_salvar,
    r2060_evtcprb.id AS ordem,
    r2060_evtcprb.tpinsc,
    r2060_evtcprb.nrinsc,
    'r2060_evtcprb_recibo'::text AS url_recibo,
    r2060_evtcprb.validacao_precedencia,
    r2060_evtcprb.validacoes,
    r2060_evtcprb.status,
    r2060_evtcprb.retornos_evttotal_id,
    r2060_evtcprb.retornos_evttotalcontrib_id,
    r2060_evtcprb.ocorrencias
   FROM r2060_evtcprb
  WHERE r2060_evtcprb.excluido = false
UNION
 SELECT r2070_evtpgtosdivs.id,
    'r2070'::text AS evento,
    r2070_evtpgtosdivs.identidade,
    r2070_evtpgtosdivs.transmissor_lote_efdreinf_id,
    r2070_evtpgtosdivs.criado_em,
    r2070_evtpgtosdivs.criado_por_id,
    r2070_evtpgtosdivs.modificado_em,
    r2070_evtpgtosdivs.modificado_por_id,
    r2070_evtpgtosdivs.excluido,
    3 AS grupo,
    'r2070_evtpgtosdivs'::text AS tabela,
    'r2070_evtpgtosdivs_salvar'::text AS tabela_salvar,
    r2070_evtpgtosdivs.id AS ordem,
    r2070_evtpgtosdivs.tpinsc,
    r2070_evtpgtosdivs.nrinsc,
    'r2070_evtpgtosdivs_recibo'::text AS url_recibo,
    r2070_evtpgtosdivs.validacao_precedencia,
    r2070_evtpgtosdivs.validacoes,
    r2070_evtpgtosdivs.status,
    r2070_evtpgtosdivs.retornos_evttotal_id,
    r2070_evtpgtosdivs.retornos_evttotalcontrib_id,
    r2070_evtpgtosdivs.ocorrencias
   FROM r2070_evtpgtosdivs
  WHERE r2070_evtpgtosdivs.excluido = false
UNION
 SELECT r2098_evtreabreevper.id,
    'r2098'::text AS evento,
    r2098_evtreabreevper.identidade,
    r2098_evtreabreevper.transmissor_lote_efdreinf_id,
    r2098_evtreabreevper.criado_em,
    r2098_evtreabreevper.criado_por_id,
    r2098_evtreabreevper.modificado_em,
    r2098_evtreabreevper.modificado_por_id,
    r2098_evtreabreevper.excluido,
    3 AS grupo,
    'r2098_evtreabreevper'::text AS tabela,
    'r2098_evtreabreevper_salvar'::text AS tabela_salvar,
    r2098_evtreabreevper.id AS ordem,
    r2098_evtreabreevper.tpinsc,
    r2098_evtreabreevper.nrinsc,
    'r2098_evtreabreevper_recibo'::text AS url_recibo,
    r2098_evtreabreevper.validacao_precedencia,
    r2098_evtreabreevper.validacoes,
    r2098_evtreabreevper.status,
    r2098_evtreabreevper.retornos_evttotal_id,
    r2098_evtreabreevper.retornos_evttotalcontrib_id,
    r2098_evtreabreevper.ocorrencias
   FROM r2098_evtreabreevper
  WHERE r2098_evtreabreevper.excluido = false
UNION
 SELECT r2099_evtfechaevper.id,
    'r2099'::text AS evento,
    r2099_evtfechaevper.identidade,
    r2099_evtfechaevper.transmissor_lote_efdreinf_id,
    r2099_evtfechaevper.criado_em,
    r2099_evtfechaevper.criado_por_id,
    r2099_evtfechaevper.modificado_em,
    r2099_evtfechaevper.modificado_por_id,
    r2099_evtfechaevper.excluido,
    3 AS grupo,
    'r2099_evtfechaevper'::text AS tabela,
    'r2099_evtfechaevper_salvar'::text AS tabela_salvar,
    r2099_evtfechaevper.id AS ordem,
    r2099_evtfechaevper.tpinsc,
    r2099_evtfechaevper.nrinsc,
    'r2099_evtfechaevper_recibo'::text AS url_recibo,
    r2099_evtfechaevper.validacao_precedencia,
    r2099_evtfechaevper.validacoes,
    r2099_evtfechaevper.status,
    r2099_evtfechaevper.retornos_evttotal_id,
    r2099_evtfechaevper.retornos_evttotalcontrib_id,
    r2099_evtfechaevper.ocorrencias
   FROM r2099_evtfechaevper
  WHERE r2099_evtfechaevper.excluido = false
UNION
 SELECT r3010_evtespdesportivo.id,
    'r3010'::text AS evento,
    r3010_evtespdesportivo.identidade,
    r3010_evtespdesportivo.transmissor_lote_efdreinf_id,
    r3010_evtespdesportivo.criado_em,
    r3010_evtespdesportivo.criado_por_id,
    r3010_evtespdesportivo.modificado_em,
    r3010_evtespdesportivo.modificado_por_id,
    r3010_evtespdesportivo.excluido,
    2 AS grupo,
    'r3010_evtespdesportivo'::text AS tabela,
    'r3010_evtespdesportivo_salvar'::text AS tabela_salvar,
    r3010_evtespdesportivo.id AS ordem,
    r3010_evtespdesportivo.tpinsc,
    r3010_evtespdesportivo.nrinsc,
    'r3010_evtespdesportivo_recibo'::text AS url_recibo,
    r3010_evtespdesportivo.validacao_precedencia,
    r3010_evtespdesportivo.validacoes,
    r3010_evtespdesportivo.status,
    r3010_evtespdesportivo.retornos_evttotal_id,
    r3010_evtespdesportivo.retornos_evttotalcontrib_id,
    r3010_evtespdesportivo.ocorrencias
   FROM r3010_evtespdesportivo
  WHERE r3010_evtespdesportivo.excluido = false
UNION
 SELECT r9000_evtexclusao.id,
    'r9000'::text AS evento,
    r9000_evtexclusao.identidade,
    r9000_evtexclusao.transmissor_lote_efdreinf_id,
    r9000_evtexclusao.criado_em,
    r9000_evtexclusao.criado_por_id,
    r9000_evtexclusao.modificado_em,
    r9000_evtexclusao.modificado_por_id,
    r9000_evtexclusao.excluido,
    3 AS grupo,
    'r9000_evtexclusao'::text AS tabela,
    'r9000_evtexclusao_salvar'::text AS tabela_salvar,
    r9000_evtexclusao.id AS ordem,
    r9000_evtexclusao.tpinsc,
    r9000_evtexclusao.nrinsc,
    'r9000_evtexclusao_recibo'::text AS url_recibo,
    r9000_evtexclusao.validacao_precedencia,
    r9000_evtexclusao.validacoes,
    r9000_evtexclusao.status,
    r9000_evtexclusao.retornos_evttotal_id,
    r9000_evtexclusao.retornos_evttotalcontrib_id,
    r9000_evtexclusao.ocorrencias
   FROM r9000_evtexclusao
  WHERE r9000_evtexclusao.excluido = false;


  CREATE OR REPLACE VIEW public.transmissor_eventos_efdreinf_totalizacoes AS 
 SELECT r5001_evttotal.id,
    'r5001'::text AS evento,
    r5001_evttotal.identidade,
    r5001_evttotal.transmissor_lote_efdreinf_id,
    r5001_evttotal.criado_em,
    r5001_evttotal.criado_por_id,
    r5001_evttotal.modificado_em,
    r5001_evttotal.modificado_por_id,
    r5001_evttotal.excluido,
    3 AS grupo,
    'r5001_evttotal'::text AS tabela,
    'r5001_evttotal_salvar'::text AS tabela_salvar,
    r5001_evttotal.id AS ordem,
    r5001_evttotal.tpinsc,
    r5001_evttotal.nrinsc,
    'r5001_evttotal_recibo'::text AS url_recibo,
    r5001_evttotal.validacao_precedencia,
    r5001_evttotal.validacoes,
    r5001_evttotal.status,
    r5001_evttotal.retornos_evttotal_id,
    r5001_evttotal.retornos_evttotalcontrib_id,
    r5001_evttotal.ocorrencias
   FROM r5001_evttotal
  WHERE r5001_evttotal.excluido = false
UNION
 SELECT r5011_evttotalcontrib.id,
    'r5011'::text AS evento,
    r5011_evttotalcontrib.identidade,
    r5011_evttotalcontrib.transmissor_lote_efdreinf_id,
    r5011_evttotalcontrib.criado_em,
    r5011_evttotalcontrib.criado_por_id,
    r5011_evttotalcontrib.modificado_em,
    r5011_evttotalcontrib.modificado_por_id,
    r5011_evttotalcontrib.excluido,
    3 AS grupo,
    'r5011_evttotalcontrib'::text AS tabela,
    'r5011_evttotalcontrib_salvar'::text AS tabela_salvar,
    r5011_evttotalcontrib.id AS ordem,
    r5011_evttotalcontrib.tpinsc,
    r5011_evttotalcontrib.nrinsc,
    'r5011_evttotalcontrib_recibo'::text AS url_recibo,
    r5011_evttotalcontrib.validacao_precedencia,
    r5011_evttotalcontrib.validacoes,
    r5011_evttotalcontrib.status,
    r5011_evttotalcontrib.retornos_evttotal_id,
    r5011_evttotalcontrib.retornos_evttotalcontrib_id,
    r5011_evttotalcontrib.ocorrencias
   FROM r5011_evttotalcontrib
  WHERE r5011_evttotalcontrib.excluido = false;


  CREATE OR REPLACE VIEW public.transmissor_eventos_esocial AS 
 SELECT s1000_evtinfoempregador.id,
    's1000'::text AS evento,
    s1000_evtinfoempregador.identidade,
    s1000_evtinfoempregador.transmissor_lote_esocial_id,
    s1000_evtinfoempregador.criado_em,
    s1000_evtinfoempregador.criado_por_id,
    s1000_evtinfoempregador.modificado_em,
    s1000_evtinfoempregador.modificado_por_id,
    s1000_evtinfoempregador.excluido,
    1 AS grupo,
    's1000_evtinfoempregador'::text AS tabela,
    's1000_evtinfoempregador_salvar'::text AS tabela_salvar,
    s1000_evtinfoempregador.id AS ordem,
    s1000_evtinfoempregador.tpinsc,
    s1000_evtinfoempregador.nrinsc,
    s1000_evtinfoempregador.recibo_numero,
    s1000_evtinfoempregador.recibo_hash,
    's1000_evtinfoempregador_recibo'::text AS url_recibo,
    s1000_evtinfoempregador.processamento_codigo_resposta,
    s1000_evtinfoempregador.processamento_descricao_resposta,
    s1000_evtinfoempregador.validacao_precedencia,
    s1000_evtinfoempregador.validacoes,
    s1000_evtinfoempregador.status,
    s1000_evtinfoempregador.retornos_eventos_id,
    s1000_evtinfoempregador.ocorrencias
   FROM s1000_evtinfoempregador
  WHERE s1000_evtinfoempregador.excluido = false
UNION
 SELECT s1005_evttabestab.id,
    's1005'::text AS evento,
    s1005_evttabestab.identidade,
    s1005_evttabestab.transmissor_lote_esocial_id,
    s1005_evttabestab.criado_em,
    s1005_evttabestab.criado_por_id,
    s1005_evttabestab.modificado_em,
    s1005_evttabestab.modificado_por_id,
    s1005_evttabestab.excluido,
    1 AS grupo,
    's1005_evttabestab'::text AS tabela,
    's1005_evttabestab_salvar'::text AS tabela_salvar,
    s1005_evttabestab.id AS ordem,
    s1005_evttabestab.tpinsc,
    s1005_evttabestab.nrinsc,
    s1005_evttabestab.recibo_numero,
    s1005_evttabestab.recibo_hash,
    's1005_evttabestab_recibo'::text AS url_recibo,
    s1005_evttabestab.processamento_codigo_resposta,
    s1005_evttabestab.processamento_descricao_resposta,
    s1005_evttabestab.validacao_precedencia,
    s1005_evttabestab.validacoes,
    s1005_evttabestab.status,
    s1005_evttabestab.retornos_eventos_id,
    s1005_evttabestab.ocorrencias
   FROM s1005_evttabestab
  WHERE s1005_evttabestab.excluido = false
UNION
 SELECT s1010_evttabrubrica.id,
    's1010'::text AS evento,
    s1010_evttabrubrica.identidade,
    s1010_evttabrubrica.transmissor_lote_esocial_id,
    s1010_evttabrubrica.criado_em,
    s1010_evttabrubrica.criado_por_id,
    s1010_evttabrubrica.modificado_em,
    s1010_evttabrubrica.modificado_por_id,
    s1010_evttabrubrica.excluido,
    1 AS grupo,
    's1010_evttabrubrica'::text AS tabela,
    's1010_evttabrubrica_salvar'::text AS tabela_salvar,
    s1010_evttabrubrica.id AS ordem,
    s1010_evttabrubrica.tpinsc,
    s1010_evttabrubrica.nrinsc,
    s1010_evttabrubrica.recibo_numero,
    s1010_evttabrubrica.recibo_hash,
    's1010_evttabrubrica_recibo'::text AS url_recibo,
    s1010_evttabrubrica.processamento_codigo_resposta,
    s1010_evttabrubrica.processamento_descricao_resposta,
    s1010_evttabrubrica.validacao_precedencia,
    s1010_evttabrubrica.validacoes,
    s1010_evttabrubrica.status,
    s1010_evttabrubrica.retornos_eventos_id,
    s1010_evttabrubrica.ocorrencias
   FROM s1010_evttabrubrica
  WHERE s1010_evttabrubrica.excluido = false
UNION
 SELECT s1020_evttablotacao.id,
    's1020'::text AS evento,
    s1020_evttablotacao.identidade,
    s1020_evttablotacao.transmissor_lote_esocial_id,
    s1020_evttablotacao.criado_em,
    s1020_evttablotacao.criado_por_id,
    s1020_evttablotacao.modificado_em,
    s1020_evttablotacao.modificado_por_id,
    s1020_evttablotacao.excluido,
    1 AS grupo,
    's1020_evttablotacao'::text AS tabela,
    's1020_evttablotacao_salvar'::text AS tabela_salvar,
    s1020_evttablotacao.id AS ordem,
    s1020_evttablotacao.tpinsc,
    s1020_evttablotacao.nrinsc,
    s1020_evttablotacao.recibo_numero,
    s1020_evttablotacao.recibo_hash,
    's1020_evttablotacao_recibo'::text AS url_recibo,
    s1020_evttablotacao.processamento_codigo_resposta,
    s1020_evttablotacao.processamento_descricao_resposta,
    s1020_evttablotacao.validacao_precedencia,
    s1020_evttablotacao.validacoes,
    s1020_evttablotacao.status,
    s1020_evttablotacao.retornos_eventos_id,
    s1020_evttablotacao.ocorrencias
   FROM s1020_evttablotacao
  WHERE s1020_evttablotacao.excluido = false
UNION
 SELECT s1030_evttabcargo.id,
    's1030'::text AS evento,
    s1030_evttabcargo.identidade,
    s1030_evttabcargo.transmissor_lote_esocial_id,
    s1030_evttabcargo.criado_em,
    s1030_evttabcargo.criado_por_id,
    s1030_evttabcargo.modificado_em,
    s1030_evttabcargo.modificado_por_id,
    s1030_evttabcargo.excluido,
    1 AS grupo,
    's1030_evttabcargo'::text AS tabela,
    's1030_evttabcargo_salvar'::text AS tabela_salvar,
    s1030_evttabcargo.id AS ordem,
    s1030_evttabcargo.tpinsc,
    s1030_evttabcargo.nrinsc,
    s1030_evttabcargo.recibo_numero,
    s1030_evttabcargo.recibo_hash,
    's1030_evttabcargo_recibo'::text AS url_recibo,
    s1030_evttabcargo.processamento_codigo_resposta,
    s1030_evttabcargo.processamento_descricao_resposta,
    s1030_evttabcargo.validacao_precedencia,
    s1030_evttabcargo.validacoes,
    s1030_evttabcargo.status,
    s1030_evttabcargo.retornos_eventos_id,
    s1030_evttabcargo.ocorrencias
   FROM s1030_evttabcargo
  WHERE s1030_evttabcargo.excluido = false
UNION
 SELECT s1035_evttabcarreira.id,
    's1035'::text AS evento,
    s1035_evttabcarreira.identidade,
    s1035_evttabcarreira.transmissor_lote_esocial_id,
    s1035_evttabcarreira.criado_em,
    s1035_evttabcarreira.criado_por_id,
    s1035_evttabcarreira.modificado_em,
    s1035_evttabcarreira.modificado_por_id,
    s1035_evttabcarreira.excluido,
    1 AS grupo,
    's1035_evttabcarreira'::text AS tabela,
    's1035_evttabcarreira_salvar'::text AS tabela_salvar,
    s1035_evttabcarreira.id AS ordem,
    s1035_evttabcarreira.tpinsc,
    s1035_evttabcarreira.nrinsc,
    s1035_evttabcarreira.recibo_numero,
    s1035_evttabcarreira.recibo_hash,
    's1035_evttabcarreira_recibo'::text AS url_recibo,
    s1035_evttabcarreira.processamento_codigo_resposta,
    s1035_evttabcarreira.processamento_descricao_resposta,
    s1035_evttabcarreira.validacao_precedencia,
    s1035_evttabcarreira.validacoes,
    s1035_evttabcarreira.status,
    s1035_evttabcarreira.retornos_eventos_id,
    s1035_evttabcarreira.ocorrencias
   FROM s1035_evttabcarreira
  WHERE s1035_evttabcarreira.excluido = false
UNION
 SELECT s1040_evttabfuncao.id,
    's1040'::text AS evento,
    s1040_evttabfuncao.identidade,
    s1040_evttabfuncao.transmissor_lote_esocial_id,
    s1040_evttabfuncao.criado_em,
    s1040_evttabfuncao.criado_por_id,
    s1040_evttabfuncao.modificado_em,
    s1040_evttabfuncao.modificado_por_id,
    s1040_evttabfuncao.excluido,
    1 AS grupo,
    's1040_evttabfuncao'::text AS tabela,
    's1040_evttabfuncao_salvar'::text AS tabela_salvar,
    s1040_evttabfuncao.id AS ordem,
    s1040_evttabfuncao.tpinsc,
    s1040_evttabfuncao.nrinsc,
    s1040_evttabfuncao.recibo_numero,
    s1040_evttabfuncao.recibo_hash,
    's1040_evttabfuncao_recibo'::text AS url_recibo,
    s1040_evttabfuncao.processamento_codigo_resposta,
    s1040_evttabfuncao.processamento_descricao_resposta,
    s1040_evttabfuncao.validacao_precedencia,
    s1040_evttabfuncao.validacoes,
    s1040_evttabfuncao.status,
    s1040_evttabfuncao.retornos_eventos_id,
    s1040_evttabfuncao.ocorrencias
   FROM s1040_evttabfuncao
  WHERE s1040_evttabfuncao.excluido = false
UNION
 SELECT s1050_evttabhortur.id,
    's1050'::text AS evento,
    s1050_evttabhortur.identidade,
    s1050_evttabhortur.transmissor_lote_esocial_id,
    s1050_evttabhortur.criado_em,
    s1050_evttabhortur.criado_por_id,
    s1050_evttabhortur.modificado_em,
    s1050_evttabhortur.modificado_por_id,
    s1050_evttabhortur.excluido,
    1 AS grupo,
    's1050_evttabhortur'::text AS tabela,
    's1050_evttabhortur_salvar'::text AS tabela_salvar,
    s1050_evttabhortur.id AS ordem,
    s1050_evttabhortur.tpinsc,
    s1050_evttabhortur.nrinsc,
    s1050_evttabhortur.recibo_numero,
    s1050_evttabhortur.recibo_hash,
    's1050_evttabhortur_recibo'::text AS url_recibo,
    s1050_evttabhortur.processamento_codigo_resposta,
    s1050_evttabhortur.processamento_descricao_resposta,
    s1050_evttabhortur.validacao_precedencia,
    s1050_evttabhortur.validacoes,
    s1050_evttabhortur.status,
    s1050_evttabhortur.retornos_eventos_id,
    s1050_evttabhortur.ocorrencias
   FROM s1050_evttabhortur
  WHERE s1050_evttabhortur.excluido = false
UNION
 SELECT s1060_evttabambiente.id,
    's1060'::text AS evento,
    s1060_evttabambiente.identidade,
    s1060_evttabambiente.transmissor_lote_esocial_id,
    s1060_evttabambiente.criado_em,
    s1060_evttabambiente.criado_por_id,
    s1060_evttabambiente.modificado_em,
    s1060_evttabambiente.modificado_por_id,
    s1060_evttabambiente.excluido,
    1 AS grupo,
    's1060_evttabambiente'::text AS tabela,
    's1060_evttabambiente_salvar'::text AS tabela_salvar,
    s1060_evttabambiente.id AS ordem,
    s1060_evttabambiente.tpinsc,
    s1060_evttabambiente.nrinsc,
    s1060_evttabambiente.recibo_numero,
    s1060_evttabambiente.recibo_hash,
    's1060_evttabambiente_recibo'::text AS url_recibo,
    s1060_evttabambiente.processamento_codigo_resposta,
    s1060_evttabambiente.processamento_descricao_resposta,
    s1060_evttabambiente.validacao_precedencia,
    s1060_evttabambiente.validacoes,
    s1060_evttabambiente.status,
    s1060_evttabambiente.retornos_eventos_id,
    s1060_evttabambiente.ocorrencias
   FROM s1060_evttabambiente
  WHERE s1060_evttabambiente.excluido = false
UNION
 SELECT s1070_evttabprocesso.id,
    's1070'::text AS evento,
    s1070_evttabprocesso.identidade,
    s1070_evttabprocesso.transmissor_lote_esocial_id,
    s1070_evttabprocesso.criado_em,
    s1070_evttabprocesso.criado_por_id,
    s1070_evttabprocesso.modificado_em,
    s1070_evttabprocesso.modificado_por_id,
    s1070_evttabprocesso.excluido,
    1 AS grupo,
    's1070_evttabprocesso'::text AS tabela,
    's1070_evttabprocesso_salvar'::text AS tabela_salvar,
    s1070_evttabprocesso.id AS ordem,
    s1070_evttabprocesso.tpinsc,
    s1070_evttabprocesso.nrinsc,
    s1070_evttabprocesso.recibo_numero,
    s1070_evttabprocesso.recibo_hash,
    's1070_evttabprocesso_recibo'::text AS url_recibo,
    s1070_evttabprocesso.processamento_codigo_resposta,
    s1070_evttabprocesso.processamento_descricao_resposta,
    s1070_evttabprocesso.validacao_precedencia,
    s1070_evttabprocesso.validacoes,
    s1070_evttabprocesso.status,
    s1070_evttabprocesso.retornos_eventos_id,
    s1070_evttabprocesso.ocorrencias
   FROM s1070_evttabprocesso
  WHERE s1070_evttabprocesso.excluido = false
UNION
 SELECT s1080_evttaboperport.id,
    's1080'::text AS evento,
    s1080_evttaboperport.identidade,
    s1080_evttaboperport.transmissor_lote_esocial_id,
    s1080_evttaboperport.criado_em,
    s1080_evttaboperport.criado_por_id,
    s1080_evttaboperport.modificado_em,
    s1080_evttaboperport.modificado_por_id,
    s1080_evttaboperport.excluido,
    1 AS grupo,
    's1080_evttaboperport'::text AS tabela,
    's1080_evttaboperport_salvar'::text AS tabela_salvar,
    s1080_evttaboperport.id AS ordem,
    s1080_evttaboperport.tpinsc,
    s1080_evttaboperport.nrinsc,
    s1080_evttaboperport.recibo_numero,
    s1080_evttaboperport.recibo_hash,
    's1080_evttaboperport_recibo'::text AS url_recibo,
    s1080_evttaboperport.processamento_codigo_resposta,
    s1080_evttaboperport.processamento_descricao_resposta,
    s1080_evttaboperport.validacao_precedencia,
    s1080_evttaboperport.validacoes,
    s1080_evttaboperport.status,
    s1080_evttaboperport.retornos_eventos_id,
    s1080_evttaboperport.ocorrencias
   FROM s1080_evttaboperport
  WHERE s1080_evttaboperport.excluido = false
UNION
 SELECT s1200_evtremun.id,
    's1200'::text AS evento,
    s1200_evtremun.identidade,
    s1200_evtremun.transmissor_lote_esocial_id,
    s1200_evtremun.criado_em,
    s1200_evtremun.criado_por_id,
    s1200_evtremun.modificado_em,
    s1200_evtremun.modificado_por_id,
    s1200_evtremun.excluido,
    3 AS grupo,
    's1200_evtremun'::text AS tabela,
    's1200_evtremun_salvar'::text AS tabela_salvar,
    s1200_evtremun.id AS ordem,
    s1200_evtremun.tpinsc,
    s1200_evtremun.nrinsc,
    s1200_evtremun.recibo_numero,
    s1200_evtremun.recibo_hash,
    's1200_evtremun_recibo'::text AS url_recibo,
    s1200_evtremun.processamento_codigo_resposta,
    s1200_evtremun.processamento_descricao_resposta,
    s1200_evtremun.validacao_precedencia,
    s1200_evtremun.validacoes,
    s1200_evtremun.status,
    s1200_evtremun.retornos_eventos_id,
    s1200_evtremun.ocorrencias
   FROM s1200_evtremun
  WHERE s1200_evtremun.excluido = false
UNION
 SELECT s1202_evtrmnrpps.id,
    's1202'::text AS evento,
    s1202_evtrmnrpps.identidade,
    s1202_evtrmnrpps.transmissor_lote_esocial_id,
    s1202_evtrmnrpps.criado_em,
    s1202_evtrmnrpps.criado_por_id,
    s1202_evtrmnrpps.modificado_em,
    s1202_evtrmnrpps.modificado_por_id,
    s1202_evtrmnrpps.excluido,
    3 AS grupo,
    's1202_evtrmnrpps'::text AS tabela,
    's1202_evtrmnrpps_salvar'::text AS tabela_salvar,
    s1202_evtrmnrpps.id AS ordem,
    s1202_evtrmnrpps.tpinsc,
    s1202_evtrmnrpps.nrinsc,
    s1202_evtrmnrpps.recibo_numero,
    s1202_evtrmnrpps.recibo_hash,
    's1202_evtrmnrpps_recibo'::text AS url_recibo,
    s1202_evtrmnrpps.processamento_codigo_resposta,
    s1202_evtrmnrpps.processamento_descricao_resposta,
    s1202_evtrmnrpps.validacao_precedencia,
    s1202_evtrmnrpps.validacoes,
    s1202_evtrmnrpps.status,
    s1202_evtrmnrpps.retornos_eventos_id,
    s1202_evtrmnrpps.ocorrencias
   FROM s1202_evtrmnrpps
  WHERE s1202_evtrmnrpps.excluido = false
UNION
 SELECT s1207_evtbenprrp.id,
    's1207'::text AS evento,
    s1207_evtbenprrp.identidade,
    s1207_evtbenprrp.transmissor_lote_esocial_id,
    s1207_evtbenprrp.criado_em,
    s1207_evtbenprrp.criado_por_id,
    s1207_evtbenprrp.modificado_em,
    s1207_evtbenprrp.modificado_por_id,
    s1207_evtbenprrp.excluido,
    3 AS grupo,
    's1207_evtbenprrp'::text AS tabela,
    's1207_evtbenprrp_salvar'::text AS tabela_salvar,
    s1207_evtbenprrp.id AS ordem,
    s1207_evtbenprrp.tpinsc,
    s1207_evtbenprrp.nrinsc,
    s1207_evtbenprrp.recibo_numero,
    s1207_evtbenprrp.recibo_hash,
    's1207_evtbenprrp_recibo'::text AS url_recibo,
    s1207_evtbenprrp.processamento_codigo_resposta,
    s1207_evtbenprrp.processamento_descricao_resposta,
    s1207_evtbenprrp.validacao_precedencia,
    s1207_evtbenprrp.validacoes,
    s1207_evtbenprrp.status,
    s1207_evtbenprrp.retornos_eventos_id,
    s1207_evtbenprrp.ocorrencias
   FROM s1207_evtbenprrp
  WHERE s1207_evtbenprrp.excluido = false
UNION
 SELECT s1210_evtpgtos.id,
    's1210'::text AS evento,
    s1210_evtpgtos.identidade,
    s1210_evtpgtos.transmissor_lote_esocial_id,
    s1210_evtpgtos.criado_em,
    s1210_evtpgtos.criado_por_id,
    s1210_evtpgtos.modificado_em,
    s1210_evtpgtos.modificado_por_id,
    s1210_evtpgtos.excluido,
    3 AS grupo,
    's1210_evtpgtos'::text AS tabela,
    's1210_evtpgtos_salvar'::text AS tabela_salvar,
    s1210_evtpgtos.id AS ordem,
    s1210_evtpgtos.tpinsc,
    s1210_evtpgtos.nrinsc,
    s1210_evtpgtos.recibo_numero,
    s1210_evtpgtos.recibo_hash,
    's1210_evtpgtos_recibo'::text AS url_recibo,
    s1210_evtpgtos.processamento_codigo_resposta,
    s1210_evtpgtos.processamento_descricao_resposta,
    s1210_evtpgtos.validacao_precedencia,
    s1210_evtpgtos.validacoes,
    s1210_evtpgtos.status,
    s1210_evtpgtos.retornos_eventos_id,
    s1210_evtpgtos.ocorrencias
   FROM s1210_evtpgtos
  WHERE s1210_evtpgtos.excluido = false
UNION
 SELECT s1250_evtaqprod.id,
    's1250'::text AS evento,
    s1250_evtaqprod.identidade,
    s1250_evtaqprod.transmissor_lote_esocial_id,
    s1250_evtaqprod.criado_em,
    s1250_evtaqprod.criado_por_id,
    s1250_evtaqprod.modificado_em,
    s1250_evtaqprod.modificado_por_id,
    s1250_evtaqprod.excluido,
    3 AS grupo,
    's1250_evtaqprod'::text AS tabela,
    's1250_evtaqprod_salvar'::text AS tabela_salvar,
    s1250_evtaqprod.id AS ordem,
    s1250_evtaqprod.tpinsc,
    s1250_evtaqprod.nrinsc,
    s1250_evtaqprod.recibo_numero,
    s1250_evtaqprod.recibo_hash,
    's1250_evtaqprod_recibo'::text AS url_recibo,
    s1250_evtaqprod.processamento_codigo_resposta,
    s1250_evtaqprod.processamento_descricao_resposta,
    s1250_evtaqprod.validacao_precedencia,
    s1250_evtaqprod.validacoes,
    s1250_evtaqprod.status,
    s1250_evtaqprod.retornos_eventos_id,
    s1250_evtaqprod.ocorrencias
   FROM s1250_evtaqprod
  WHERE s1250_evtaqprod.excluido = false
UNION
 SELECT s1260_evtcomprod.id,
    's1260'::text AS evento,
    s1260_evtcomprod.identidade,
    s1260_evtcomprod.transmissor_lote_esocial_id,
    s1260_evtcomprod.criado_em,
    s1260_evtcomprod.criado_por_id,
    s1260_evtcomprod.modificado_em,
    s1260_evtcomprod.modificado_por_id,
    s1260_evtcomprod.excluido,
    3 AS grupo,
    's1260_evtcomprod'::text AS tabela,
    's1260_evtcomprod_salvar'::text AS tabela_salvar,
    s1260_evtcomprod.id AS ordem,
    s1260_evtcomprod.tpinsc,
    s1260_evtcomprod.nrinsc,
    s1260_evtcomprod.recibo_numero,
    s1260_evtcomprod.recibo_hash,
    's1260_evtcomprod_recibo'::text AS url_recibo,
    s1260_evtcomprod.processamento_codigo_resposta,
    s1260_evtcomprod.processamento_descricao_resposta,
    s1260_evtcomprod.validacao_precedencia,
    s1260_evtcomprod.validacoes,
    s1260_evtcomprod.status,
    s1260_evtcomprod.retornos_eventos_id,
    s1260_evtcomprod.ocorrencias
   FROM s1260_evtcomprod
  WHERE s1260_evtcomprod.excluido = false
UNION
 SELECT s1270_evtcontratavnp.id,
    's1270'::text AS evento,
    s1270_evtcontratavnp.identidade,
    s1270_evtcontratavnp.transmissor_lote_esocial_id,
    s1270_evtcontratavnp.criado_em,
    s1270_evtcontratavnp.criado_por_id,
    s1270_evtcontratavnp.modificado_em,
    s1270_evtcontratavnp.modificado_por_id,
    s1270_evtcontratavnp.excluido,
    3 AS grupo,
    's1270_evtcontratavnp'::text AS tabela,
    's1270_evtcontratavnp_salvar'::text AS tabela_salvar,
    s1270_evtcontratavnp.id AS ordem,
    s1270_evtcontratavnp.tpinsc,
    s1270_evtcontratavnp.nrinsc,
    s1270_evtcontratavnp.recibo_numero,
    s1270_evtcontratavnp.recibo_hash,
    's1270_evtcontratavnp_recibo'::text AS url_recibo,
    s1270_evtcontratavnp.processamento_codigo_resposta,
    s1270_evtcontratavnp.processamento_descricao_resposta,
    s1270_evtcontratavnp.validacao_precedencia,
    s1270_evtcontratavnp.validacoes,
    s1270_evtcontratavnp.status,
    s1270_evtcontratavnp.retornos_eventos_id,
    s1270_evtcontratavnp.ocorrencias
   FROM s1270_evtcontratavnp
  WHERE s1270_evtcontratavnp.excluido = false
UNION
 SELECT s1280_evtinfocomplper.id,
    's1280'::text AS evento,
    s1280_evtinfocomplper.identidade,
    s1280_evtinfocomplper.transmissor_lote_esocial_id,
    s1280_evtinfocomplper.criado_em,
    s1280_evtinfocomplper.criado_por_id,
    s1280_evtinfocomplper.modificado_em,
    s1280_evtinfocomplper.modificado_por_id,
    s1280_evtinfocomplper.excluido,
    3 AS grupo,
    's1280_evtinfocomplper'::text AS tabela,
    's1280_evtinfocomplper_salvar'::text AS tabela_salvar,
    s1280_evtinfocomplper.id AS ordem,
    s1280_evtinfocomplper.tpinsc,
    s1280_evtinfocomplper.nrinsc,
    s1280_evtinfocomplper.recibo_numero,
    s1280_evtinfocomplper.recibo_hash,
    's1280_evtinfocomplper_recibo'::text AS url_recibo,
    s1280_evtinfocomplper.processamento_codigo_resposta,
    s1280_evtinfocomplper.processamento_descricao_resposta,
    s1280_evtinfocomplper.validacao_precedencia,
    s1280_evtinfocomplper.validacoes,
    s1280_evtinfocomplper.status,
    s1280_evtinfocomplper.retornos_eventos_id,
    s1280_evtinfocomplper.ocorrencias
   FROM s1280_evtinfocomplper
  WHERE s1280_evtinfocomplper.excluido = false
UNION
 SELECT s1295_evttotconting.id,
    's1295'::text AS evento,
    s1295_evttotconting.identidade,
    s1295_evttotconting.transmissor_lote_esocial_id,
    s1295_evttotconting.criado_em,
    s1295_evttotconting.criado_por_id,
    s1295_evttotconting.modificado_em,
    s1295_evttotconting.modificado_por_id,
    s1295_evttotconting.excluido,
    3 AS grupo,
    's1295_evttotconting'::text AS tabela,
    's1295_evttotconting_salvar'::text AS tabela_salvar,
    s1295_evttotconting.id AS ordem,
    s1295_evttotconting.tpinsc,
    s1295_evttotconting.nrinsc,
    s1295_evttotconting.recibo_numero,
    s1295_evttotconting.recibo_hash,
    's1295_evttotconting_recibo'::text AS url_recibo,
    s1295_evttotconting.processamento_codigo_resposta,
    s1295_evttotconting.processamento_descricao_resposta,
    s1295_evttotconting.validacao_precedencia,
    s1295_evttotconting.validacoes,
    s1295_evttotconting.status,
    s1295_evttotconting.retornos_eventos_id,
    s1295_evttotconting.ocorrencias
   FROM s1295_evttotconting
  WHERE s1295_evttotconting.excluido = false
UNION
 SELECT s1298_evtreabreevper.id,
    's1298'::text AS evento,
    s1298_evtreabreevper.identidade,
    s1298_evtreabreevper.transmissor_lote_esocial_id,
    s1298_evtreabreevper.criado_em,
    s1298_evtreabreevper.criado_por_id,
    s1298_evtreabreevper.modificado_em,
    s1298_evtreabreevper.modificado_por_id,
    s1298_evtreabreevper.excluido,
    3 AS grupo,
    's1298_evtreabreevper'::text AS tabela,
    's1298_evtreabreevper_salvar'::text AS tabela_salvar,
    s1298_evtreabreevper.id AS ordem,
    s1298_evtreabreevper.tpinsc,
    s1298_evtreabreevper.nrinsc,
    s1298_evtreabreevper.recibo_numero,
    s1298_evtreabreevper.recibo_hash,
    's1298_evtreabreevper_recibo'::text AS url_recibo,
    s1298_evtreabreevper.processamento_codigo_resposta,
    s1298_evtreabreevper.processamento_descricao_resposta,
    s1298_evtreabreevper.validacao_precedencia,
    s1298_evtreabreevper.validacoes,
    s1298_evtreabreevper.status,
    s1298_evtreabreevper.retornos_eventos_id,
    s1298_evtreabreevper.ocorrencias
   FROM s1298_evtreabreevper
  WHERE s1298_evtreabreevper.excluido = false
UNION
 SELECT s1299_evtfechaevper.id,
    's1299'::text AS evento,
    s1299_evtfechaevper.identidade,
    s1299_evtfechaevper.transmissor_lote_esocial_id,
    s1299_evtfechaevper.criado_em,
    s1299_evtfechaevper.criado_por_id,
    s1299_evtfechaevper.modificado_em,
    s1299_evtfechaevper.modificado_por_id,
    s1299_evtfechaevper.excluido,
    3 AS grupo,
    's1299_evtfechaevper'::text AS tabela,
    's1299_evtfechaevper_salvar'::text AS tabela_salvar,
    s1299_evtfechaevper.id AS ordem,
    s1299_evtfechaevper.tpinsc,
    s1299_evtfechaevper.nrinsc,
    s1299_evtfechaevper.recibo_numero,
    s1299_evtfechaevper.recibo_hash,
    's1299_evtfechaevper_recibo'::text AS url_recibo,
    s1299_evtfechaevper.processamento_codigo_resposta,
    s1299_evtfechaevper.processamento_descricao_resposta,
    s1299_evtfechaevper.validacao_precedencia,
    s1299_evtfechaevper.validacoes,
    s1299_evtfechaevper.status,
    s1299_evtfechaevper.retornos_eventos_id,
    s1299_evtfechaevper.ocorrencias
   FROM s1299_evtfechaevper
  WHERE s1299_evtfechaevper.excluido = false
UNION
 SELECT s1300_evtcontrsindpatr.id,
    's1300'::text AS evento,
    s1300_evtcontrsindpatr.identidade,
    s1300_evtcontrsindpatr.transmissor_lote_esocial_id,
    s1300_evtcontrsindpatr.criado_em,
    s1300_evtcontrsindpatr.criado_por_id,
    s1300_evtcontrsindpatr.modificado_em,
    s1300_evtcontrsindpatr.modificado_por_id,
    s1300_evtcontrsindpatr.excluido,
    3 AS grupo,
    's1300_evtcontrsindpatr'::text AS tabela,
    's1300_evtcontrsindpatr_salvar'::text AS tabela_salvar,
    s1300_evtcontrsindpatr.id AS ordem,
    s1300_evtcontrsindpatr.tpinsc,
    s1300_evtcontrsindpatr.nrinsc,
    s1300_evtcontrsindpatr.recibo_numero,
    s1300_evtcontrsindpatr.recibo_hash,
    's1300_evtcontrsindpatr_recibo'::text AS url_recibo,
    s1300_evtcontrsindpatr.processamento_codigo_resposta,
    s1300_evtcontrsindpatr.processamento_descricao_resposta,
    s1300_evtcontrsindpatr.validacao_precedencia,
    s1300_evtcontrsindpatr.validacoes,
    s1300_evtcontrsindpatr.status,
    s1300_evtcontrsindpatr.retornos_eventos_id,
    s1300_evtcontrsindpatr.ocorrencias
   FROM s1300_evtcontrsindpatr
  WHERE s1300_evtcontrsindpatr.excluido = false
UNION
 SELECT s2190_evtadmprelim.id,
    's2190'::text AS evento,
    s2190_evtadmprelim.identidade,
    s2190_evtadmprelim.transmissor_lote_esocial_id,
    s2190_evtadmprelim.criado_em,
    s2190_evtadmprelim.criado_por_id,
    s2190_evtadmprelim.modificado_em,
    s2190_evtadmprelim.modificado_por_id,
    s2190_evtadmprelim.excluido,
    2 AS grupo,
    's2190_evtadmprelim'::text AS tabela,
    's2190_evtadmprelim_salvar'::text AS tabela_salvar,
    s2190_evtadmprelim.id AS ordem,
    s2190_evtadmprelim.tpinsc,
    s2190_evtadmprelim.nrinsc,
    s2190_evtadmprelim.recibo_numero,
    s2190_evtadmprelim.recibo_hash,
    's2190_evtadmprelim_recibo'::text AS url_recibo,
    s2190_evtadmprelim.processamento_codigo_resposta,
    s2190_evtadmprelim.processamento_descricao_resposta,
    s2190_evtadmprelim.validacao_precedencia,
    s2190_evtadmprelim.validacoes,
    s2190_evtadmprelim.status,
    s2190_evtadmprelim.retornos_eventos_id,
    s2190_evtadmprelim.ocorrencias
   FROM s2190_evtadmprelim
  WHERE s2190_evtadmprelim.excluido = false
UNION
 SELECT s2200_evtadmissao.id,
    's2200'::text AS evento,
    s2200_evtadmissao.identidade,
    s2200_evtadmissao.transmissor_lote_esocial_id,
    s2200_evtadmissao.criado_em,
    s2200_evtadmissao.criado_por_id,
    s2200_evtadmissao.modificado_em,
    s2200_evtadmissao.modificado_por_id,
    s2200_evtadmissao.excluido,
    2 AS grupo,
    's2200_evtadmissao'::text AS tabela,
    's2200_evtadmissao_salvar'::text AS tabela_salvar,
    s2200_evtadmissao.id AS ordem,
    s2200_evtadmissao.tpinsc,
    s2200_evtadmissao.nrinsc,
    s2200_evtadmissao.recibo_numero,
    s2200_evtadmissao.recibo_hash,
    's2200_evtadmissao_recibo'::text AS url_recibo,
    s2200_evtadmissao.processamento_codigo_resposta,
    s2200_evtadmissao.processamento_descricao_resposta,
    s2200_evtadmissao.validacao_precedencia,
    s2200_evtadmissao.validacoes,
    s2200_evtadmissao.status,
    s2200_evtadmissao.retornos_eventos_id,
    s2200_evtadmissao.ocorrencias
   FROM s2200_evtadmissao
  WHERE s2200_evtadmissao.excluido = false
UNION
 SELECT s2205_evtaltcadastral.id,
    's2205'::text AS evento,
    s2205_evtaltcadastral.identidade,
    s2205_evtaltcadastral.transmissor_lote_esocial_id,
    s2205_evtaltcadastral.criado_em,
    s2205_evtaltcadastral.criado_por_id,
    s2205_evtaltcadastral.modificado_em,
    s2205_evtaltcadastral.modificado_por_id,
    s2205_evtaltcadastral.excluido,
    2 AS grupo,
    's2205_evtaltcadastral'::text AS tabela,
    's2205_evtaltcadastral_salvar'::text AS tabela_salvar,
    s2205_evtaltcadastral.id AS ordem,
    s2205_evtaltcadastral.tpinsc,
    s2205_evtaltcadastral.nrinsc,
    s2205_evtaltcadastral.recibo_numero,
    s2205_evtaltcadastral.recibo_hash,
    's2205_evtaltcadastral_recibo'::text AS url_recibo,
    s2205_evtaltcadastral.processamento_codigo_resposta,
    s2205_evtaltcadastral.processamento_descricao_resposta,
    s2205_evtaltcadastral.validacao_precedencia,
    s2205_evtaltcadastral.validacoes,
    s2205_evtaltcadastral.status,
    s2205_evtaltcadastral.retornos_eventos_id,
    s2205_evtaltcadastral.ocorrencias
   FROM s2205_evtaltcadastral
  WHERE s2205_evtaltcadastral.excluido = false
UNION
 SELECT s2206_evtaltcontratual.id,
    's2206'::text AS evento,
    s2206_evtaltcontratual.identidade,
    s2206_evtaltcontratual.transmissor_lote_esocial_id,
    s2206_evtaltcontratual.criado_em,
    s2206_evtaltcontratual.criado_por_id,
    s2206_evtaltcontratual.modificado_em,
    s2206_evtaltcontratual.modificado_por_id,
    s2206_evtaltcontratual.excluido,
    2 AS grupo,
    's2206_evtaltcontratual'::text AS tabela,
    's2206_evtaltcontratual_salvar'::text AS tabela_salvar,
    s2206_evtaltcontratual.id AS ordem,
    s2206_evtaltcontratual.tpinsc,
    s2206_evtaltcontratual.nrinsc,
    s2206_evtaltcontratual.recibo_numero,
    s2206_evtaltcontratual.recibo_hash,
    's2206_evtaltcontratual_recibo'::text AS url_recibo,
    s2206_evtaltcontratual.processamento_codigo_resposta,
    s2206_evtaltcontratual.processamento_descricao_resposta,
    s2206_evtaltcontratual.validacao_precedencia,
    s2206_evtaltcontratual.validacoes,
    s2206_evtaltcontratual.status,
    s2206_evtaltcontratual.retornos_eventos_id,
    s2206_evtaltcontratual.ocorrencias
   FROM s2206_evtaltcontratual
  WHERE s2206_evtaltcontratual.excluido = false
UNION
 SELECT s2210_evtcat.id,
    's2210'::text AS evento,
    s2210_evtcat.identidade,
    s2210_evtcat.transmissor_lote_esocial_id,
    s2210_evtcat.criado_em,
    s2210_evtcat.criado_por_id,
    s2210_evtcat.modificado_em,
    s2210_evtcat.modificado_por_id,
    s2210_evtcat.excluido,
    2 AS grupo,
    's2210_evtcat'::text AS tabela,
    's2210_evtcat_salvar'::text AS tabela_salvar,
    s2210_evtcat.id AS ordem,
    s2210_evtcat.tpinsc,
    s2210_evtcat.nrinsc,
    s2210_evtcat.recibo_numero,
    s2210_evtcat.recibo_hash,
    's2210_evtcat_recibo'::text AS url_recibo,
    s2210_evtcat.processamento_codigo_resposta,
    s2210_evtcat.processamento_descricao_resposta,
    s2210_evtcat.validacao_precedencia,
    s2210_evtcat.validacoes,
    s2210_evtcat.status,
    s2210_evtcat.retornos_eventos_id,
    s2210_evtcat.ocorrencias
   FROM s2210_evtcat
  WHERE s2210_evtcat.excluido = false
UNION
 SELECT s2220_evtmonit.id,
    's2220'::text AS evento,
    s2220_evtmonit.identidade,
    s2220_evtmonit.transmissor_lote_esocial_id,
    s2220_evtmonit.criado_em,
    s2220_evtmonit.criado_por_id,
    s2220_evtmonit.modificado_em,
    s2220_evtmonit.modificado_por_id,
    s2220_evtmonit.excluido,
    2 AS grupo,
    's2220_evtmonit'::text AS tabela,
    's2220_evtmonit_salvar'::text AS tabela_salvar,
    s2220_evtmonit.id AS ordem,
    s2220_evtmonit.tpinsc,
    s2220_evtmonit.nrinsc,
    s2220_evtmonit.recibo_numero,
    s2220_evtmonit.recibo_hash,
    's2220_evtmonit_recibo'::text AS url_recibo,
    s2220_evtmonit.processamento_codigo_resposta,
    s2220_evtmonit.processamento_descricao_resposta,
    s2220_evtmonit.validacao_precedencia,
    s2220_evtmonit.validacoes,
    s2220_evtmonit.status,
    s2220_evtmonit.retornos_eventos_id,
    s2220_evtmonit.ocorrencias
   FROM s2220_evtmonit
  WHERE s2220_evtmonit.excluido = false
UNION
 SELECT s2230_evtafasttemp.id,
    's2230'::text AS evento,
    s2230_evtafasttemp.identidade,
    s2230_evtafasttemp.transmissor_lote_esocial_id,
    s2230_evtafasttemp.criado_em,
    s2230_evtafasttemp.criado_por_id,
    s2230_evtafasttemp.modificado_em,
    s2230_evtafasttemp.modificado_por_id,
    s2230_evtafasttemp.excluido,
    2 AS grupo,
    's2230_evtafasttemp'::text AS tabela,
    's2230_evtafasttemp_salvar'::text AS tabela_salvar,
    s2230_evtafasttemp.id AS ordem,
    s2230_evtafasttemp.tpinsc,
    s2230_evtafasttemp.nrinsc,
    s2230_evtafasttemp.recibo_numero,
    s2230_evtafasttemp.recibo_hash,
    's2230_evtafasttemp_recibo'::text AS url_recibo,
    s2230_evtafasttemp.processamento_codigo_resposta,
    s2230_evtafasttemp.processamento_descricao_resposta,
    s2230_evtafasttemp.validacao_precedencia,
    s2230_evtafasttemp.validacoes,
    s2230_evtafasttemp.status,
    s2230_evtafasttemp.retornos_eventos_id,
    s2230_evtafasttemp.ocorrencias
   FROM s2230_evtafasttemp
  WHERE s2230_evtafasttemp.excluido = false
UNION
 SELECT s2240_evtexprisco.id,
    's2240'::text AS evento,
    s2240_evtexprisco.identidade,
    s2240_evtexprisco.transmissor_lote_esocial_id,
    s2240_evtexprisco.criado_em,
    s2240_evtexprisco.criado_por_id,
    s2240_evtexprisco.modificado_em,
    s2240_evtexprisco.modificado_por_id,
    s2240_evtexprisco.excluido,
    2 AS grupo,
    's2240_evtexprisco'::text AS tabela,
    's2240_evtexprisco_salvar'::text AS tabela_salvar,
    s2240_evtexprisco.id AS ordem,
    s2240_evtexprisco.tpinsc,
    s2240_evtexprisco.nrinsc,
    s2240_evtexprisco.recibo_numero,
    s2240_evtexprisco.recibo_hash,
    's2240_evtexprisco_recibo'::text AS url_recibo,
    s2240_evtexprisco.processamento_codigo_resposta,
    s2240_evtexprisco.processamento_descricao_resposta,
    s2240_evtexprisco.validacao_precedencia,
    s2240_evtexprisco.validacoes,
    s2240_evtexprisco.status,
    s2240_evtexprisco.retornos_eventos_id,
    s2240_evtexprisco.ocorrencias
   FROM s2240_evtexprisco
  WHERE s2240_evtexprisco.excluido = false
UNION
 SELECT s2241_evtinsapo.id,
    's2241'::text AS evento,
    s2241_evtinsapo.identidade,
    s2241_evtinsapo.transmissor_lote_esocial_id,
    s2241_evtinsapo.criado_em,
    s2241_evtinsapo.criado_por_id,
    s2241_evtinsapo.modificado_em,
    s2241_evtinsapo.modificado_por_id,
    s2241_evtinsapo.excluido,
    2 AS grupo,
    's2241_evtinsapo'::text AS tabela,
    's2241_evtinsapo_salvar'::text AS tabela_salvar,
    s2241_evtinsapo.id AS ordem,
    s2241_evtinsapo.tpinsc,
    s2241_evtinsapo.nrinsc,
    s2241_evtinsapo.recibo_numero,
    s2241_evtinsapo.recibo_hash,
    's2241_evtinsapo_recibo'::text AS url_recibo,
    s2241_evtinsapo.processamento_codigo_resposta,
    s2241_evtinsapo.processamento_descricao_resposta,
    s2241_evtinsapo.validacao_precedencia,
    s2241_evtinsapo.validacoes,
    s2241_evtinsapo.status,
    s2241_evtinsapo.retornos_eventos_id,
    s2241_evtinsapo.ocorrencias
   FROM s2241_evtinsapo
  WHERE s2241_evtinsapo.excluido = false
UNION
 SELECT s2250_evtavprevio.id,
    's2250'::text AS evento,
    s2250_evtavprevio.identidade,
    s2250_evtavprevio.transmissor_lote_esocial_id,
    s2250_evtavprevio.criado_em,
    s2250_evtavprevio.criado_por_id,
    s2250_evtavprevio.modificado_em,
    s2250_evtavprevio.modificado_por_id,
    s2250_evtavprevio.excluido,
    2 AS grupo,
    's2250_evtavprevio'::text AS tabela,
    's2250_evtavprevio_salvar'::text AS tabela_salvar,
    s2250_evtavprevio.id AS ordem,
    s2250_evtavprevio.tpinsc,
    s2250_evtavprevio.nrinsc,
    s2250_evtavprevio.recibo_numero,
    s2250_evtavprevio.recibo_hash,
    's2250_evtavprevio_recibo'::text AS url_recibo,
    s2250_evtavprevio.processamento_codigo_resposta,
    s2250_evtavprevio.processamento_descricao_resposta,
    s2250_evtavprevio.validacao_precedencia,
    s2250_evtavprevio.validacoes,
    s2250_evtavprevio.status,
    s2250_evtavprevio.retornos_eventos_id,
    s2250_evtavprevio.ocorrencias
   FROM s2250_evtavprevio
  WHERE s2250_evtavprevio.excluido = false
UNION
 SELECT s2260_evtconvinterm.id,
    's2260'::text AS evento,
    s2260_evtconvinterm.identidade,
    s2260_evtconvinterm.transmissor_lote_esocial_id,
    s2260_evtconvinterm.criado_em,
    s2260_evtconvinterm.criado_por_id,
    s2260_evtconvinterm.modificado_em,
    s2260_evtconvinterm.modificado_por_id,
    s2260_evtconvinterm.excluido,
    2 AS grupo,
    's2260_evtconvinterm'::text AS tabela,
    's2260_evtconvinterm_salvar'::text AS tabela_salvar,
    s2260_evtconvinterm.id AS ordem,
    s2260_evtconvinterm.tpinsc,
    s2260_evtconvinterm.nrinsc,
    s2260_evtconvinterm.recibo_numero,
    s2260_evtconvinterm.recibo_hash,
    's2260_evtconvinterm_recibo'::text AS url_recibo,
    s2260_evtconvinterm.processamento_codigo_resposta,
    s2260_evtconvinterm.processamento_descricao_resposta,
    s2260_evtconvinterm.validacao_precedencia,
    s2260_evtconvinterm.validacoes,
    s2260_evtconvinterm.status,
    s2260_evtconvinterm.retornos_eventos_id,
    s2260_evtconvinterm.ocorrencias
   FROM s2260_evtconvinterm
  WHERE s2260_evtconvinterm.excluido = false
UNION
 SELECT s2298_evtreintegr.id,
    's2298'::text AS evento,
    s2298_evtreintegr.identidade,
    s2298_evtreintegr.transmissor_lote_esocial_id,
    s2298_evtreintegr.criado_em,
    s2298_evtreintegr.criado_por_id,
    s2298_evtreintegr.modificado_em,
    s2298_evtreintegr.modificado_por_id,
    s2298_evtreintegr.excluido,
    2 AS grupo,
    's2298_evtreintegr'::text AS tabela,
    's2298_evtreintegr_salvar'::text AS tabela_salvar,
    s2298_evtreintegr.id AS ordem,
    s2298_evtreintegr.tpinsc,
    s2298_evtreintegr.nrinsc,
    s2298_evtreintegr.recibo_numero,
    s2298_evtreintegr.recibo_hash,
    's2298_evtreintegr_recibo'::text AS url_recibo,
    s2298_evtreintegr.processamento_codigo_resposta,
    s2298_evtreintegr.processamento_descricao_resposta,
    s2298_evtreintegr.validacao_precedencia,
    s2298_evtreintegr.validacoes,
    s2298_evtreintegr.status,
    s2298_evtreintegr.retornos_eventos_id,
    s2298_evtreintegr.ocorrencias
   FROM s2298_evtreintegr
  WHERE s2298_evtreintegr.excluido = false
UNION
 SELECT s2299_evtdeslig.id,
    's2299'::text AS evento,
    s2299_evtdeslig.identidade,
    s2299_evtdeslig.transmissor_lote_esocial_id,
    s2299_evtdeslig.criado_em,
    s2299_evtdeslig.criado_por_id,
    s2299_evtdeslig.modificado_em,
    s2299_evtdeslig.modificado_por_id,
    s2299_evtdeslig.excluido,
    2 AS grupo,
    's2299_evtdeslig'::text AS tabela,
    's2299_evtdeslig_salvar'::text AS tabela_salvar,
    s2299_evtdeslig.id AS ordem,
    s2299_evtdeslig.tpinsc,
    s2299_evtdeslig.nrinsc,
    s2299_evtdeslig.recibo_numero,
    s2299_evtdeslig.recibo_hash,
    's2299_evtdeslig_recibo'::text AS url_recibo,
    s2299_evtdeslig.processamento_codigo_resposta,
    s2299_evtdeslig.processamento_descricao_resposta,
    s2299_evtdeslig.validacao_precedencia,
    s2299_evtdeslig.validacoes,
    s2299_evtdeslig.status,
    s2299_evtdeslig.retornos_eventos_id,
    s2299_evtdeslig.ocorrencias
   FROM s2299_evtdeslig
  WHERE s2299_evtdeslig.excluido = false
UNION
 SELECT s2300_evttsvinicio.id,
    's2300'::text AS evento,
    s2300_evttsvinicio.identidade,
    s2300_evttsvinicio.transmissor_lote_esocial_id,
    s2300_evttsvinicio.criado_em,
    s2300_evttsvinicio.criado_por_id,
    s2300_evttsvinicio.modificado_em,
    s2300_evttsvinicio.modificado_por_id,
    s2300_evttsvinicio.excluido,
    2 AS grupo,
    's2300_evttsvinicio'::text AS tabela,
    's2300_evttsvinicio_salvar'::text AS tabela_salvar,
    s2300_evttsvinicio.id AS ordem,
    s2300_evttsvinicio.tpinsc,
    s2300_evttsvinicio.nrinsc,
    s2300_evttsvinicio.recibo_numero,
    s2300_evttsvinicio.recibo_hash,
    's2300_evttsvinicio_recibo'::text AS url_recibo,
    s2300_evttsvinicio.processamento_codigo_resposta,
    s2300_evttsvinicio.processamento_descricao_resposta,
    s2300_evttsvinicio.validacao_precedencia,
    s2300_evttsvinicio.validacoes,
    s2300_evttsvinicio.status,
    s2300_evttsvinicio.retornos_eventos_id,
    s2300_evttsvinicio.ocorrencias
   FROM s2300_evttsvinicio
  WHERE s2300_evttsvinicio.excluido = false
UNION
 SELECT s2306_evttsvaltcontr.id,
    's2306'::text AS evento,
    s2306_evttsvaltcontr.identidade,
    s2306_evttsvaltcontr.transmissor_lote_esocial_id,
    s2306_evttsvaltcontr.criado_em,
    s2306_evttsvaltcontr.criado_por_id,
    s2306_evttsvaltcontr.modificado_em,
    s2306_evttsvaltcontr.modificado_por_id,
    s2306_evttsvaltcontr.excluido,
    2 AS grupo,
    's2306_evttsvaltcontr'::text AS tabela,
    's2306_evttsvaltcontr_salvar'::text AS tabela_salvar,
    s2306_evttsvaltcontr.id AS ordem,
    s2306_evttsvaltcontr.tpinsc,
    s2306_evttsvaltcontr.nrinsc,
    s2306_evttsvaltcontr.recibo_numero,
    s2306_evttsvaltcontr.recibo_hash,
    's2306_evttsvaltcontr_recibo'::text AS url_recibo,
    s2306_evttsvaltcontr.processamento_codigo_resposta,
    s2306_evttsvaltcontr.processamento_descricao_resposta,
    s2306_evttsvaltcontr.validacao_precedencia,
    s2306_evttsvaltcontr.validacoes,
    s2306_evttsvaltcontr.status,
    s2306_evttsvaltcontr.retornos_eventos_id,
    s2306_evttsvaltcontr.ocorrencias
   FROM s2306_evttsvaltcontr
  WHERE s2306_evttsvaltcontr.excluido = false
UNION
 SELECT s2399_evttsvtermino.id,
    's2399'::text AS evento,
    s2399_evttsvtermino.identidade,
    s2399_evttsvtermino.transmissor_lote_esocial_id,
    s2399_evttsvtermino.criado_em,
    s2399_evttsvtermino.criado_por_id,
    s2399_evttsvtermino.modificado_em,
    s2399_evttsvtermino.modificado_por_id,
    s2399_evttsvtermino.excluido,
    2 AS grupo,
    's2399_evttsvtermino'::text AS tabela,
    's2399_evttsvtermino_salvar'::text AS tabela_salvar,
    s2399_evttsvtermino.id AS ordem,
    s2399_evttsvtermino.tpinsc,
    s2399_evttsvtermino.nrinsc,
    s2399_evttsvtermino.recibo_numero,
    s2399_evttsvtermino.recibo_hash,
    's2399_evttsvtermino_recibo'::text AS url_recibo,
    s2399_evttsvtermino.processamento_codigo_resposta,
    s2399_evttsvtermino.processamento_descricao_resposta,
    s2399_evttsvtermino.validacao_precedencia,
    s2399_evttsvtermino.validacoes,
    s2399_evttsvtermino.status,
    s2399_evttsvtermino.retornos_eventos_id,
    s2399_evttsvtermino.ocorrencias
   FROM s2399_evttsvtermino
  WHERE s2399_evttsvtermino.excluido = false
UNION
 SELECT s3000_evtexclusao.id,
    's3000'::text AS evento,
    s3000_evtexclusao.identidade,
    s3000_evtexclusao.transmissor_lote_esocial_id,
    s3000_evtexclusao.criado_em,
    s3000_evtexclusao.criado_por_id,
    s3000_evtexclusao.modificado_em,
    s3000_evtexclusao.modificado_por_id,
    s3000_evtexclusao.excluido,
    2 AS grupo,
    's3000_evtexclusao'::text AS tabela,
    's3000_evtexclusao_salvar'::text AS tabela_salvar,
    s3000_evtexclusao.id AS ordem,
    s3000_evtexclusao.tpinsc,
    s3000_evtexclusao.nrinsc,
    s3000_evtexclusao.recibo_numero,
    s3000_evtexclusao.recibo_hash,
    's3000_evtexclusao_recibo'::text AS url_recibo,
    s3000_evtexclusao.processamento_codigo_resposta,
    s3000_evtexclusao.processamento_descricao_resposta,
    s3000_evtexclusao.validacao_precedencia,
    s3000_evtexclusao.validacoes,
    s3000_evtexclusao.status,
    s3000_evtexclusao.retornos_eventos_id,
    s3000_evtexclusao.ocorrencias
   FROM s3000_evtexclusao
  WHERE s3000_evtexclusao.excluido = false;


  CREATE OR REPLACE VIEW public.transmissor_eventos_esocial_totalizacoes AS 
 SELECT s5001_evtbasestrab.id,
    's5001' AS evento,
    s5001_evtbasestrab.identidade,
    s5001_evtbasestrab.transmissor_lote_esocial_id,
    s5001_evtbasestrab.criado_em,
    s5001_evtbasestrab.criado_por_id,
    s5001_evtbasestrab.modificado_em,
    s5001_evtbasestrab.modificado_por_id,
    s5001_evtbasestrab.excluido,
    2 AS grupo,
    's5001_evtbasestrab' AS tabela,
    's5001_evtbasestrab_salvar' AS tabela_salvar,
    s5001_evtbasestrab.id AS ordem,
    s5001_evtbasestrab.tpinsc,
    s5001_evtbasestrab.nrinsc,
    s5001_evtbasestrab.recibo_numero,
    s5001_evtbasestrab.recibo_hash,
    's5001_evtbasestrab_recibo' AS url_recibo,
    s5001_evtbasestrab.processamento_codigo_resposta,
    s5001_evtbasestrab.processamento_descricao_resposta,
    s5001_evtbasestrab.validacao_precedencia,
    s5001_evtbasestrab.validacoes,
    s5001_evtbasestrab.status
   FROM s5001_evtbasestrab
  WHERE s5001_evtbasestrab.excluido = false;        
        
        """)
    ]
