# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0003_auto_20180813_0952'),
        ('mensageiro', '0017_auto_20180819_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetornosEventos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('recepcao_tp_amb', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('recepcao_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recepcao_versao_app', models.CharField(max_length=30, null=True, blank=True)),
                ('recepcao_protocolo_envio_lote', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_codigo_resposta', models.IntegerField(blank=True, null=True, choices=[(0, 'Cadastrado'), (101, '101 - Lote Aguardando Processamento'), (201, '201 - Lote Processado com Sucesso'), (202, '202 - Lote Processado com Advert\xeancias'), (301, '301 - Erro Servidor eSocial'), (401, '401 - Lote Incorreto - Erro preenchimento'), (402, '402 - Lote Incorreto - schema Inv\xe1lido'), (403, '403 - Lote Incorreto - Vers\xe3o do Schema n\xe3o permitida'), (404, '404 - Lote Incorreto - Erro Certificado'), (405, '405 - Lote Incorreto - Lote nulo ou vazio'), (501, '501 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Preenchimento'), (502, '502 - Solicita\xe7\xe3o de Consulta Incorreta - Schema Inv\xe1lido.'), (503, '503 - Solicita\xe7\xe3o de Consulta Incorreta - Vers\xe3o do Schema N\xe3o Permitida.'), (504, '504 - Solicita\xe7\xe3o de Consulta Incorreta - Erro Certificado.'), (505, '505 - Solicita\xe7\xe3o de Consulta Incorreta - Consulta nula ou vazia.')])),
                ('processamento_descricao_resposta', models.TextField(null=True, blank=True)),
                ('processamento_versao_app_processamento', models.CharField(max_length=30, null=True, blank=True)),
                ('processamento_data_hora', models.DateTimeField(null=True, blank=True)),
                ('recibo_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('recibo_hash', models.CharField(max_length=100, null=True, blank=True)),
                ('tpinsc', models.IntegerField(blank=True, null=True, choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('nrinsc', models.CharField(max_length=15, null=True, blank=True)),
                ('cpftrab', models.CharField(max_length=11, null=True, blank=True)),
                ('nistrab', models.CharField(max_length=11, null=True, blank=True)),
                ('nmtrab', models.CharField(max_length=70, null=True, blank=True)),
                ('infocota', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('matricula', models.CharField(max_length=30, null=True, blank=True)),
                ('dtadm', models.DateField(null=True, blank=True)),
                ('tpregjor', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Submetidos a Hor\xe1rio de Trabalho (Cap. II da CLT)'), (2, '2 - Atividade Externa especificada no Inciso I do Art. 62 da CLT'), (3, '3 - Fun\xe7\xf5es especificadas no Inciso II do Art. 62 da CLT'), (4, '4 - Teletrabalho, previsto no Inciso III do Art. 62 da CLT')])),
                ('dtbase', models.IntegerField(null=True, blank=True)),
                ('cnpjsindcategprof', models.CharField(max_length=14, null=True, blank=True)),
                ('dtposse', models.DateField(null=True, blank=True)),
                ('dtexercicio', models.DateField(null=True, blank=True)),
                ('codcargo', models.CharField(max_length=30, null=True, blank=True)),
                ('nmcargo', models.CharField(max_length=100, null=True, blank=True)),
                ('codfuncao', models.CharField(max_length=30, null=True, blank=True)),
                ('dscfuncao', models.CharField(max_length=100, null=True, blank=True)),
                ('codcbo', models.CharField(max_length=6, null=True, blank=True)),
                ('codcateg', models.IntegerField(null=True, blank=True)),
                ('vrsalfx', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('undsalfixo', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Por Hora'), (2, '2 - Por Dia'), (3, '3 - Por Semana'), (4, '4 - Por Quinzena'), (5, '5 - Por M\xeas'), (6, '6 - Por Tarefa'), (7, '7 - N\xe3o aplic\xe1vel - sal\xe1rio exclusivamente vari\xe1vel')])),
                ('dscsalvar', models.CharField(max_length=255, null=True, blank=True)),
                ('tpcontr', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Prazo indeterminado'), (2, '2 - Prazo determinado')])),
                ('dtterm', models.DateField(null=True, blank=True)),
                ('clauassec', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('local_tpinsc', models.IntegerField(blank=True, null=True, choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)')])),
                ('local_nrinsc', models.CharField(max_length=15, null=True, blank=True)),
                ('local_cnae', models.IntegerField(null=True, blank=True)),
                ('qtdhrssem', models.DecimalField(max_length=4, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('tpjornada', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Jornada com hor\xe1rio di\xe1rio e folga fixos'), (2, '2 - Jornada 12 x 36 (12 horas de trabalho seguidas de 36 horas ininterruptas de descanso)'), (3, '3 - Jornada com hor\xe1rio di\xe1rio fixo e folga vari\xe1vel'), (9, '9 - Demais tipos de jornada')])),
                ('dsctpjorn', models.CharField(max_length=100, null=True, blank=True)),
                ('tmpparc', models.IntegerField(blank=True, null=True, choices=[(0, '0 - N\xe3o \xe9 contrato em tempo parcial'), (1, '1 - Limitado a 25 horas semanais'), (2, '2 - Limitado a 30 horas semanais'), (3, '3 - Limitado a 26 horas semanais')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['transmissor_lote_esocial', 'identidade'],
                'db_table': 'retornos_eventos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventosHorarios',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dia', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Segunda-Feira'), (2, '2 - Ter\xe7a-Feira'), (3, '3 - Quarta-Feira'), (4, '4 - Quinta-Feira'), (5, '5 - Sexta-Feira'), (6, '6 - S\xe1bado'), (7, '7 - Domingo'), (8, '8 - Dia vari\xe1vel')])),
                ('codhorcontrat', models.CharField(max_length=30, null=True, blank=True)),
                ('hrentr', models.CharField(max_length=4, null=True, blank=True)),
                ('hrsaida', models.CharField(max_length=4, null=True, blank=True)),
                ('durjornada', models.IntegerField(null=True, blank=True)),
                ('perhorflexivel', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventoshorarios_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventoshorarios_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_eventos', models.ForeignKey(related_name='retornoseventoshorarios_retornos_eventos', blank=True, to='mensageiro.RetornosEventos', null=True)),
            ],
            options={
                'db_table': 'retornos_eventos_horarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventosIntervalos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinterv', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Intervalo em Hor\xe1rio Fixo'), (2, '2 - Intervalo em Hor\xe1rio Vari\xe1vel')])),
                ('durinterv', models.IntegerField(null=True, blank=True)),
                ('iniinterv', models.CharField(max_length=4, null=True, blank=True)),
                ('terminterv', models.CharField(max_length=4, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventosintervalos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventosintervalos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_eventos_horarios', models.ForeignKey(related_name='retornoseventosintervalos_retornos_eventos_horarios', blank=True, to='mensageiro.RetornosEventosHorarios', null=True)),
            ],
            options={
                'db_table': 'retornos_eventos_intervalos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RetornosEventosOcorrencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Advert\xeancia')])),
                ('codigo', models.IntegerField()),
                ('descricao', models.TextField()),
                ('localizacao', models.TextField(max_length=30, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='retornoseventosocorrencias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='retornoseventosocorrencias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_eventos', models.ForeignKey(related_name='retornoseventosocorrencias_retornos_eventos', to='mensageiro.RetornosEventos')),
            ],
            options={
                'db_table': 'retornos_eventos_ocorrencias',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='transmissorloteefdreinf',
            name='status',
            field=models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')]),
        ),
        migrations.AlterField(
            model_name='transmissorloteesocial',
            name='status',
            field=models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')]),
        ),
        migrations.AddField(
            model_name='retornoseventos',
            name='transmissor_lote_esocial',
            field=models.ForeignKey(related_name='retornoseventos_transmissor_lote_esocial', to='mensageiro.TransmissorLoteEsocial'),
        ),
    ]
