# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0017_auto_20190204_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s1000evtinfoempregador',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1000evtinfoempregador',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1005evttabestab',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1005evttabestab',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1010evttabrubrica',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1010evttabrubrica',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1020evttablotacao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1020evttablotacao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1030evttabcargo',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1030evttabcargo',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1035evttabcarreira',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1035evttabcarreira',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1040evttabfuncao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1040evttabfuncao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1050evttabhortur',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1050evttabhortur',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1060evttabambiente',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1060evttabambiente',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1070evttabprocesso',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1070evttabprocesso',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1080evttaboperport',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1080evttaboperport',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1200evtremun',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1200evtremun',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1202evtrmnrpps',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1202evtrmnrpps',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1207evtbenprrp',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1207evtbenprrp',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1210evtpgtos',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1210evtpgtos',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1250evtaqprod',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1250evtaqprod',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1260evtcomprod',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1260evtcomprod',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1270evtcontratavnp',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1270evtcontratavnp',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1280evtinfocomplper',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1280evtinfocomplper',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1295evttotconting',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1295evttotconting',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1298evtreabreevper',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1298evtreabreevper',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1299evtfechaevper',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1299evtfechaevper',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s1300evtcontrsindpatr',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s1300evtcontrsindpatr',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2190evtadmprelim',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2190evtadmprelim',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2200evtadmissao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2200evtadmissao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2205evtaltcadastral',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2205evtaltcadastral',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2206evtaltcontratual',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2206evtaltcontratual',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2210evtcat',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2210evtcat',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2220evtmonit',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2220evtmonit',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2221evttoxic',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2221evttoxic',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2230evtafasttemp',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2230evtafasttemp',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2231evtcessao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2231evtcessao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2240evtexprisco',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2240evtexprisco',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2241evtinsapo',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2241evtinsapo',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2245evttreicap',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2245evttreicap',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2250evtavprevio',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2250evtavprevio',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2260evtconvinterm',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2260evtconvinterm',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2298evtreintegr',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2298evtreintegr',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2299evtdeslig',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2299evtdeslig',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300evttsvinicio',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300evttsvinicio',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2306evttsvaltcontr',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2306evttsvaltcontr',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2399evttsvtermino',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2399evttsvtermino',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenefin',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenefin',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2405evtcdbenefalt',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2405evtcdbenefalt',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2410evtcdbenin',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2410evtcdbenin',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2416evtcdbenalt',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2416evtcdbenalt',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2420evtcdbenterm',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2420evtcdbenterm',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s3000evtexclusao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s3000evtexclusao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s5001evtbasestrab',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s5001evtbasestrab',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s5002evtirrfbenef',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s5002evtirrfbenef',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s5003evtbasesfgts',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s5003evtbasesfgts',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s5011evtcs',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s5011evtcs',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s5012evtirrf',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s5012evtirrf',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s5013evtfgts',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s5013evtfgts',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='s1000evtinfoempregador',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1000evtinfoempregador',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1005evttabestab',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1005evttabestab',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1010evttabrubrica',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1010evttabrubrica',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1020evttablotacao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1020evttablotacao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1030evttabcargo',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1030evttabcargo',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1035evttabcarreira',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1035evttabcarreira',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040evttabfuncao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1040evttabfuncao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1050evttabhortur',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1050evttabhortur',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1060evttabambiente',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1060evttabambiente',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1070evttabprocesso',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1070evttabprocesso',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1080evttaboperport',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1080evttaboperport',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1200evtremun',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1200evtremun',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1202evtrmnrpps',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1202evtrmnrpps',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1207evtbenprrp',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1207evtbenprrp',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1210evtpgtos',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1210evtpgtos',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1250evtaqprod',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1250evtaqprod',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1260evtcomprod',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1260evtcomprod',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1270evtcontratavnp',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1270evtcontratavnp',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1280evtinfocomplper',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1280evtinfocomplper',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1295evttotconting',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1295evttotconting',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1298evtreabreevper',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1298evtreabreevper',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1299evtfechaevper',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1299evtfechaevper',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1300evtcontrsindpatr',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s1300evtcontrsindpatr',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2190evtadmprelim',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2190evtadmprelim',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2200evtadmissao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2200evtadmissao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2205evtaltcadastral',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2205evtaltcadastral',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2206evtaltcontratual',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2206evtaltcontratual',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2210evtcat',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2210evtcat',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2220evtmonit',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2220evtmonit',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2221evttoxic',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2221evttoxic',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230evtafasttemp',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2230evtafasttemp',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2231evtcessao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2231evtcessao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2240evtexprisco',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2240evtexprisco',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2241evtinsapo',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2241evtinsapo',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2245evttreicap',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2245evttreicap',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2250evtavprevio',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2250evtavprevio',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2260evtconvinterm',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2260evtconvinterm',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2298evtreintegr',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2298evtreintegr',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2299evtdeslig',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2299evtdeslig',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300evttsvinicio',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300evttsvinicio',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2306evttsvaltcontr',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2306evttsvaltcontr',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2399evttsvtermino',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2399evttsvtermino',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2400evtcdbenefin',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2400evtcdbenefin',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2405evtcdbenefalt',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2405evtcdbenefalt',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2410evtcdbenin',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2410evtcdbenin',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2416evtcdbenalt',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2416evtcdbenalt',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2420evtcdbenterm',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2420evtcdbenterm',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3000evtexclusao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3000evtexclusao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5001evtbasestrab',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5001evtbasestrab',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5002evtirrfbenef',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5002evtirrfbenef',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5003evtbasesfgts',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5003evtbasesfgts',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5011evtcs',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5011evtcs',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5012evtirrf',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5012evtirrf',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5013evtfgts',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s5013evtfgts',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
