# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-28 12:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0044_auto_20191223_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s1000evtinfoempregador',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1005evttabestab',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1010evttabrubrica',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1020evttablotacao',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1030evttabcargo',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1035evttabcarreira',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1040evttabfuncao',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1050evttabhortur',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1060evttabambiente',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1070evttabprocesso',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1080evttaboperport',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1200evtremun',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1202evtrmnrpps',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1207evtbenprrp',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1210evtpgtos',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1250evtaqprod',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1260evtcomprod',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1270evtcontratavnp',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1280evtinfocomplper',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1295evttotconting',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1298evtreabreevper',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1299evtfechaevper',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s1300evtcontrsindpatr',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2190evtadmprelim',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2200evtadmissao',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2205evtaltcadastral',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2206evtaltcontratual',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2210evtcat',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2220evtmonit',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2221evttoxic',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2230evtafasttemp',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2231evtcessao',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2240evtexprisco',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2241evtinsapo',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2245evttreicap',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2250evtavprevio',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2260evtconvinterm',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2298evtreintegr',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2299evtdeslig',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2300evttsvinicio',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2306evttsvaltcontr',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2399evttsvtermino',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2400evtcdbenefin',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2405evtcdbenefalt',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2410evtcdbenin',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2416evtcdbenalt',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s2420evtcdbenterm',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s3000evtexclusao',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s5001evtbasestrab',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s5002evtirrfbenef',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s5003evtbasesfgts',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s5011evtcs',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s5012evtirrf',
            name='retorno_json',
        ),
        migrations.RemoveField(
            model_name='s5013evtfgts',
            name='retorno_json',
        ),
        migrations.AddField(
            model_name='s1000evtinfoempregador',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1000evtinfoempregador',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1000evtinfoempregador',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1005evttabestab',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1005evttabestab',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1005evttabestab',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1010evttabrubrica',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1010evttabrubrica',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1010evttabrubrica',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1020evttablotacao',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1020evttablotacao',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1020evttablotacao',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1030evttabcargo',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1030evttabcargo',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1030evttabcargo',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1035evttabcarreira',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1035evttabcarreira',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1035evttabcarreira',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1040evttabfuncao',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1040evttabfuncao',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1040evttabfuncao',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1050evttabhortur',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1050evttabhortur',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1050evttabhortur',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1060evttabambiente',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1060evttabambiente',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1060evttabambiente',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1070evttabprocesso',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1070evttabprocesso',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1070evttabprocesso',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1080evttaboperport',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1080evttaboperport',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1080evttaboperport',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1200evtremun',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1200evtremun',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1200evtremun',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1202evtrmnrpps',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1202evtrmnrpps',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1202evtrmnrpps',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1207evtbenprrp',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1207evtbenprrp',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1207evtbenprrp',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1210evtpgtos',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1210evtpgtos',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1210evtpgtos',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1250evtaqprod',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1250evtaqprod',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1250evtaqprod',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1260evtcomprod',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1260evtcomprod',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1260evtcomprod',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1270evtcontratavnp',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1270evtcontratavnp',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1270evtcontratavnp',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1280evtinfocomplper',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1280evtinfocomplper',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1280evtinfocomplper',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1295evttotconting',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1295evttotconting',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1295evttotconting',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1298evtreabreevper',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1298evtreabreevper',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1298evtreabreevper',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1299evtfechaevper',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1299evtfechaevper',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1299evtfechaevper',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s1300evtcontrsindpatr',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s1300evtcontrsindpatr',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s1300evtcontrsindpatr',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2190evtadmprelim',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2190evtadmprelim',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2190evtadmprelim',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2200evtadmissao',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2200evtadmissao',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2200evtadmissao',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2205evtaltcadastral',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2205evtaltcadastral',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2205evtaltcadastral',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2206evtaltcontratual',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2206evtaltcontratual',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2206evtaltcontratual',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2210evtcat',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2220evtmonit',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2221evttoxic',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2221evttoxic',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2221evttoxic',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2230evtafasttemp',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2230evtafasttemp',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2230evtafasttemp',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2231evtcessao',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2231evtcessao',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2231evtcessao',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2240evtexprisco',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2240evtexprisco',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2240evtexprisco',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2241evtinsapo',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2241evtinsapo',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2241evtinsapo',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2245evttreicap',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2245evttreicap',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2245evttreicap',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2250evtavprevio',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2250evtavprevio',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2250evtavprevio',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2260evtconvinterm',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2260evtconvinterm',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2260evtconvinterm',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2298evtreintegr',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2298evtreintegr',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2298evtreintegr',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2299evtdeslig',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2299evtdeslig',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2299evtdeslig',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2300evttsvinicio',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2300evttsvinicio',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2300evttsvinicio',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2306evttsvaltcontr',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2306evttsvaltcontr',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2306evttsvaltcontr',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2399evttsvtermino',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2399evttsvtermino',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2399evttsvtermino',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2400evtcdbenefin',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2400evtcdbenefin',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2400evtcdbenefin',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2405evtcdbenefalt',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2405evtcdbenefalt',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2405evtcdbenefalt',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2410evtcdbenin',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2410evtcdbenin',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2410evtcdbenin',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2416evtcdbenalt',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2416evtcdbenalt',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2416evtcdbenalt',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s2420evtcdbenterm',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s2420evtcdbenterm',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s2420evtcdbenterm',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s3000evtexclusao',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s3000evtexclusao',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s3000evtexclusao',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s5001evtbasestrab',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s5001evtbasestrab',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s5001evtbasestrab',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s5002evtirrfbenef',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s5002evtirrfbenef',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s5002evtirrfbenef',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s5003evtbasesfgts',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s5003evtbasesfgts',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s5003evtbasesfgts',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s5011evtcs',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s5011evtcs',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s5011evtcs',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s5012evtirrf',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s5012evtirrf',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s5012evtirrf',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
        migrations.AddField(
            model_name='s5013evtfgts',
            name='evento_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'evento_json'),
        ),
        migrations.AddField(
            model_name='s5013evtfgts',
            name='retorno_consulta_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_consulta_json'),
        ),
        migrations.AddField(
            model_name='s5013evtfgts',
            name='retorno_envio_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'retorno_envio_json'),
        ),
    ]
