# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2245', '0002_auto_20181010_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s2245ideprofresp',
            options={'managed': True, 'ordering': ['s2245_infocomplem', 'nmprof', 'tpprof', 'formprof', 'codcbo', 'nacprof']},
        ),
        migrations.AddField(
            model_name='s2245ideprofresp',
            name='nacprof',
            field=models.IntegerField(choices=[(1, '1 - Brasileiro'), (2, '2 - Estrangeiro')], default=0),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='codcbo',
            field=models.CharField(default=b'A', max_length=6),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='cpfprof',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='formprof',
            field=models.CharField(default=b'A', max_length=255),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='nmprof',
            field=models.CharField(default=b'A', max_length=70),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='s2245_infocomplem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2245ideprofresp_s2245_infocomplem', to='s2245.s2245infoComplem'),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='tpprof',
            field=models.IntegerField(choices=[(1, '1 - Profissional empregado do declarante'), (2, '2 - Profissional sem v\xednculo de emprego/estatut\xe1rio com o declarante')], default=0),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='criado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='dttreicap',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='durtreicap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, max_length=6),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='modtreicap',
            field=models.IntegerField(choices=[(1, '1 - Presencial'), (2, '2 - Educa\xe7\xe3o a Dist\xe2ncia (EaD)'), (3, '3 - Semipresencial')], default=0),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='s2245_evttreicap',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s2245infocomplem_s2245_evttreicap', to='esocial.s2245evtTreiCap'),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='tptreicap',
            field=models.IntegerField(choices=[(1, '1 - Inicial'), (2, '2 - Peri\xf3dico'), (3, '3 - Reciclagem'), (4, '4 - Eventual'), (5, '5 - Outros')], default=0),
        ),
    ]
