# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2245', '0003_auto_20181119_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='codcbo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='criado_em',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='formprof',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='nacprof',
            field=models.IntegerField(choices=[(1, '1 - Brasileiro'), (2, '2 - Estrangeiro')]),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='nmprof',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='s2245_infocomplem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2245ideprofresp_s2245_infocomplem', to='s2245.s2245infoComplem'),
        ),
        migrations.AlterField(
            model_name='s2245ideprofresp',
            name='tpprof',
            field=models.IntegerField(choices=[(1, '1 - Profissional empregado do declarante'), (2, '2 - Profissional sem v\xednculo de emprego/estatut\xe1rio com o declarante')]),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='criado_em',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='dttreicap',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='durtreicap',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=6),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='modtreicap',
            field=models.IntegerField(choices=[(1, '1 - Presencial'), (2, '2 - Educa\xe7\xe3o a Dist\xe2ncia (EaD)'), (3, '3 - Semipresencial')]),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='s2245_evttreicap',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s2245infocomplem_s2245_evttreicap', to='esocial.s2245evtTreiCap'),
        ),
        migrations.AlterField(
            model_name='s2245infocomplem',
            name='tptreicap',
            field=models.IntegerField(choices=[(1, '1 - Inicial'), (2, '2 - Peri\xf3dico'), (3, '3 - Reciclagem'), (4, '4 - Eventual'), (5, '5 - Outros')]),
        ),
    ]
