# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s5011', '0007_auto_20190202_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s5011basesaquis',
            options={'managed': True, 'ordering': ['s5011_ideestab', 'indaquis', 'vlraquis', 'vrcpdescpr', 'vrcpnret', 'vrratnret', 'vrsenarnret', 'vrcpcalcpr', 'vrratdescpr', 'vrratcalcpr', 'vrsenardesc', 'vrsenarcalc'], 'permissions': (('can_view_s5011_basesaquis', 'Can view s5011_basesaquis'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011basesavnport',
            options={'managed': True, 'ordering': ['s5011_idelotacao', 'vrbccp00', 'vrbccp15', 'vrbccp20', 'vrbccp25', 'vrbccp13', 'vrbcfgts', 'vrdesccp'], 'permissions': (('can_view_s5011_basesavnport', 'Can view s5011_basesavnport'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011basescomerc',
            options={'managed': True, 'ordering': ['s5011_ideestab', 'indcomerc', 'vrbccompr'], 'permissions': (('can_view_s5011_basescomerc', 'Can view s5011_basescomerc'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011basesremun',
            options={'managed': True, 'ordering': ['s5011_idelotacao', 'indincid', 'codcateg', 'vrbccp00', 'vrbccp15', 'vrbccp20', 'vrbccp25', 'vrsuspbccp00', 'vrsuspbccp15', 'vrsuspbccp20', 'vrsuspbccp25', 'vrdescsest', 'vrcalcsest', 'vrdescsenat', 'vrcalcsenat', 'vrsalfam', 'vrsalmat'], 'permissions': (('can_view_s5011_basesremun', 'Can view s5011_basesremun'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011dadosopport',
            options={'managed': True, 'ordering': ['s5011_idelotacao', 'cnpjopportuario', 'aliqrat', 'fap', 'aliqratajust'], 'permissions': (('can_view_s5011_dadosopport', 'Can view s5011_dadosopport'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011ideestab',
            options={'managed': True, 'ordering': ['s5011_evtcs', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_s5011_ideestab', 'Can view s5011_ideestab'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011idelotacao',
            options={'managed': True, 'ordering': ['s5011_ideestab', 'codlotacao', 'fpas', 'codtercs'], 'permissions': (('can_view_s5011_idelotacao', 'Can view s5011_idelotacao'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infoatconc',
            options={'managed': True, 'ordering': ['s5011_infopj', 'fatormes', 'fator13'], 'permissions': (('can_view_s5011_infoatconc', 'Can view s5011_infoatconc'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infocomplobra',
            options={'managed': True, 'ordering': ['s5011_infoestab', 'indsubstpatrobra'], 'permissions': (('can_view_s5011_infocomplobra', 'Can view s5011_infocomplobra'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infocpseg',
            options={'managed': True, 'ordering': ['s5011_evtcs', 'vrdesccp', 'vrcpseg'], 'permissions': (('can_view_s5011_infocpseg', 'Can view s5011_infocpseg'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infocrcontrib',
            options={'managed': True, 'ordering': ['s5011_evtcs', 'tpcr', 'vrcr'], 'permissions': (('can_view_s5011_infocrcontrib', 'Can view s5011_infocrcontrib'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infocrestab',
            options={'managed': True, 'ordering': ['s5011_ideestab', 'tpcr', 'vrcr'], 'permissions': (('can_view_s5011_infocrestab', 'Can view s5011_infocrestab'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infoemprparcial',
            options={'managed': True, 'ordering': ['s5011_idelotacao', 'tpinsccontrat', 'nrinsccontrat', 'tpinscprop', 'nrinscprop'], 'permissions': (('can_view_s5011_infoemprparcial', 'Can view s5011_infoemprparcial'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infoestab',
            options={'managed': True, 'ordering': ['s5011_ideestab', 'cnaeprep', 'aliqrat', 'fap', 'aliqratajust'], 'permissions': (('can_view_s5011_infoestab', 'Can view s5011_infoestab'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infopj',
            options={'managed': True, 'ordering': ['s5011_evtcs', 'indconstr'], 'permissions': (('can_view_s5011_infopj', 'Can view s5011_infopj'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infosubstpatropport',
            options={'managed': True, 'ordering': ['s5011_idelotacao', 'cnpjopportuario'], 'permissions': (('can_view_s5011_infosubstpatropport', 'Can view s5011_infosubstpatropport'),)},
        ),
        migrations.AlterModelOptions(
            name='s5011infotercsusp',
            options={'managed': True, 'ordering': ['s5011_idelotacao', 'codterc'], 'permissions': (('can_view_s5011_infotercsusp', 'Can view s5011_infotercsusp'),)},
        ),
    ]
