# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcidentesSituacoesGeradoras',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='acidentessituacoesgeradoras_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='acidentessituacoesgeradoras_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'acidentes_situacoes_geradoras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfastamentosMotivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='afastamentosmotivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='afastamentosmotivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao', 'data_inicio', 'data_termino'],
                'db_table': 'afastamentos_motivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentesCausadoresAcidentesTrabalho',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='agentescausadoresacidentestrabalho_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='agentescausadoresacidentestrabalho_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'agentes_causadores_acidentes_trabalho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentesCausadoresDoencasProfissionais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='agentescausadoresdoencasprofissionais_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='agentescausadoresdoencasprofissionais_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'agentes_causadores_doencas_profissionais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArquivosEsocialTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='arquivosesocialtipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='arquivosesocialtipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'arquivos_esocial_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AtividadesPericulosasInsalubresEspeciais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'ATIVIDADES COM EXPOSI\xc7\xc3O A RISCOS BIOL\xd3GICOS'), (10, 'OUTRAS ATIVIDADES'), (11, 'AUS\xcaNCIA DE CORRESPOND\xcaNCIA'), (2, 'ATIVIDADES COM EXPOSI\xc7\xc3O A RISCOS QU\xcdMICOS'), (3, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM EXPLOSIVOS'), (4, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM INFLAM\xc1VEIS'), (5, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM RADIA\xc7\xd5ES IONIZANTES OU SUBST\xc2NCIAS RADIOATIVAS'), (6, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM EXPOSI\xc7\xc3O A ROUBOS OU OUTRAS ESP\xc9CIES DE VIOL\xcaNCIA F\xcdSICA NAS ATIVIDADES PROFISSIONAIS DE SEGURAN\xc7A PESSOAL OU PATRIMONIAL'), (7, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM ENERGIA EL\xc9TRICA'), (8, 'ATIVIDADES PERIGOSAS EM MOTOCICLETA'), (9, 'ATIVIDADES ESPECIAIS POR EXPOSI\xc7\xc3O A AGENTES F\xcdSICOS')])),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='atividadespericulosasinsalubresespeciais_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='atividadespericulosasinsalubresespeciais_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'codigo', 'descricao'],
                'db_table': 'atividades_periculosas_insalubres_especiais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BeneficiosPrevidenciariosCessacaoMotivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='beneficiosprevidenciarioscessacaomotivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='beneficiosprevidenciarioscessacaomotivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'beneficios_previdenciarios_cessacao_motivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BeneficiosPrevidenciariosTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='beneficiosprevidenciariostipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='beneficiosprevidenciariostipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'beneficios_previdenciarios_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CBO',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='cbo_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='cbo_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'cbo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(null=True, blank=True)),
                ('descricao_resumida', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='cid_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='cid_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'cid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoServicosPrestados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='classificacaoservicosprestados_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='classificacaoservicosprestados_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'classificacao_servicos_prestados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoTributaria',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='classificacaotributaria_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='classificacaotributaria_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'classificacao_tributaria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassificacoesTributarias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='classificacoestributarias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='classificacoestributarias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'classificacoes_tributarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=7)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(null=True, blank=True)),
                ('aliquota', models.DecimalField(max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='cnae_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='cnae_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'cnae',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodificacoesAcidenteTrabalho',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='codificacoesacidentetrabalho_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='codificacoesacidentetrabalho_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'codificacoes_acidente_trabalho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoAliquotasFPASTerceiros',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descricao', models.TextField()),
                ('tipo_empresa', models.CharField(max_length=20)),
                ('base_calculo', models.CharField(max_length=50)),
                ('terceiros', models.CharField(max_length=20)),
                ('codigo_terceiro', models.CharField(max_length=4)),
                ('aliquota', models.DecimalField(max_digits=15, decimal_places=2)),
                ('ind_total', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='codigoaliquotasfpasterceiros_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='codigoaliquotasfpasterceiros_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'codigo_aliquotas_fpas_terceiros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigosAtividadesProdutosServicosCPRB',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('grupo', models.IntegerField(choices=[(1, 'I - Pessoas Jur\xeddicas Prestadoras de Servi\xe7os -'), (2, 'II - Pessoas Jur\xeddicas Comerciais - CR 2991-01'), (3, 'III - Pessoas Jur\xeddicas Fabricantes - CR 2991-01'), (4, 'IV - C\xf3digos Gen\xe9ricos - Outras Receitas sujeitas \xe0 CPRB - CR 2991-01')])),
                ('aliquota', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('inicio_escrituracao', models.DateField(null=True, blank=True)),
                ('ncm', models.CharField(max_length=12, null=True, blank=True)),
                ('cr', models.CharField(max_length=12, null=True, blank=True)),
                ('incidencia', models.TextField(null=True, blank=True)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='codigosatividadesprodutosservicoscprb_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='codigosatividadesprodutosservicoscprb_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'grupo', 'aliquota', 'inicio_escrituracao', 'ncm', 'cr', 'incidencia', 'descricao'],
                'db_table': 'codigos_atividades_produtos_servicos_cprb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadesCategoriasClassificacoesLotacoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('classificacao_tributaria', models.TextField()),
                ('tipo_lotacao_tributaria_01', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_02', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_03', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_04', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_05', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_06', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_07', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_08', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_09', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_10', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_21', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_24', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_90', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_91', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='compatibilidadescategoriasclassificacoeslotacoes_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='compatibilidadescategoriasclassificacoeslotacoes_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'classificacao_tributaria'],
                'db_table': 'compatibilidades_categorias_classificacoes_lotacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadesFPASClassificacoesTributarias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('classificacao_tributaria_01', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_02', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_03', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_04', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_06', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_07', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_08', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_09', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_10', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_11', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_13', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_14', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_21', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_22', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_60', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_70', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_80', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_85', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_99', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='compatibilidadesfpasclassificacoestributarias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='compatibilidadesfpasclassificacoestributarias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'compatibilidades_fpas_classificacoes_tributarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadesLotacoesClassificacoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('tipo_classificacao_tributaria_01', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_02', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_03', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_04', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_06', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_07', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_08', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_09', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_10', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_11', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_13', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_14', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_21', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_22', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_60', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_70', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_80', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_85', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_99', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='compatibilidadeslotacoesclassificacoes_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='compatibilidadeslotacoesclassificacoes_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'compatibilidades_lotacoes_classificacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DependentesTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='dependentestipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='dependentestipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'dependentes_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DesligamentosMotivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='desligamentosmotivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='desligamentosmotivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao', 'data_inicio', 'data_termino'],
                'db_table': 'desligamentos_motivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfEventos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfeventos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfeventos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_eventos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FatoresRisco',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'F\xcdSICOS'), (10, 'PERICULOSO'), (11, 'ASSOCIA\xc7\xc3O DE FATORES DE RISCO'), (12, 'OUTROS FATORES DE RISCO'), (13, 'AUS\xcaNCIA DE FATORES DE RISCO'), (2, 'QU\xcdMICOS'), (3, 'BIOL\xd3GICOS'), (4, 'ERGON\xd4MICOS - BIOMEC\xc2NICOS'), (5, 'ERGON\xd4MICOS - MOBILI\xc1RIO E EQUIPAMENTOS'), (6, 'ERGON\xd4MICOS - ORGANIZACIONAIS'), (7, 'ERGON\xd4MICOS - AMBIENTAIS'), (8, 'ERGON\xd4MICOS - PSICOSSOCIAIS/COGNITIVOS'), (9, 'MEC\xc2NICOS/ACIDENTES')])),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='fatoresrisco_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='fatoresrisco_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'codigo', 'descricao'],
                'db_table': 'fatores_risco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinanciamentosAposentadoriasEspeciais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='financiamentosaposentadoriasespeciais_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='financiamentosaposentadoriasespeciais_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'financiamentos_aposentadorias_especiais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InformacoesBeneficiariosExterior',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='informacoesbeneficiariosexterior_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='informacoesbeneficiariosexterior_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'informacoes_beneficiarios_exterior',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InscricoesTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='inscricoestipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='inscricoestipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'inscricoes_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogradourosTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='logradourostipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='logradourostipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'logradouros_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LotacoesTributariasTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('preenchimento_campo_nr_insc', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='lotacoestributariastipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='lotacoestributariastipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'lotacoes_tributarias_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=7)),
                ('titulo', models.CharField(max_length=300)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='municipios_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='municipios_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['titulo'],
                'db_table': 'municipios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NaturezasJuridicas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Administra\xe7\xe3o P\xfablica'), (2, 'Entidades Empresariais'), (3, 'Entidades sem Fins Lucrativos'), (4, 'Pessoas F\xedsicas'), (5, 'Organiza\xe7\xf5es Internacionais e Outras Institui\xe7\xf5es Extraterritoriais')])),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='naturezasjuridicas_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='naturezasjuridicas_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'naturezas_juridicas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NaturezasLesoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='naturezaslesoes_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='naturezaslesoes_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'naturezas_lesoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NaturezasRubricas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='naturezasrubricas_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='naturezasrubricas_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'titulo'],
                'db_table': 'naturezas_rubricas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagamentosCodigos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Benefici\xe1rios no Brasil'), (2, 'Benefici\xe1rios no Brasil e Justi\xe7a \u2013 RRA'), (3, 'Remessa Exterior')])),
                ('beneficiario_pf', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('beneficiario_pj', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='pagamentoscodigos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='pagamentoscodigos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'beneficiario_pf', 'beneficiario_pj', 'codigo', 'descricao'],
                'db_table': 'pagamentos_codigos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(null=True, blank=True)),
                ('data_extincao', models.DateField(null=True, blank=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='paises_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='paises_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'nome', 'codigo', 'descricao'],
                'db_table': 'paises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartesCorpoAtingidas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='partescorpoatingidas_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='partescorpoatingidas_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'partes_corpo_atingidas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcedimentosDiagnosticos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='procedimentosdiagnosticos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='procedimentosdiagnosticos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'procedimentos_diagnosticos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramasPlanosDocumentos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='programasplanosdocumentos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='programasplanosdocumentos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'programas_planos_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegrasPagamentosCodigos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('classificacao', models.IntegerField(choices=[(1, 'Benefici\xe1rios'), (2, 'Benefici\xe1rios / Justi\xe7a \u2013 RRA')])),
                ('tributacao_com_exigibilidade_suspensa', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('compensacao_imposto_por_decisao_judicial', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('rendimentos_isentos', models.CharField(max_length=10, null=True, blank=True)),
                ('deducoes', models.CharField(max_length=10, null=True, blank=True)),
                ('decimo_terceiro', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='regraspagamentoscodigos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='regraspagamentoscodigos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['classificacao', 'tributacao_com_exigibilidade_suspensa', 'compensacao_imposto_por_decisao_judicial', 'rendimentos_isentos', 'deducoes', 'decimo_terceiro', 'codigo', 'descricao'],
                'db_table': 'regras_pagamentos_codigos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RendimentosBeneficiariosExterior',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='rendimentosbeneficiariosexterior_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='rendimentosbeneficiariosexterior_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'rendimentos_beneficiarios_exterior',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RendimentosBeneficiariosExteriorTributacao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='rendimentosbeneficiariosexteriortributacao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='rendimentosbeneficiariosexteriortributacao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'rendimentos_beneficiarios_exterior_tributacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrabalhadoresCategorias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Empregado e Trabalhador Tempor\xe1rio'), (2, 'Avulso'), (3, 'Agente P\xfablico'), (4, 'Cess\xe3o'), (5, 'Contribuinte Individual'), (6, 'Bolsistas')])),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='trabalhadorescategorias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='trabalhadorescategorias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'codigo', 'descricao'],
                'db_table': 'trabalhadores_categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TreinamentosCapacitacoesExerciciosSimulados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='treinamentoscapacitacoesexerciciossimulados_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='treinamentoscapacitacoesexerciciossimulados_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'treinamentos_capacitacoes_exercicios_simulados',
                'managed': True,
            },
        ),
    ]
