# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0011_auto_20181123_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='efdreinfcodigosatividadesprodutosservicoscprb',
            options={'managed': True, 'ordering': ['grupo', 'codigo', 'descricao', 'incidencia', 'cr', 'ncm', 'aliquota', 'inicio_escrituracao']},
        ),
        migrations.AlterModelOptions(
            name='efdreinfpagamentoscodigos',
            options={'managed': True, 'ordering': ['grupo', 'codigo', 'beneficiario_pj', 'beneficiario_pf', 'descricao']},
        ),
        migrations.AlterModelOptions(
            name='efdreinfregraspagamentoscodigos',
            options={'managed': True, 'ordering': ['classificacao', 'codigo', 'decimo_terceiro', 'deducoes', 'rendimentos_isentos', 'compensacao_imposto_por_decisao_judicial', 'tributacao_com_exigibilidade_suspensa', 'descricao']},
        ),
    ]
