# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r9002', '0003_auto_20190513_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r9002infototal',
            name='nrinsc',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r9002infototal',
            name='r9002_evtret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002infototal_r9002_evtret', to='efdreinf.r9002evtRet'),
        ),
        migrations.AlterField(
            model_name='r9002infototal',
            name='tpinsc',
            field=models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF'), (3, '3 - CAEPF (Cadastro de Atividade Econ\xf4mica de Pessoa F\xedsica)'), (4, '4 - CNO (Cadastro Nacional de Obra)'), (5, '5 - CGC')]),
        ),
        migrations.AlterField(
            model_name='r9002regocorrs',
            name='codresp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='r9002regocorrs',
            name='dscresp',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='r9002regocorrs',
            name='localerroaviso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='r9002regocorrs',
            name='r9002_evtret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002regocorrs_r9002_evtret', to='efdreinf.r9002evtRet'),
        ),
        migrations.AlterField(
            model_name='r9002regocorrs',
            name='tpocorr',
            field=models.IntegerField(choices=[(1, '1 - Erro'), (2, '2 - Aviso.')]),
        ),
        migrations.AlterField(
            model_name='r9002totapurdec',
            name='crdec',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='r9002totapurdec',
            name='perapurdec',
            field=models.IntegerField(choices=[(1, '1 - O dia ("DD") da data informada em {dtFG} no evento de origem \xe9 de 1 a 10'), (2, '2 - O dia ("DD") da data informada em {dtFG} no evento de origem \xe9 de 11 a 20'), (3, '3 - O dia ("DD") da data informada em {dtFG} no evento de origem \xe9 de 21 a 31.')]),
        ),
        migrations.AlterField(
            model_name='r9002totapurdec',
            name='r9002_infototal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002totapurdec_r9002_infototal', to='r9002.r9002infoTotal'),
        ),
        migrations.AlterField(
            model_name='r9002totapurdec',
            name='vlrbasecrdec',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurdec',
            name='vlrcrdec',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurdia',
            name='crdia',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='r9002totapurdia',
            name='perapurdia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r9002totapurdia',
            name='r9002_infototal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002totapurdia_r9002_infototal', to='r9002.r9002infoTotal'),
        ),
        migrations.AlterField(
            model_name='r9002totapurdia',
            name='vlrbasecrdia',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurdia',
            name='vlrcrdia',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurmen',
            name='crmen',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='r9002totapurmen',
            name='r9002_infototal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002totapurmen_r9002_infototal', to='r9002.r9002infoTotal'),
        ),
        migrations.AlterField(
            model_name='r9002totapurmen',
            name='vlrbasecrmen',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurmen',
            name='vlrcrmen',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurqui',
            name='crqui',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='r9002totapurqui',
            name='perapurqui',
            field=models.IntegerField(choices=[(1, '1 - O dia ("DD") da data informada em {dtFG} no evento de origem \xe9 de 1 a 15'), (2, '2 - O dia ("DD") da data informada em {dtFG} no evento de origem \xe9 de 16 a 31.')]),
        ),
        migrations.AlterField(
            model_name='r9002totapurqui',
            name='r9002_infototal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002totapurqui_r9002_infototal', to='r9002.r9002infoTotal'),
        ),
        migrations.AlterField(
            model_name='r9002totapurqui',
            name='vlrbasecrqui',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapurqui',
            name='vlrcrqui',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapursem',
            name='crsem',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='r9002totapursem',
            name='perapursem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r9002totapursem',
            name='r9002_infototal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r9002totapursem_r9002_infototal', to='r9002.r9002infoTotal'),
        ),
        migrations.AlterField(
            model_name='r9002totapursem',
            name='vlrbasecrsem',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r9002totapursem',
            name='vlrcrsem',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
