# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2405', '0015_auto_20190531_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s2405brasil',
            options={'managed': True, 'ordering': ['s2405_endereco', 'tplograd', 'dsclograd', 'nrlograd', 'cep', 'codmunic', 'uf'], 'permissions': (('can_see_list_s2405brasil', 'Pode ver listagem do modelo S2405BRASIL'), ('can_see_data_s2405brasil', 'Pode visualizar o conte\xfado do modelo S2405BRASIL'), ('can_see_menu_s2405brasil', 'Pode visualizar no menu o modelo S2405BRASIL'), ('can_print_list_s2405brasil', 'Pode imprimir listagem do modelo S2405BRASIL'), ('can_print_data_s2405brasil', 'Pode imprimir o conte\xfado do modelo S2405BRASIL'))},
        ),
        migrations.AlterModelOptions(
            name='s2405dependente',
            options={'managed': True, 'ordering': ['s2405_evtcdbenefalt', 'tpdep', 'nmdep', 'dtnascto', 'sexodep', 'depirrf', 'incfismen', 'depfinsprev'], 'permissions': (('can_see_list_s2405dependente', 'Pode ver listagem do modelo S2405DEPENDENTE'), ('can_see_data_s2405dependente', 'Pode visualizar o conte\xfado do modelo S2405DEPENDENTE'), ('can_see_menu_s2405dependente', 'Pode visualizar no menu o modelo S2405DEPENDENTE'), ('can_print_list_s2405dependente', 'Pode imprimir listagem do modelo S2405DEPENDENTE'), ('can_print_data_s2405dependente', 'Pode imprimir o conte\xfado do modelo S2405DEPENDENTE'))},
        ),
        migrations.AlterModelOptions(
            name='s2405endereco',
            options={'managed': True, 'ordering': ['s2405_evtcdbenefalt'], 'permissions': (('can_see_list_s2405endereco', 'Pode ver listagem do modelo S2405ENDERECO'), ('can_see_data_s2405endereco', 'Pode visualizar o conte\xfado do modelo S2405ENDERECO'), ('can_see_menu_s2405endereco', 'Pode visualizar no menu o modelo S2405ENDERECO'), ('can_print_list_s2405endereco', 'Pode imprimir listagem do modelo S2405ENDERECO'), ('can_print_data_s2405endereco', 'Pode imprimir o conte\xfado do modelo S2405ENDERECO'))},
        ),
        migrations.AlterModelOptions(
            name='s2405exterior',
            options={'managed': True, 'ordering': ['s2405_endereco', 'paisresid', 'dsclograd', 'nrlograd', 'nmcid'], 'permissions': (('can_see_list_s2405exterior', 'Pode ver listagem do modelo S2405EXTERIOR'), ('can_see_data_s2405exterior', 'Pode visualizar o conte\xfado do modelo S2405EXTERIOR'), ('can_see_menu_s2405exterior', 'Pode visualizar no menu o modelo S2405EXTERIOR'), ('can_print_list_s2405exterior', 'Pode imprimir listagem do modelo S2405EXTERIOR'), ('can_print_data_s2405exterior', 'Pode imprimir o conte\xfado do modelo S2405EXTERIOR'))},
        ),
    ]
