# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r2010', '0010_auto_20190428_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2010infoprocretad',
            name='nrprocretadic',
            field=models.CharField(default=b'A', max_length=21),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretad',
            name='r2010_evtservtom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r2010infoprocretad_r2010_evtservtom', to='efdreinf.r2010evtServTom'),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretad',
            name='tpprocretadic',
            field=models.IntegerField(choices=[(1, '1 - Administrativo'), (2, '2 - Judicial.')], default=0),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretad',
            name='valoradic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretpr',
            name='nrprocretprinc',
            field=models.CharField(default=b'A', max_length=21),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretpr',
            name='r2010_evtservtom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r2010infoprocretpr_r2010_evtservtom', to='efdreinf.r2010evtServTom'),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretpr',
            name='tpprocretprinc',
            field=models.IntegerField(choices=[(1, '1 - Administrativo'), (2, '2 - Judicial.')], default=0),
        ),
        migrations.AlterField(
            model_name='r2010infoprocretpr',
            name='valorprinc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='r2010_nfs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r2010infotpserv_r2010_nfs', to='r2010.r2010nfs'),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='tpservico',
            field=models.IntegerField(choices=[(100000001, '100000001 - Limpeza, conserva\xe7\xe3o ou zeladoria'), (100000002, '100000002 - Vigil\xe2ncia ou seguran\xe7a'), (100000003, '100000003 - Constru\xe7\xe3o civil'), (100000004, '100000004 - Servi\xe7os de natureza rural'), (100000005, '100000005 - Digita\xe7\xe3o'), (100000006, '100000006 - Prepara\xe7\xe3o de dados para processamento'), (100000007, '100000007 - Acabamento'), (100000008, '100000008 - Embalagem'), (100000009, '100000009 - Acondicionamento'), (100000010, '100000010 - Cobran\xe7a'), (100000011, '100000011 - Coleta ou reciclagem de lixo ou de res\xedduos'), (100000012, '100000012 - Copa'), (100000013, '100000013 - Hotelaria'), (100000014, '100000014 - Corte ou liga\xe7\xe3o de servi\xe7os p\xfablicos'), (100000015, '100000015 - Distribui\xe7\xe3o'), (100000016, '100000016 - Treinamento e ensino'), (100000017, '100000017 - Entrega de contas e de documentos'), (100000018, '100000018 - Liga\xe7\xe3o de medidores'), (100000019, '100000019 - Leitura de medidores'), (100000020, '100000020 - Manuten\xe7\xe3o de instala\xe7\xf5es, de m\xe1quinas ou de equipamentos'), (100000021, '100000021 - Montagem'), (100000022, '100000022 - Opera\xe7\xe3o de m\xe1quinas, de equipamentos e de ve\xedculos'), (100000023, '100000023 - Opera\xe7\xe3o de ped\xe1gio ou de terminal de transporte'), (100000024, '100000024 - Opera\xe7\xe3o de transporte de passageiros'), (100000025, '100000025 - Portaria, recep\xe7\xe3o ou ascensorista'), (100000026, '100000026 - Recep\xe7\xe3o, triagem ou movimenta\xe7\xe3o de materiais'), (100000027, '100000027 - Promo\xe7\xe3o de vendas ou de eventos'), (100000028, '100000028 - Secretaria e expediente'), (100000029, '100000029 - Sa\xfade'), (100000030, '100000030 - Telefonia ou telemarketing'), (100000031, '100000031 - Trabalho tempor\xe1rio na forma da Lei n\xba 6.019, de janeiro de 1974')], default=0),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlradicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrbaseret',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrnretadic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrnretprinc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrretencao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrretsub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrservicos15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrservicos20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010infotpserv',
            name='vlrservicos25',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='r2010nfs',
            name='dtemissaonf',
            field=models.DateField(default=b'1900-01-01'),
        ),
        migrations.AlterField(
            model_name='r2010nfs',
            name='numdocto',
            field=models.CharField(default=b'A', max_length=15),
        ),
        migrations.AlterField(
            model_name='r2010nfs',
            name='r2010_evtservtom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r2010nfs_r2010_evtservtom', to='efdreinf.r2010evtServTom'),
        ),
        migrations.AlterField(
            model_name='r2010nfs',
            name='serie',
            field=models.CharField(default=b'A', max_length=5),
        ),
        migrations.AlterField(
            model_name='r2010nfs',
            name='vlrbruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
