# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r3010', '0014_auto_20190531_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r3010boletim',
            options={'managed': True, 'ordering': ['r3010_evtespdesportivo', 'nrboletim', 'tpcompeticao', 'categevento', 'moddesportiva', 'nomecompeticao', 'cnpjmandante', 'pracadesportiva', 'uf', 'qtdepagantes', 'qtdenaopagantes'], 'permissions': (('can_see_list_r3010boletim', 'Pode ver listagem do modelo R3010BOLETIM'), ('can_see_data_r3010boletim', 'Pode visualizar o conte\xfado do modelo R3010BOLETIM'), ('can_see_menu_r3010boletim', 'Pode visualizar no menu o modelo R3010BOLETIM'), ('can_print_list_r3010boletim', 'Pode imprimir listagem do modelo R3010BOLETIM'), ('can_print_data_r3010boletim', 'Pode imprimir o conte\xfado do modelo R3010BOLETIM'))},
        ),
        migrations.AlterModelOptions(
            name='r3010infoproc',
            options={'managed': True, 'ordering': ['r3010_evtespdesportivo', 'tpproc', 'nrproc', 'vlrcpsusp'], 'permissions': (('can_see_list_r3010infoProc', 'Pode ver listagem do modelo R3010INFOPROC'), ('can_see_data_r3010infoProc', 'Pode visualizar o conte\xfado do modelo R3010INFOPROC'), ('can_see_menu_r3010infoProc', 'Pode visualizar no menu o modelo R3010INFOPROC'), ('can_print_list_r3010infoProc', 'Pode imprimir listagem do modelo R3010INFOPROC'), ('can_print_data_r3010infoProc', 'Pode imprimir o conte\xfado do modelo R3010INFOPROC'))},
        ),
        migrations.AlterModelOptions(
            name='r3010outrasreceitas',
            options={'managed': True, 'ordering': ['r3010_boletim', 'tpreceita', 'vlrreceita', 'descreceita'], 'permissions': (('can_see_list_r3010outrasReceitas', 'Pode ver listagem do modelo R3010OUTRASRECEITAS'), ('can_see_data_r3010outrasReceitas', 'Pode visualizar o conte\xfado do modelo R3010OUTRASRECEITAS'), ('can_see_menu_r3010outrasReceitas', 'Pode visualizar no menu o modelo R3010OUTRASRECEITAS'), ('can_print_list_r3010outrasReceitas', 'Pode imprimir listagem do modelo R3010OUTRASRECEITAS'), ('can_print_data_r3010outrasReceitas', 'Pode imprimir o conte\xfado do modelo R3010OUTRASRECEITAS'))},
        ),
        migrations.AlterModelOptions(
            name='r3010receitaingressos',
            options={'managed': True, 'ordering': ['r3010_boletim', 'tpingresso', 'descingr', 'qtdeingrvenda', 'qtdeingrvendidos', 'qtdeingrdev', 'precoindiv', 'vlrtotal'], 'permissions': (('can_see_list_r3010receitaIngressos', 'Pode ver listagem do modelo R3010RECEITAINGRESSOS'), ('can_see_data_r3010receitaIngressos', 'Pode visualizar o conte\xfado do modelo R3010RECEITAINGRESSOS'), ('can_see_menu_r3010receitaIngressos', 'Pode visualizar no menu o modelo R3010RECEITAINGRESSOS'), ('can_print_list_r3010receitaIngressos', 'Pode imprimir listagem do modelo R3010RECEITAINGRESSOS'), ('can_print_data_r3010receitaIngressos', 'Pode imprimir o conte\xfado do modelo R3010RECEITAINGRESSOS'))},
        ),
    ]
