# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensageiro', '0001_initial'),
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='r1000evtInfoContri',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('operacao', models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')])),
                ('criado_por', models.ForeignKey(related_name='r1000evtinfocontri_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r1000evtinfocontri_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'],
                'db_table': 'r1000_evtinfocontri',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r1070evtTabProcesso',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('operacao', models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')])),
                ('criado_por', models.ForeignKey(related_name='r1070evttabprocesso_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r1070evttabprocesso_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'],
                'db_table': 'r1070_evttabprocesso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2010evtServTom',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpinscestab', models.IntegerField(choices=[(1, '1 - CNPJ'), (4, '4 - CNO')])),
                ('nrinscestab', models.CharField(max_length=14)),
                ('indobra', models.IntegerField(choices=[(0, '0 - N\xe3o \xe9 obra de constru\xe7\xe3o civil ou n\xe3o est\xe1 sujeita a matr\xedcula de obra'), (1, '1 - Obra de Constru\xe7\xe3o Civil - Empreitada Total'), (2, '2 - Obra de Constru\xe7\xe3o Civil - Empreitada Parcial')])),
                ('cnpjprestador', models.CharField(max_length=14)),
                ('vlrtotalbruto', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrtotalbaseret', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrtotalretprinc', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrtotalretadic', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrtotalnretprinc', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrtotalnretadic', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('indcprb', models.IntegerField(choices=[(0, '0 - N\xe3o \xe9 contribuinte da Contribui\xe7\xe3o Previdenci\xe1ria sobre a Receita Bruta (CPRB) - Reten\xe7\xe3o 11%'), (1, '1 - Contribuinte da Contribui\xe7\xe3o Previdenci\xe1ria sobre a Receita Bruta (CPRB) - Reten\xe7\xe3o 3,5%')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2010evtservtom_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2010evtservtom_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscestab', 'nrinscestab', 'indobra', 'cnpjprestador', 'vlrtotalbruto', 'vlrtotalbaseret', 'vlrtotalretprinc', 'vlrtotalretadic', 'vlrtotalnretprinc', 'vlrtotalnretadic', 'indcprb'],
                'db_table': 'r2010_evtservtom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2020evtServPrest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpinscestabprest', models.IntegerField(choices=[(1, '1 - CNPJ')])),
                ('nrinscestabprest', models.CharField(max_length=14)),
                ('tpinsctomador', models.IntegerField(choices=[(1, '1 - CNPJ'), (4, '4 - CNO')])),
                ('nrinsctomador', models.CharField(max_length=14)),
                ('indobra', models.IntegerField(choices=[(0, '0 - N\xe3o \xe9 obra de constru\xe7\xe3o civil ou n\xe3o est\xe1 sujeita a matr\xedcula de obra'), (1, '1 - Obra de Constru\xe7\xe3o Civil - Empreitada Total'), (2, '2 - Obra de Constru\xe7\xe3o Civil - Empreitada Parcial')])),
                ('vlrtotalbruto', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrtotalbaseret', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrtotalretprinc', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrtotalretadic', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrtotalnretprinc', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrtotalnretadic', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2020evtservprest_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2020evtservprest_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscestabprest', 'nrinscestabprest', 'tpinsctomador', 'nrinsctomador', 'indobra', 'vlrtotalbruto', 'vlrtotalbaseret', 'vlrtotalretprinc', 'vlrtotalretadic', 'vlrtotalnretprinc', 'vlrtotalnretadic'],
                'db_table': 'r2020_evtservprest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2030evtAssocDespRec',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpinscestab', models.IntegerField(choices=[(1, '1 - CNPJ')])),
                ('nrinscestab', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2030evtassocdesprec_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2030evtassocdesprec_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscestab', 'nrinscestab'],
                'db_table': 'r2030_evtassocdesprec',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2040evtAssocDespRep',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpinscestab', models.IntegerField(choices=[(1, '1 - CNPJ')])),
                ('nrinscestab', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2040evtassocdesprep_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2040evtassocdesprep_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscestab', 'nrinscestab'],
                'db_table': 'r2040_evtassocdesprep',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2050evtComProd',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpinscestab', models.IntegerField(choices=[(1, '1 - CNPJ')])),
                ('nrinscestab', models.CharField(max_length=14)),
                ('vlrrecbrutatotal', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrcpapur', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrratapur', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrsenarapur', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrcpsusptotal', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrratsusptotal', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrsenarsusptotal', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2050evtcomprod_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2050evtcomprod_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscestab', 'nrinscestab', 'vlrrecbrutatotal', 'vlrcpapur', 'vlrratapur', 'vlrsenarapur', 'vlrcpsusptotal', 'vlrratsusptotal', 'vlrsenarsusptotal'],
                'db_table': 'r2050_evtcomprod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2060evtCPRB',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpinscestab', models.IntegerField(choices=[(1, '1 - CNPJ'), (4, '4 - CNO')])),
                ('nrinscestab', models.CharField(max_length=14)),
                ('vlrrecbrutatotal', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrcpapurtotal', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrcprbsusptotal', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2060evtcprb_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2060evtcprb_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpinscestab', 'nrinscestab', 'vlrrecbrutatotal', 'vlrcpapurtotal', 'vlrcprbsusptotal'],
                'db_table': 'r2060_evtcprb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070evtPgtosDivs',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (1, '1 - CNPJ'), (2, '2 - CPF'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('codpgto', models.IntegerField()),
                ('tpinscbenef', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Pessoa Jur\xeddica'), (2, '2 - Pessoa F\xedsica')])),
                ('nrinscbenef', models.CharField(max_length=14, null=True, blank=True)),
                ('nmrazaobenef', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2070evtpgtosdivs_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070evtpgtosdivs_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'codpgto', 'tpinscbenef', 'nrinscbenef', 'nmrazaobenef'],
                'db_table': 'r2070_evtpgtosdivs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2098evtReabreEvPer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2098evtreabreevper_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2098evtreabreevper_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'],
                'db_table': 'r2098_evtreabreevper',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2099evtFechaEvPer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('evtservtm', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('evtservpr', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('evtassdesprec', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('evtassdesprep', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('evtcomprod', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('evtcprb', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('evtpgtos', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('compsemmovto', models.CharField(max_length=7, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r2099evtfechaevper_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2099evtfechaevper_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'perapur', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'evtservtm', 'evtservpr', 'evtassdesprec', 'evtassdesprep', 'evtcomprod', 'evtcprb', 'evtpgtos', 'compsemmovto'],
                'db_table': 'r2099_evtfechaevper',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r3010evtEspDesportivo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('indretif', models.IntegerField(choices=[(1, '1 - Arquivo original'), (2, '2 - Arquivo de retifica\xe7\xe3o')])),
                ('nrrecibo', models.CharField(max_length=52, null=True, blank=True)),
                ('dtapuracao', models.DateField()),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r3010evtespdesportivo_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r3010evtespdesportivo_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['identidade', 'indretif', 'nrrecibo', 'dtapuracao', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc'],
                'db_table': 'r3010_evtespdesportivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r5001evtTotal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('cdretorno', models.CharField(max_length=6)),
                ('descretorno', models.CharField(max_length=255)),
                ('nrprotentr', models.CharField(max_length=49, null=True, blank=True)),
                ('dhprocess', models.DateField()),
                ('tpev', models.CharField(max_length=6)),
                ('idev', models.CharField(max_length=36)),
                ('hash', models.CharField(max_length=60)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('criado_por', models.ForeignKey(related_name='r5001evttotal_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r5001evttotal_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_evttotal', models.ForeignKey(related_name='r5001evttotal_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True)),
            ],
            options={
                'ordering': ['identidade', 'perapur', 'tpinsc', 'nrinsc', 'cdretorno', 'descretorno', 'nrprotentr', 'dhprocess', 'tpev', 'idev', 'hash'],
                'db_table': 'r5001_evttotal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r5011evtTotalContrib',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('perapur', models.CharField(max_length=10)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('cdretorno', models.CharField(max_length=6)),
                ('descretorno', models.CharField(max_length=255)),
                ('nrprotentr', models.CharField(max_length=49)),
                ('dhprocess', models.DateField()),
                ('tpev', models.CharField(max_length=6)),
                ('idev', models.CharField(max_length=36)),
                ('hash', models.CharField(max_length=60)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('criado_por', models.ForeignKey(related_name='r5011evttotalcontrib_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r5011evttotalcontrib_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_evttotal', models.ForeignKey(related_name='r5011evttotalcontrib_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True)),
                ('retornos_evttotalcontrib', models.ForeignKey(related_name='r5011evttotalcontrib_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True)),
                ('transmissor_lote_efdreinf', models.ForeignKey(related_name='r5011evttotalcontrib_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True)),
            ],
            options={
                'ordering': ['identidade', 'perapur', 'tpinsc', 'nrinsc', 'cdretorno', 'descretorno', 'nrprotentr', 'dhprocess', 'tpev', 'idev', 'hash'],
                'db_table': 'r5011_evttotalcontrib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r9000evtExclusao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.CharField(default=b'v1_03_02', max_length=20, choices=[(b'v1_03_02', 'Vers\xe3o 1.03.02')])),
                ('identidade', models.CharField(max_length=36, null=True, blank=True)),
                ('tpamb', models.IntegerField(choices=[(1, '1 - Produ\xe7\xe3o'), (2, '2 - Produ\xe7\xe3o restrita')])),
                ('procemi', models.IntegerField(default=1, choices=[(1, '1 - Aplicativo do contribuinte'), (2, '2 - Aplicativo governamental')])),
                ('verproc', models.CharField(max_length=20)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('tpevento', models.CharField(max_length=6)),
                ('nrrecevt', models.CharField(max_length=52)),
                ('perapur', models.CharField(max_length=10)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('validacoes', models.TextField(null=True, blank=True)),
                ('validacao_precedencia', models.IntegerField(blank=True, null=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('ocorrencias', models.TextField(null=True, blank=True)),
                ('arquivo', models.CharField(max_length=200, null=True, blank=True)),
                ('arquivo_original', models.IntegerField(default=0, null=True, blank=True, choices=[(0, 'N\xe3o'), (1, 'Sim')])),
                ('status', models.IntegerField(default=0, choices=[(0, 'Cadastrado'), (1, 'Importado'), (10, 'Assinado'), (11, 'Gerado'), (12, 'Retorno'), (13, 'Erro - Ocorr\xeancias'), (14, 'Processado'), (2, 'Duplicado'), (3, 'Erro na valida\xe7\xe3o'), (4, 'Validado'), (5, 'Erro no envio'), (6, 'Aguardando envio'), (7, 'Enviado'), (8, 'Erro na consulta'), (9, 'Consultado')])),
                ('cdretorno', models.CharField(max_length=6, null=True, blank=True)),
                ('descretorno', models.CharField(max_length=255, null=True, blank=True)),
                ('dhprocess', models.DateTimeField(null=True, blank=True)),
                ('criado_por', models.ForeignKey(related_name='r9000evtexclusao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r9000evtexclusao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('retornos_evttotal', models.ForeignKey(related_name='r9000evtexclusao_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True)),
                ('retornos_evttotalcontrib', models.ForeignKey(related_name='r9000evtexclusao_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True)),
                ('transmissor_lote_efdreinf', models.ForeignKey(related_name='r9000evtexclusao_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True)),
            ],
            options={
                'ordering': ['identidade', 'tpamb', 'procemi', 'verproc', 'tpinsc', 'nrinsc', 'tpevento', 'nrrecevt', 'perapur'],
                'db_table': 'r9000_evtexclusao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='r5001evttotal',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r5001evttotal_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r5001evttotal',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r5001evttotal_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r3010evtespdesportivo',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r3010evtespdesportivo_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r3010evtespdesportivo',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r3010evtespdesportivo_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r3010evtespdesportivo',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r3010evtespdesportivo_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2099evtfechaevper',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2099evtfechaevper_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2099evtfechaevper',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2099evtfechaevper_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2099evtfechaevper',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2099evtfechaevper_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2098evtreabreevper',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2098evtreabreevper_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2098evtreabreevper',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2098evtreabreevper_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2098evtreabreevper',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2098evtreabreevper_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2070evtpgtosdivs',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2070evtpgtosdivs_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2070evtpgtosdivs',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2070evtpgtosdivs_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2070evtpgtosdivs',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2070evtpgtosdivs_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2060evtcprb',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2060evtcprb_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2060evtcprb',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2060evtcprb_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2060evtcprb',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2060evtcprb_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2050evtcomprod',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2050evtcomprod_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2050evtcomprod',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2050evtcomprod_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2050evtcomprod',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2050evtcomprod_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2040evtassocdesprep',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2040evtassocdesprep_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2040evtassocdesprep',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2040evtassocdesprep_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2040evtassocdesprep',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2040evtassocdesprep_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2030evtassocdesprec',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2030evtassocdesprec_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2030evtassocdesprec',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2030evtassocdesprec_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2030evtassocdesprec',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2030evtassocdesprec_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2020evtservprest',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2020evtservprest_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2020evtservprest',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2020evtservprest_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2020evtservprest',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2020evtservprest_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r2010evtservtom',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r2010evtservtom_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r2010evtservtom',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r2010evtservtom_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r2010evtservtom',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r2010evtservtom_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r1070evttabprocesso',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r1070evttabprocesso_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r1070evttabprocesso',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r1070evttabprocesso_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r1070evttabprocesso',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r1070evttabprocesso_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
        migrations.AddField(
            model_name='r1000evtinfocontri',
            name='retornos_evttotal',
            field=models.ForeignKey(related_name='r1000evtinfocontri_retornos_evttotal', blank=True, to='efdreinf.r5001evtTotal', null=True),
        ),
        migrations.AddField(
            model_name='r1000evtinfocontri',
            name='retornos_evttotalcontrib',
            field=models.ForeignKey(related_name='r1000evtinfocontri_retornos_evttotalcontrib', blank=True, to='efdreinf.r5011evtTotalContrib', null=True),
        ),
        migrations.AddField(
            model_name='r1000evtinfocontri',
            name='transmissor_lote_efdreinf',
            field=models.ForeignKey(related_name='r1000evtinfocontri_transmissor_lote_efdreinf', blank=True, to='mensageiro.TransmissorLoteEfdreinf', null=True),
        ),
    ]
