# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efdreinf', '0023_auto_20190602_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r1000evtinfocontri',
            name='operacao',
            field=models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True),
        ),
        migrations.AlterField(
            model_name='r1070evttabprocesso',
            name='operacao',
            field=models.IntegerField(choices=[(1, 'Incluir'), (2, 'Alterar'), (3, 'Excluir')], null=True),
        ),
    ]
