# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0003_auto_20180912_1359'),
        ('tabelas', '0003_auto_20180912_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFDReinfClassificacaoServicosPrestados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfclassificacaoservicosprestados_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfclassificacaoservicosprestados_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_classificacao_servicos_prestados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfClassificacaoTributaria',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfclassificacaotributaria_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfclassificacaotributaria_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_classificacao_tributaria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfCodigosAtividadesProdutosServicosCPRB',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('grupo', models.IntegerField(choices=[(1, 'I - Pessoas Jur\xeddicas Prestadoras de Servi\xe7os -'), (2, 'II - Pessoas Jur\xeddicas Comerciais - CR 2991-01'), (3, 'III - Pessoas Jur\xeddicas Fabricantes - CR 2991-01'), (4, 'IV - C\xf3digos Gen\xe9ricos - Outras Receitas sujeitas \xe0 CPRB - CR 2991-01')])),
                ('aliquota', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('inicio_escrituracao', models.DateField(null=True, blank=True)),
                ('ncm', models.CharField(max_length=12, null=True, blank=True)),
                ('cr', models.CharField(max_length=12, null=True, blank=True)),
                ('incidencia', models.TextField(null=True, blank=True)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfcodigosatividadesprodutosservicoscprb_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfcodigosatividadesprodutosservicoscprb_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'grupo', 'aliquota', 'inicio_escrituracao', 'ncm', 'cr', 'incidencia', 'descricao'],
                'db_table': 'efdreinf_codigos_atividades_produtos_servicos_cprb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfEventos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfeventos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfeventos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_eventos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfInformacoesBeneficiariosExterior',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfinformacoesbeneficiariosexterior_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfinformacoesbeneficiariosexterior_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_informacoes_beneficiarios_exterior',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfPagamentosCodigos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Benefici\xe1rios no Brasil'), (2, 'Benefici\xe1rios no Brasil e Justi\xe7a \u2013 RRA'), (3, 'Remessa Exterior')])),
                ('beneficiario_pf', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('beneficiario_pj', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfpagamentoscodigos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfpagamentoscodigos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'beneficiario_pf', 'beneficiario_pj', 'codigo', 'descricao'],
                'db_table': 'efdreinf_pagamentos_codigos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfPaises',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfpaises_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfpaises_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_paises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfRegrasPagamentosCodigos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('classificacao', models.IntegerField(choices=[(1, 'Benefici\xe1rios'), (2, 'Benefici\xe1rios / Justi\xe7a \u2013 RRA')])),
                ('tributacao_com_exigibilidade_suspensa', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('compensacao_imposto_por_decisao_judicial', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('rendimentos_isentos', models.CharField(max_length=10, null=True, blank=True)),
                ('deducoes', models.CharField(max_length=10, null=True, blank=True)),
                ('decimo_terceiro', models.CharField(blank=True, max_length=1, null=True, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfregraspagamentoscodigos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfregraspagamentoscodigos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['classificacao', 'tributacao_com_exigibilidade_suspensa', 'compensacao_imposto_por_decisao_judicial', 'rendimentos_isentos', 'deducoes', 'decimo_terceiro', 'codigo', 'descricao'],
                'db_table': 'efdreinf_regras_pagamentos_codigos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfRendimentosBeneficiariosExterior',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfrendimentosbeneficiariosexterior_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfrendimentosbeneficiariosexterior_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_rendimentos_beneficiarios_exterior',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EFDReinfRendimentosBeneficiariosExteriorTributacao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='efdreinfrendimentosbeneficiariosexteriortributacao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='efdreinfrendimentosbeneficiariosexteriortributacao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'efdreinf_rendimentos_beneficiarios_exterior_tributacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialAcidentesSituacoesGeradoras',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialacidentessituacoesgeradoras_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialacidentessituacoesgeradoras_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_acidentes_situacoes_geradoras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialAfastamentosMotivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialafastamentosmotivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialafastamentosmotivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao', 'data_inicio', 'data_termino'],
                'db_table': 'esocial_afastamentos_motivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialAgentesCausadoresAcidentesTrabalho',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialagentescausadoresacidentestrabalho_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialagentescausadoresacidentestrabalho_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_agentes_causadores_acidentes_trabalho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialAgentesCausadoresDoencasProfissionais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialagentescausadoresdoencasprofissionais_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialagentescausadoresdoencasprofissionais_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_agentes_causadores_doencas_profissionais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialArquivosEsocialTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialarquivosesocialtipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialarquivosesocialtipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_arquivos_esocial_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialAtividadesPericulosasInsalubresEspeciais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'ATIVIDADES COM EXPOSI\xc7\xc3O A RISCOS BIOL\xd3GICOS'), (10, 'OUTRAS ATIVIDADES'), (11, 'AUS\xcaNCIA DE CORRESPOND\xcaNCIA'), (2, 'ATIVIDADES COM EXPOSI\xc7\xc3O A RISCOS QU\xcdMICOS'), (3, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM EXPLOSIVOS'), (4, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM INFLAM\xc1VEIS'), (5, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM RADIA\xc7\xd5ES IONIZANTES OU SUBST\xc2NCIAS RADIOATIVAS'), (6, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM EXPOSI\xc7\xc3O A ROUBOS OU OUTRAS ESP\xc9CIES DE VIOL\xcaNCIA F\xcdSICA NAS ATIVIDADES PROFISSIONAIS DE SEGURAN\xc7A PESSOAL OU PATRIMONIAL'), (7, 'ATIVIDADES E OPERA\xc7\xd5ES PERIGOSAS COM ENERGIA EL\xc9TRICA'), (8, 'ATIVIDADES PERIGOSAS EM MOTOCICLETA'), (9, 'ATIVIDADES ESPECIAIS POR EXPOSI\xc7\xc3O A AGENTES F\xcdSICOS')])),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialatividadespericulosasinsalubresespeciais_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialatividadespericulosasinsalubresespeciais_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'codigo', 'descricao'],
                'db_table': 'esocial_atividades_periculosas_insalubres_especiais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialBeneficiosPrevidenciariosCessacaoMotivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialbeneficiosprevidenciarioscessacaomotivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialbeneficiosprevidenciarioscessacaomotivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_beneficios_previdenciarios_cessacao_motivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialBeneficiosPrevidenciariosTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialbeneficiosprevidenciariostipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialbeneficiosprevidenciariostipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_beneficios_previdenciarios_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialClassificacoesTributarias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialclassificacoestributarias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialclassificacoestributarias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_classificacoes_tributarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialCodificacoesAcidenteTrabalho',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialcodificacoesacidentetrabalho_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialcodificacoesacidentetrabalho_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_codificacoes_acidente_trabalho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialCodigoAliquotasFPASTerceiros',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descricao', models.TextField()),
                ('tipo_empresa', models.CharField(max_length=20)),
                ('base_calculo', models.CharField(max_length=50)),
                ('terceiros', models.CharField(max_length=20)),
                ('codigo_terceiro', models.CharField(max_length=4)),
                ('aliquota', models.DecimalField(max_digits=15, decimal_places=2)),
                ('ind_total', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialcodigoaliquotasfpasterceiros_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialcodigoaliquotasfpasterceiros_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_codigo_aliquotas_fpas_terceiros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialCompatibilidadesCategoriasClassificacoesLotacoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('classificacao_tributaria', models.TextField()),
                ('tipo_lotacao_tributaria_01', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_02', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_03', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_04', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_05', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_06', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_07', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_08', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_09', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_10', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_21', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_24', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_90', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_lotacao_tributaria_91', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialcompatibilidadescategoriasclassificacoeslotacoes_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialcompatibilidadescategoriasclassificacoeslotacoes_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'classificacao_tributaria'],
                'db_table': 'esocial_compatibilidades_categorias_classificacoes_lotacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialCompatibilidadesFPASClassificacoesTributarias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('classificacao_tributaria_01', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_02', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_03', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_04', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_06', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_07', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_08', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_09', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_10', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_11', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_13', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_14', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_21', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_22', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_60', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_70', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_80', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_85', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('classificacao_tributaria_99', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialcompatibilidadesfpasclassificacoestributarias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialcompatibilidadesfpasclassificacoestributarias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'esocial_compatibilidades_fpas_classificacoes_tributarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialCompatibilidadesLotacoesClassificacoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('tipo_classificacao_tributaria_01', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_02', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_03', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_04', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_06', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_07', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_08', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_09', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_10', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_11', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_13', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_14', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_21', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_22', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_60', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_70', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_80', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_85', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('tipo_classificacao_tributaria_99', models.CharField(max_length=1, choices=[(b'N', 'N\xe3o'), (b'S', 'Sim')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialcompatibilidadeslotacoesclassificacoes_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialcompatibilidadeslotacoesclassificacoes_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'esocial_compatibilidades_lotacoes_classificacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialDependentesTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialdependentestipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialdependentestipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_dependentes_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialDesligamentosMotivos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialdesligamentosmotivos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialdesligamentosmotivos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao', 'data_inicio', 'data_termino'],
                'db_table': 'esocial_desligamentos_motivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialFatoresRisco',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'F\xcdSICOS'), (10, 'PERICULOSO'), (11, 'ASSOCIA\xc7\xc3O DE FATORES DE RISCO'), (12, 'OUTROS FATORES DE RISCO'), (13, 'AUS\xcaNCIA DE FATORES DE RISCO'), (2, 'QU\xcdMICOS'), (3, 'BIOL\xd3GICOS'), (4, 'ERGON\xd4MICOS - BIOMEC\xc2NICOS'), (5, 'ERGON\xd4MICOS - MOBILI\xc1RIO E EQUIPAMENTOS'), (6, 'ERGON\xd4MICOS - ORGANIZACIONAIS'), (7, 'ERGON\xd4MICOS - AMBIENTAIS'), (8, 'ERGON\xd4MICOS - PSICOSSOCIAIS/COGNITIVOS'), (9, 'MEC\xc2NICOS/ACIDENTES')])),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialfatoresrisco_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialfatoresrisco_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'codigo', 'descricao'],
                'db_table': 'esocial_fatores_risco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialFinanciamentosAposentadoriasEspeciais',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialfinanciamentosaposentadoriasespeciais_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialfinanciamentosaposentadoriasespeciais_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_financiamentos_aposentadorias_especiais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialInscricoesTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialinscricoestipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialinscricoestipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_inscricoes_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialLogradourosTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=3)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esociallogradourostipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esociallogradourostipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_logradouros_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialLotacoesTributariasTipos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
                ('preenchimento_campo_nr_insc', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esociallotacoestributariastipos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esociallotacoestributariastipos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_lotacoes_tributarias_tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialNaturezasJuridicas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Administra\xe7\xe3o P\xfablica'), (2, 'Entidades Empresariais'), (3, 'Entidades sem Fins Lucrativos'), (4, 'Pessoas F\xedsicas'), (5, 'Organiza\xe7\xf5es Internacionais e Outras Institui\xe7\xf5es Extraterritoriais')])),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialnaturezasjuridicas_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialnaturezasjuridicas_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'db_table': 'esocial_naturezas_juridicas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialNaturezasLesoes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialnaturezaslesoes_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialnaturezaslesoes_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_naturezas_lesoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialNaturezasRubricas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialnaturezasrubricas_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialnaturezasrubricas_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'titulo'],
                'db_table': 'esocial_naturezas_rubricas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialPaises',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(null=True, blank=True)),
                ('data_extincao', models.DateField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialpaises_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialpaises_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'nome'],
                'db_table': 'esocial_paises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialPartesCorpoAtingidas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialpartescorpoatingidas_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialpartescorpoatingidas_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_partes_corpo_atingidas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialProcedimentosDiagnosticos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialprocedimentosdiagnosticos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialprocedimentosdiagnosticos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_procedimentos_diagnosticos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialProgramasPlanosDocumentos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialprogramasplanosdocumentos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialprogramasplanosdocumentos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_programas_planos_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialTrabalhadoresCategorias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Empregado e Trabalhador Tempor\xe1rio'), (2, 'Avulso'), (3, 'Agente P\xfablico'), (4, 'Cess\xe3o'), (5, 'Contribuinte Individual'), (6, 'Bolsistas')])),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialtrabalhadorescategorias_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialtrabalhadorescategorias_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['grupo', 'codigo', 'descricao'],
                'db_table': 'esocial_trabalhadores_categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='eSocialTreinamentosCapacitacoesExerciciosSimulados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='esocialtreinamentoscapacitacoesexerciciossimulados_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='esocialtreinamentoscapacitacoesexerciciossimulados_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['codigo', 'descricao'],
                'db_table': 'esocial_treinamentos_capacitacoes_exercicios_simulados',
                'managed': True,
            },
        ),
    ]
