# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2416', '0005_auto_20190202_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s2416homologtc',
            options={'managed': True, 'ordering': ['s2416_evtcdbenalt', 'nratolegal'], 'permissions': (('can_view_s2416_homologtc', 'Can view s2416_homologtc'),)},
        ),
        migrations.AlterModelOptions(
            name='s2416infopenmorte',
            options={'managed': True, 'ordering': ['s2416_evtcdbenalt', 'tppenmorte'], 'permissions': (('can_view_s2416_infopenmorte', 'Can view s2416_infopenmorte'),)},
        ),
        migrations.AlterModelOptions(
            name='s2416suspensao',
            options={'managed': True, 'ordering': ['s2416_evtcdbenalt', 'mtvsuspensao'], 'permissions': (('can_view_s2416_suspensao', 'Can view s2416_suspensao'),)},
        ),
    ]
