# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0001_initial'),
        ('efdreinf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='r2070compJud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vlrcompanocalend', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('vlrcompanoant', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070compjud_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070compjud_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'vlrcompanocalend', 'vlrcompanoant'],
                'db_table': 'r2070_compjud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070depJudicial',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vlrdepjudicial', models.DecimalField(max_length=14, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070depjudicial_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070depjudicial_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'vlrdepjudicial'],
                'db_table': 'r2070_depjudicial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070detCompet',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indperreferencia', models.IntegerField(choices=[(1, '1 - Folha de Pagamento Mensal'), (2, '2 - Folha do D\xe9cimo Terceiro Sal\xe1rio')])),
                ('perrefpagto', models.CharField(max_length=7)),
                ('vlrrendtributavel', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070detcompet_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070detcompet_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'indperreferencia', 'perrefpagto', 'vlrrendtributavel'],
                'db_table': 'r2070_detcompet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070detDeducao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indtpdeducao', models.IntegerField(choices=[(1, '1 - Previd\xeancia Oficial'), (2, '2 - Previd\xeancia Privada'), (3, '3 - Fapi'), (4, '4 - Funpresp'), (5, '5 - Pens\xe3o Aliment\xedcia'), (6, '6 - Dependentes')])),
                ('vlrdeducao', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070detdeducao_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070detdeducao_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'indtpdeducao', 'vlrdeducao'],
                'db_table': 'r2070_detdeducao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070ideEstab',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinsc', models.IntegerField(choices=[(1, '1 - CNPJ'), (1, '1 - CNPJ'), (2, '2 - CPF'), (2, '2 - CPF')])),
                ('nrinsc', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070ideestab_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070ideestab_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_evtpgtosdivs', models.ForeignKey(related_name='r2070ideestab_r2070_evtpgtosdivs', to='efdreinf.r2070evtPgtosDivs')),
            ],
            options={
                'ordering': ['r2070_evtpgtosdivs', 'tpinsc', 'nrinsc'],
                'db_table': 'r2070_ideestab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoMolestia',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dtlaudo', models.DateField()),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070infomolestia_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070infomolestia_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_evtpgtosdivs', models.OneToOneField(related_name='r2070infomolestia_r2070_evtpgtosdivs', to='efdreinf.r2070evtPgtosDivs')),
            ],
            options={
                'ordering': ['r2070_evtpgtosdivs', 'dtlaudo'],
                'db_table': 'r2070_infomolestia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoProcJud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nrprocjud', models.CharField(max_length=21)),
                ('codsusp', models.IntegerField(null=True, blank=True)),
                ('indorigemrecursos', models.IntegerField(choices=[(1, '1 - Recursos do pr\xf3prio declarante'), (2, '2 - Recursos de terceiros - Declarante \xe9 a Institui\xe7\xe3o Financeira respons\xe1vel apenas pelo repasse dos valores')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070infoprocjud_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070infoprocjud_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'nrprocjud', 'codsusp', 'indorigemrecursos'],
                'db_table': 'r2070_infoprocjud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoProcJuddespProcJud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vlrdespcustas', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrdespadvogados', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070infoprocjuddespprocjud_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070infoprocjuddespprocjud_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_infoprocjud', models.OneToOneField(related_name='r2070infoprocjuddespprocjud_r2070_infoprocjud', to='r2070.r2070infoProcJud')),
            ],
            options={
                'ordering': ['r2070_infoprocjud', 'vlrdespcustas', 'vlrdespadvogados'],
                'db_table': 'r2070_infoprocjud_despprocjud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoProcJudideAdvogado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinscadvogado', models.IntegerField(choices=[(1, '1 - Pessoa Jur\xeddica'), (2, '2 - Pessoa F\xedsica')])),
                ('nrinscadvogado', models.CharField(max_length=14)),
                ('vlradvogado', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070infoprocjudideadvogado_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070infoprocjudideadvogado_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_infoprocjud_despprocjud', models.ForeignKey(related_name='r2070infoprocjudideadvogado_r2070_infoprocjud_despprocjud', to='r2070.r2070infoProcJuddespProcJud')),
            ],
            options={
                'ordering': ['r2070_infoprocjud_despprocjud', 'tpinscadvogado', 'nrinscadvogado', 'vlradvogado'],
                'db_table': 'r2070_infoprocjud_ideadvogado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoProcJudorigemRecursos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cnpjorigemrecursos', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070infoprocjudorigemrecursos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070infoprocjudorigemrecursos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_infoprocjud', models.OneToOneField(related_name='r2070infoprocjudorigemrecursos_r2070_infoprocjud', to='r2070.r2070infoProcJud')),
            ],
            options={
                'ordering': ['r2070_infoprocjud', 'cnpjorigemrecursos'],
                'db_table': 'r2070_infoprocjud_origemrecursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoResidExt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('paisresid', models.CharField(max_length=3)),
                ('dsclograd', models.CharField(max_length=80)),
                ('nrlograd', models.CharField(max_length=10, null=True, blank=True)),
                ('complem', models.CharField(max_length=30, null=True, blank=True)),
                ('bairro', models.CharField(max_length=60, null=True, blank=True)),
                ('cidade', models.CharField(max_length=30, null=True, blank=True)),
                ('codpostal', models.CharField(max_length=12, null=True, blank=True)),
                ('indnif', models.IntegerField(choices=[(1, '1 - Benefici\xe1rio com NIF'), (2, '2 - Benefici\xe1rio dispensado do NIF'), (3, '3 - Pa\xeds n\xe3o exige NIF')])),
                ('nifbenef', models.CharField(max_length=20, null=True, blank=True)),
                ('relfontepagad', models.CharField(max_length=3, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070inforesidext_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070inforesidext_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_evtpgtosdivs', models.OneToOneField(related_name='r2070inforesidext_r2070_evtpgtosdivs', to='efdreinf.r2070evtPgtosDivs')),
            ],
            options={
                'ordering': ['r2070_evtpgtosdivs', 'paisresid', 'dsclograd', 'nrlograd', 'complem', 'bairro', 'cidade', 'codpostal', 'indnif', 'nifbenef', 'relfontepagad'],
                'db_table': 'r2070_inforesidext',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoRRA',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpprocrra', models.IntegerField(blank=True, null=True, choices=[(1, '1 - Administrativo'), (2, '2 - Judicial')])),
                ('nrprocrra', models.CharField(max_length=21, null=True, blank=True)),
                ('codsusp', models.IntegerField(null=True, blank=True)),
                ('natrra', models.CharField(max_length=50, null=True, blank=True)),
                ('qtdmesesrra', models.IntegerField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070inforra_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070inforra_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'tpprocrra', 'nrprocrra', 'codsusp', 'natrra', 'qtdmesesrra'],
                'db_table': 'r2070_inforra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoRRAdespProcJud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vlrdespcustas', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrdespadvogados', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070inforradespprocjud_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070inforradespprocjud_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_inforra', models.OneToOneField(related_name='r2070inforradespprocjud_r2070_inforra', to='r2070.r2070infoRRA')),
            ],
            options={
                'ordering': ['r2070_inforra', 'vlrdespcustas', 'vlrdespadvogados'],
                'db_table': 'r2070_inforra_despprocjud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070infoRRAideAdvogado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinscadvogado', models.IntegerField(choices=[(1, '1 - Pessoa Jur\xeddica'), (2, '2 - Pessoa F\xedsica')])),
                ('nrinscadvogado', models.CharField(max_length=14)),
                ('vlradvogado', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070inforraideadvogado_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070inforraideadvogado_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_inforra_despprocjud', models.ForeignKey(related_name='r2070inforraideadvogado_r2070_inforra_despprocjud', to='r2070.r2070infoRRAdespProcJud')),
            ],
            options={
                'ordering': ['r2070_inforra_despprocjud', 'tpinscadvogado', 'nrinscadvogado', 'vlradvogado'],
                'db_table': 'r2070_inforra_ideadvogado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoPF',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dtpgto', models.DateField()),
                ('indsuspexig', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('inddecterceiro', models.CharField(max_length=1, choices=[(b'N', 'N - N\xe3o'), (b'S', 'S - Sim')])),
                ('vlrrendtributavel', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrirrf', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtopf_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtopf_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtoresidbr', 'dtpgto', 'indsuspexig', 'inddecterceiro', 'vlrrendtributavel', 'vlrirrf'],
                'db_table': 'r2070_pgtopf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoPJ',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dtpagto', models.DateField()),
                ('vlrrendtributavel', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrret', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtopj_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtopj_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtoresidbr', 'dtpagto', 'vlrrendtributavel', 'vlrret'],
                'db_table': 'r2070_pgtopj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoPJdespProcJud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vlrdespcustas', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrdespadvogados', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtopjdespprocjud_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtopjdespprocjud_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
            ],
            options={
                'ordering': ['r2070_pgtopj_infoprocjud', 'vlrdespcustas', 'vlrdespadvogados'],
                'db_table': 'r2070_pgtopj_despprocjud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoPJideAdvogado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpinscadvogado', models.IntegerField(choices=[(1, '1 - Pessoa Jur\xeddica'), (2, '2 - Pessoa F\xedsica')])),
                ('nrinscadvogado', models.CharField(max_length=14)),
                ('vlradvogado', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtopjideadvogado_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtopjideadvogado_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_pgtopj_despprocjud', models.ForeignKey(related_name='r2070pgtopjideadvogado_r2070_pgtopj_despprocjud', to='r2070.r2070pgtoPJdespProcJud')),
            ],
            options={
                'ordering': ['r2070_pgtopj_despprocjud', 'tpinscadvogado', 'nrinscadvogado', 'vlradvogado'],
                'db_table': 'r2070_pgtopj_ideadvogado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoPJinfoProcJud',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nrprocjud', models.CharField(max_length=21)),
                ('codsusp', models.IntegerField(null=True, blank=True)),
                ('indorigemrecursos', models.IntegerField(choices=[(1, '1 - Recursos do pr\xf3prio declarante'), (2, '2 - Recursos de terceiros - Declarante \xe9 a Institui\xe7\xe3o Financeira respons\xe1vel apenas pelo repasse dos valores')])),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtopjinfoprocjud_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtopjinfoprocjud_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_pgtopj', models.ForeignKey(related_name='r2070pgtopjinfoprocjud_r2070_pgtopj', to='r2070.r2070pgtoPJ')),
            ],
            options={
                'ordering': ['r2070_pgtopj', 'nrprocjud', 'codsusp', 'indorigemrecursos'],
                'db_table': 'r2070_pgtopj_infoprocjud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoPJorigemRecursos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cnpjorigemrecursos', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtopjorigemrecursos_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtopjorigemrecursos_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_pgtopj_infoprocjud', models.OneToOneField(related_name='r2070pgtopjorigemrecursos_r2070_pgtopj_infoprocjud', to='r2070.r2070pgtoPJinfoProcJud')),
            ],
            options={
                'ordering': ['r2070_pgtopj_infoprocjud', 'cnpjorigemrecursos'],
                'db_table': 'r2070_pgtopj_origemrecursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoResidBR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtoresidbr_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtoresidbr_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_ideestab', models.OneToOneField(related_name='r2070pgtoresidbr_r2070_ideestab', to='r2070.r2070ideEstab')),
            ],
            options={
                'ordering': ['r2070_ideestab'],
                'db_table': 'r2070_pgtoresidbr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070pgtoResidExt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dtpagto', models.DateField()),
                ('tprendimento', models.IntegerField()),
                ('formatributacao', models.CharField(max_length=2)),
                ('vlrpgto', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('vlrret', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070pgtoresidext_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070pgtoresidext_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_ideestab', models.OneToOneField(related_name='r2070pgtoresidext_r2070_ideestab', to='r2070.r2070ideEstab')),
            ],
            options={
                'ordering': ['r2070_ideestab', 'dtpagto', 'tprendimento', 'formatributacao', 'vlrpgto', 'vlrret'],
                'db_table': 'r2070_pgtoresidext',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='r2070rendIsento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tpisencao', models.IntegerField(choices=[(1, '1 - Parcela Isenta 65 anos'), (10, '10 - Bolsa de estudo recebida por m\xe9dico-residente'), (11, '11 - Complementa\xe7\xe3o de aposentadoria, correspondente \xe0s contribui\xe7\xf5es efetuadas no per\xedodo de 01/01/1989 a 31/12/1995'), (2, '2 - Di\xe1ria e Ajuda de Custo'), (3, '3 - Indeniza\xe7\xe3o e rescis\xe3o de contrato, inclusive a t\xedtulo de PDV'), (4, '4 - Abono pecuni\xe1rio'), (5, '5 - Outros (especificar)'), (6, '6 - Lucros e dividendos pagos a partir de 1996'), (7, '7 - Valores pagos a titular ou s\xf3cio de microempresa ou empresa de pequeno porte, exceto pr\xf3-labore e alugueis'), (8, '8 - Pens\xe3o, aposentadoria ou reforma por mol\xe9stia grave ou acidente em servi\xe7o'), (9, '9 - Benef\xedcios indiretos e/ou reembolso de despesas recebidas por volunt\xe1rio da copa do mundo ou da copa das confedera\xe7\xf5es')])),
                ('vlrisento', models.DecimalField(max_length=14, max_digits=15, decimal_places=2)),
                ('descrendimento', models.CharField(max_length=100, null=True, blank=True)),
                ('criado_em', models.DateTimeField(blank=True)),
                ('modificado_em', models.DateTimeField(null=True, blank=True)),
                ('excluido', models.BooleanField()),
                ('criado_por', models.ForeignKey(related_name='r2070rendisento_criado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('modificado_por', models.ForeignKey(related_name='r2070rendisento_modificado_por', blank=True, to='controle_de_acesso.Usuarios', null=True)),
                ('r2070_pgtopf', models.ForeignKey(related_name='r2070rendisento_r2070_pgtopf', to='r2070.r2070pgtoPF')),
            ],
            options={
                'ordering': ['r2070_pgtopf', 'tpisencao', 'vlrisento', 'descrendimento'],
                'db_table': 'r2070_rendisento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='r2070pgtopjdespprocjud',
            name='r2070_pgtopj_infoprocjud',
            field=models.OneToOneField(related_name='r2070pgtopjdespprocjud_r2070_pgtopj_infoprocjud', to='r2070.r2070pgtoPJinfoProcJud'),
        ),
        migrations.AddField(
            model_name='r2070pgtopj',
            name='r2070_pgtoresidbr',
            field=models.ForeignKey(related_name='r2070pgtopj_r2070_pgtoresidbr', to='r2070.r2070pgtoResidBR'),
        ),
        migrations.AddField(
            model_name='r2070pgtopf',
            name='r2070_pgtoresidbr',
            field=models.ForeignKey(related_name='r2070pgtopf_r2070_pgtoresidbr', to='r2070.r2070pgtoResidBR'),
        ),
        migrations.AddField(
            model_name='r2070inforra',
            name='r2070_pgtopf',
            field=models.ForeignKey(related_name='r2070inforra_r2070_pgtopf', to='r2070.r2070pgtoPF'),
        ),
        migrations.AddField(
            model_name='r2070infoprocjud',
            name='r2070_pgtopf',
            field=models.ForeignKey(related_name='r2070infoprocjud_r2070_pgtopf', to='r2070.r2070pgtoPF'),
        ),
        migrations.AddField(
            model_name='r2070detdeducao',
            name='r2070_pgtopf',
            field=models.ForeignKey(related_name='r2070detdeducao_r2070_pgtopf', to='r2070.r2070pgtoPF'),
        ),
        migrations.AddField(
            model_name='r2070detcompet',
            name='r2070_pgtopf',
            field=models.ForeignKey(related_name='r2070detcompet_r2070_pgtopf', to='r2070.r2070pgtoPF'),
        ),
        migrations.AddField(
            model_name='r2070depjudicial',
            name='r2070_pgtopf',
            field=models.OneToOneField(related_name='r2070depjudicial_r2070_pgtopf', to='r2070.r2070pgtoPF'),
        ),
        migrations.AddField(
            model_name='r2070compjud',
            name='r2070_pgtopf',
            field=models.OneToOneField(related_name='r2070compjud_r2070_pgtopf', to='r2070.r2070pgtoPF'),
        ),
    ]
