# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r2070', '0006_auto_20190202_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r2070compjud',
            options={'managed': True, 'ordering': ['r2070_pgtopf'], 'permissions': (('can_view_r2070_compjud', 'Can view r2070_compjud'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070depjudicial',
            options={'managed': True, 'ordering': ['r2070_pgtopf'], 'permissions': (('can_view_r2070_depjudicial', 'Can view r2070_depjudicial'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070detcompet',
            options={'managed': True, 'ordering': ['r2070_pgtopf', 'indperreferencia', 'perrefpagto', 'vlrrendtributavel'], 'permissions': (('can_view_r2070_detcompet', 'Can view r2070_detcompet'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070detdeducao',
            options={'managed': True, 'ordering': ['r2070_pgtopf', 'indtpdeducao', 'vlrdeducao'], 'permissions': (('can_view_r2070_detdeducao', 'Can view r2070_detdeducao'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070ideestab',
            options={'managed': True, 'ordering': ['r2070_evtpgtosdivs', 'tpinsc', 'nrinsc'], 'permissions': (('can_view_r2070_ideestab', 'Can view r2070_ideestab'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070infomolestia',
            options={'managed': True, 'ordering': ['r2070_evtpgtosdivs', 'dtlaudo'], 'permissions': (('can_view_r2070_infomolestia', 'Can view r2070_infomolestia'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070infoprocjud',
            options={'managed': True, 'ordering': ['r2070_pgtopf', 'nrprocjud', 'indorigemrecursos'], 'permissions': (('can_view_r2070_infoprocjud', 'Can view r2070_infoprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070infoprocjuddespprocjud',
            options={'managed': True, 'ordering': ['r2070_infoprocjud', 'vlrdespcustas', 'vlrdespadvogados'], 'permissions': (('can_view_r2070_infoprocjud_despprocjud', 'Can view r2070_infoprocjud_despprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070infoprocjudideadvogado',
            options={'managed': True, 'ordering': ['r2070_infoprocjud_despprocjud', 'tpinscadvogado', 'nrinscadvogado', 'vlradvogado'], 'permissions': (('can_view_r2070_infoprocjud_ideadvogado', 'Can view r2070_infoprocjud_ideadvogado'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070infoprocjudorigemrecursos',
            options={'managed': True, 'ordering': ['r2070_infoprocjud', 'cnpjorigemrecursos'], 'permissions': (('can_view_r2070_infoprocjud_origemrecursos', 'Can view r2070_infoprocjud_origemrecursos'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070inforesidext',
            options={'managed': True, 'ordering': ['r2070_evtpgtosdivs', 'paisresid', 'dsclograd', 'indnif'], 'permissions': (('can_view_r2070_inforesidext', 'Can view r2070_inforesidext'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070inforra',
            options={'managed': True, 'ordering': ['r2070_pgtopf'], 'permissions': (('can_view_r2070_inforra', 'Can view r2070_inforra'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070inforradespprocjud',
            options={'managed': True, 'ordering': ['r2070_inforra', 'vlrdespcustas', 'vlrdespadvogados'], 'permissions': (('can_view_r2070_inforra_despprocjud', 'Can view r2070_inforra_despprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070inforraideadvogado',
            options={'managed': True, 'ordering': ['r2070_inforra_despprocjud', 'tpinscadvogado', 'nrinscadvogado', 'vlradvogado'], 'permissions': (('can_view_r2070_inforra_ideadvogado', 'Can view r2070_inforra_ideadvogado'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtopf',
            options={'managed': True, 'ordering': ['r2070_ideestab', 'dtpgto', 'indsuspexig', 'inddecterceiro', 'vlrrendtributavel', 'vlrirrf'], 'permissions': (('can_view_r2070_pgtopf', 'Can view r2070_pgtopf'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtopj',
            options={'managed': True, 'ordering': ['r2070_ideestab', 'dtpagto', 'vlrrendtributavel', 'vlrret'], 'permissions': (('can_view_r2070_pgtopj', 'Can view r2070_pgtopj'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtopjdespprocjud',
            options={'managed': True, 'ordering': ['r2070_pgtopj_infoprocjud', 'vlrdespcustas', 'vlrdespadvogados'], 'permissions': (('can_view_r2070_pgtopj_despprocjud', 'Can view r2070_pgtopj_despprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtopjideadvogado',
            options={'managed': True, 'ordering': ['r2070_pgtopj_despprocjud', 'tpinscadvogado', 'nrinscadvogado', 'vlradvogado'], 'permissions': (('can_view_r2070_pgtopj_ideadvogado', 'Can view r2070_pgtopj_ideadvogado'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtopjinfoprocjud',
            options={'managed': True, 'ordering': ['r2070_pgtopj', 'nrprocjud', 'indorigemrecursos'], 'permissions': (('can_view_r2070_pgtopj_infoprocjud', 'Can view r2070_pgtopj_infoprocjud'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtopjorigemrecursos',
            options={'managed': True, 'ordering': ['r2070_pgtopj_infoprocjud', 'cnpjorigemrecursos'], 'permissions': (('can_view_r2070_pgtopj_origemrecursos', 'Can view r2070_pgtopj_origemrecursos'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070pgtoresidext',
            options={'managed': True, 'ordering': ['r2070_ideestab', 'dtpagto', 'tprendimento', 'formatributacao', 'vlrpgto', 'vlrret'], 'permissions': (('can_view_r2070_pgtoresidext', 'Can view r2070_pgtoresidext'),)},
        ),
        migrations.AlterModelOptions(
            name='r2070rendisento',
            options={'managed': True, 'ordering': ['r2070_pgtopf', 'tpisencao', 'vlrisento'], 'permissions': (('can_view_r2070_rendisento', 'Can view r2070_rendisento'),)},
        ),
    ]
