# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1000', '0016_auto_20190530_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1000alteracao',
            options={'managed': True, 'ordering': ['s1000_evtinfoempregador', 'inivalid', 'nmrazao', 'classtrib', 'inddesfolha', 'indoptregeletron', 'indett', 'nmctt', 'cpfctt'], 'permissions': (('can_view_s1000alteracao', 'Can view S1000ALTERACAO'), ('can_view_menu_s1000alteracao', 'Can view menu S1000ALTERACAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaodadosisencao',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'ideminlei', 'nrcertif', 'dtemiscertif', 'dtvenccertif'], 'permissions': (('can_view_s1000alteracaodadosIsencao', 'Can view S1000ALTERACAODADOSISENCAO'), ('can_view_menu_s1000alteracaodadosIsencao', 'Can view menu S1000ALTERACAODADOSISENCAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoefr',
            options={'managed': True, 'ordering': ['s1000_alteracao_infoop', 'ideefr', 'indrpps', 'prevcomp'], 'permissions': (('can_view_s1000alteracaoinfoEFR', 'Can view S1000ALTERACAOINFOEFR'), ('can_view_menu_s1000alteracaoinfoEFR', 'Can view menu S1000ALTERACAOINFOEFR'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoente',
            options={'managed': True, 'ordering': ['s1000_alteracao_infoop', 'nmente', 'uf', 'indrpps', 'subteto', 'vrsubteto'], 'permissions': (('can_view_s1000alteracaoinfoEnte', 'Can view S1000ALTERACAOINFOENTE'), ('can_view_menu_s1000alteracaoinfoEnte', 'Can view menu S1000ALTERACAOINFOENTE'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoop',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'nrsiafi', 'indugrpps', 'poderop', 'vrtetorem', 'ideefr'], 'permissions': (('can_view_s1000alteracaoinfoOP', 'Can view S1000ALTERACAOINFOOP'), ('can_view_menu_s1000alteracaoinfoOP', 'Can view menu S1000ALTERACAOINFOOP'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaoinfoorginternacional',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'indacordoisenmulta'], 'permissions': (('can_view_s1000alteracaoinfoOrgInternacional', 'Can view S1000ALTERACAOINFOORGINTERNACIONAL'), ('can_view_menu_s1000alteracaoinfoOrgInternacional', 'Can view menu S1000ALTERACAOINFOORGINTERNACIONAL'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaonovavalidade',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'inivalid'], 'permissions': (('can_view_s1000alteracaonovaValidade', 'Can view S1000ALTERACAONOVAVALIDADE'), ('can_view_menu_s1000alteracaonovaValidade', 'Can view menu S1000ALTERACAONOVAVALIDADE'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaosituacaopf',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'indsitpf'], 'permissions': (('can_view_s1000alteracaosituacaoPF', 'Can view S1000ALTERACAOSITUACAOPF'), ('can_view_menu_s1000alteracaosituacaoPF', 'Can view menu S1000ALTERACAOSITUACAOPF'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaosituacaopj',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'indsitpj'], 'permissions': (('can_view_s1000alteracaosituacaoPJ', 'Can view S1000ALTERACAOSITUACAOPJ'), ('can_view_menu_s1000alteracaosituacaoPJ', 'Can view menu S1000ALTERACAOSITUACAOPJ'))},
        ),
        migrations.AlterModelOptions(
            name='s1000alteracaosoftwarehouse',
            options={'managed': True, 'ordering': ['s1000_alteracao', 'cnpjsofthouse', 'nmrazao', 'nmcont', 'telefone'], 'permissions': (('can_view_s1000alteracaosoftwareHouse', 'Can view S1000ALTERACAOSOFTWAREHOUSE'), ('can_view_menu_s1000alteracaosoftwareHouse', 'Can view menu S1000ALTERACAOSOFTWAREHOUSE'))},
        ),
        migrations.AlterModelOptions(
            name='s1000exclusao',
            options={'managed': True, 'ordering': ['s1000_evtinfoempregador', 'inivalid'], 'permissions': (('can_view_s1000exclusao', 'Can view S1000EXCLUSAO'), ('can_view_menu_s1000exclusao', 'Can view menu S1000EXCLUSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusao',
            options={'managed': True, 'ordering': ['s1000_evtinfoempregador', 'inivalid', 'nmrazao', 'classtrib', 'inddesfolha', 'indoptregeletron', 'indett', 'nmctt', 'cpfctt'], 'permissions': (('can_view_s1000inclusao', 'Can view S1000INCLUSAO'), ('can_view_menu_s1000inclusao', 'Can view menu S1000INCLUSAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaodadosisencao',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'ideminlei', 'nrcertif', 'dtemiscertif', 'dtvenccertif'], 'permissions': (('can_view_s1000inclusaodadosIsencao', 'Can view S1000INCLUSAODADOSISENCAO'), ('can_view_menu_s1000inclusaodadosIsencao', 'Can view menu S1000INCLUSAODADOSISENCAO'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoefr',
            options={'managed': True, 'ordering': ['s1000_inclusao_infoop', 'ideefr', 'indrpps', 'prevcomp'], 'permissions': (('can_view_s1000inclusaoinfoEFR', 'Can view S1000INCLUSAOINFOEFR'), ('can_view_menu_s1000inclusaoinfoEFR', 'Can view menu S1000INCLUSAOINFOEFR'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoente',
            options={'managed': True, 'ordering': ['s1000_inclusao_infoop', 'nmente', 'uf', 'indrpps', 'subteto', 'vrsubteto'], 'permissions': (('can_view_s1000inclusaoinfoEnte', 'Can view S1000INCLUSAOINFOENTE'), ('can_view_menu_s1000inclusaoinfoEnte', 'Can view menu S1000INCLUSAOINFOENTE'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoop',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'nrsiafi', 'indugrpps', 'poderop', 'vrtetorem', 'ideefr'], 'permissions': (('can_view_s1000inclusaoinfoOP', 'Can view S1000INCLUSAOINFOOP'), ('can_view_menu_s1000inclusaoinfoOP', 'Can view menu S1000INCLUSAOINFOOP'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaoinfoorginternacional',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'indacordoisenmulta'], 'permissions': (('can_view_s1000inclusaoinfoOrgInternacional', 'Can view S1000INCLUSAOINFOORGINTERNACIONAL'), ('can_view_menu_s1000inclusaoinfoOrgInternacional', 'Can view menu S1000INCLUSAOINFOORGINTERNACIONAL'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaosituacaopf',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'indsitpf'], 'permissions': (('can_view_s1000inclusaosituacaoPF', 'Can view S1000INCLUSAOSITUACAOPF'), ('can_view_menu_s1000inclusaosituacaoPF', 'Can view menu S1000INCLUSAOSITUACAOPF'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaosituacaopj',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'indsitpj'], 'permissions': (('can_view_s1000inclusaosituacaoPJ', 'Can view S1000INCLUSAOSITUACAOPJ'), ('can_view_menu_s1000inclusaosituacaoPJ', 'Can view menu S1000INCLUSAOSITUACAOPJ'))},
        ),
        migrations.AlterModelOptions(
            name='s1000inclusaosoftwarehouse',
            options={'managed': True, 'ordering': ['s1000_inclusao', 'cnpjsofthouse', 'nmrazao', 'nmcont', 'telefone'], 'permissions': (('can_view_s1000inclusaosoftwareHouse', 'Can view S1000INCLUSAOSOFTWAREHOUSE'), ('can_view_menu_s1000inclusaosoftwareHouse', 'Can view menu S1000INCLUSAOSOFTWAREHOUSE'))},
        ),
    ]
