# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s5001', '0017_auto_20190531_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s5001calcterc',
            options={'managed': True, 'ordering': ['s5001_infocategincid', 'tpcr', 'vrcssegterc', 'vrdescterc'], 'permissions': (('can_see_list_s5001calcTerc', 'Pode ver listagem do modelo S5001CALCTERC'), ('can_see_data_s5001calcTerc', 'Pode visualizar o conte\xfado do modelo S5001CALCTERC'), ('can_see_menu_s5001calcTerc', 'Pode visualizar no menu o modelo S5001CALCTERC'), ('can_print_list_s5001calcTerc', 'Pode imprimir listagem do modelo S5001CALCTERC'), ('can_print_data_s5001calcTerc', 'Pode imprimir o conte\xfado do modelo S5001CALCTERC'))},
        ),
        migrations.AlterModelOptions(
            name='s5001ideestablot',
            options={'managed': True, 'ordering': ['s5001_infocp', 'tpinsc', 'nrinsc', 'codlotacao'], 'permissions': (('can_see_list_s5001ideEstabLot', 'Pode ver listagem do modelo S5001IDEESTABLOT'), ('can_see_data_s5001ideEstabLot', 'Pode visualizar o conte\xfado do modelo S5001IDEESTABLOT'), ('can_see_menu_s5001ideEstabLot', 'Pode visualizar no menu o modelo S5001IDEESTABLOT'), ('can_print_list_s5001ideEstabLot', 'Pode imprimir listagem do modelo S5001IDEESTABLOT'), ('can_print_data_s5001ideEstabLot', 'Pode imprimir o conte\xfado do modelo S5001IDEESTABLOT'))},
        ),
        migrations.AlterModelOptions(
            name='s5001infobasecs',
            options={'managed': True, 'ordering': ['s5001_infocategincid', 'ind13', 'tpvalor', 'valor'], 'permissions': (('can_see_list_s5001infoBaseCS', 'Pode ver listagem do modelo S5001INFOBASECS'), ('can_see_data_s5001infoBaseCS', 'Pode visualizar o conte\xfado do modelo S5001INFOBASECS'), ('can_see_menu_s5001infoBaseCS', 'Pode visualizar no menu o modelo S5001INFOBASECS'), ('can_print_list_s5001infoBaseCS', 'Pode imprimir listagem do modelo S5001INFOBASECS'), ('can_print_data_s5001infoBaseCS', 'Pode imprimir o conte\xfado do modelo S5001INFOBASECS'))},
        ),
        migrations.AlterModelOptions(
            name='s5001infocategincid',
            options={'managed': True, 'ordering': ['s5001_ideestablot', 'codcateg'], 'permissions': (('can_see_list_s5001infoCategIncid', 'Pode ver listagem do modelo S5001INFOCATEGINCID'), ('can_see_data_s5001infoCategIncid', 'Pode visualizar o conte\xfado do modelo S5001INFOCATEGINCID'), ('can_see_menu_s5001infoCategIncid', 'Pode visualizar no menu o modelo S5001INFOCATEGINCID'), ('can_print_list_s5001infoCategIncid', 'Pode imprimir listagem do modelo S5001INFOCATEGINCID'), ('can_print_data_s5001infoCategIncid', 'Pode imprimir o conte\xfado do modelo S5001INFOCATEGINCID'))},
        ),
        migrations.AlterModelOptions(
            name='s5001infocp',
            options={'managed': True, 'ordering': ['s5001_evtbasestrab'], 'permissions': (('can_see_list_s5001infoCp', 'Pode ver listagem do modelo S5001INFOCP'), ('can_see_data_s5001infoCp', 'Pode visualizar o conte\xfado do modelo S5001INFOCP'), ('can_see_menu_s5001infoCp', 'Pode visualizar no menu o modelo S5001INFOCP'), ('can_print_list_s5001infoCp', 'Pode imprimir listagem do modelo S5001INFOCP'), ('can_print_data_s5001infoCp', 'Pode imprimir o conte\xfado do modelo S5001INFOCP'))},
        ),
        migrations.AlterModelOptions(
            name='s5001infocpcalc',
            options={'managed': True, 'ordering': ['s5001_evtbasestrab', 'tpcr', 'vrcpseg', 'vrdescseg'], 'permissions': (('can_see_list_s5001infoCpCalc', 'Pode ver listagem do modelo S5001INFOCPCALC'), ('can_see_data_s5001infoCpCalc', 'Pode visualizar o conte\xfado do modelo S5001INFOCPCALC'), ('can_see_menu_s5001infoCpCalc', 'Pode visualizar no menu o modelo S5001INFOCPCALC'), ('can_print_list_s5001infoCpCalc', 'Pode imprimir listagem do modelo S5001INFOCPCALC'), ('can_print_data_s5001infoCpCalc', 'Pode imprimir o conte\xfado do modelo S5001INFOCPCALC'))},
        ),
        migrations.AlterModelOptions(
            name='s5001procjudtrab',
            options={'managed': True, 'ordering': ['s5001_evtbasestrab', 'nrprocjud', 'codsusp'], 'permissions': (('can_see_list_s5001procJudTrab', 'Pode ver listagem do modelo S5001PROCJUDTRAB'), ('can_see_data_s5001procJudTrab', 'Pode visualizar o conte\xfado do modelo S5001PROCJUDTRAB'), ('can_see_menu_s5001procJudTrab', 'Pode visualizar no menu o modelo S5001PROCJUDTRAB'), ('can_print_list_s5001procJudTrab', 'Pode imprimir listagem do modelo S5001PROCJUDTRAB'), ('can_print_data_s5001procJudTrab', 'Pode imprimir o conte\xfado do modelo S5001PROCJUDTRAB'))},
        ),
    ]
