# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1210', '0019_auto_20190620_1408'),
        ('controle_de_acesso', '0026_auto_20190620_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s1210deps',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoant',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoantinfopgtoant',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtobenpr',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtobenprinfopgtoparc',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtobenprretpgtotot',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtofer',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoferdetrubrfer',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoferpenalim',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtofl',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoflinfopgtoparc',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoflpenalim',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210detpgtoflretpgtotot',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210idepgtoext',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='s1210infopgto',
            name='excluido',
        ),
    ]
