# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2300', '0007_auto_20190204_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s2300afastamento',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300afastamento',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300ageintegracao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300ageintegracao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300brasil',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300brasil',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300cargofuncao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300cargofuncao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300cnh',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300cnh',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300contato',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300contato',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300ctps',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300ctps',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300dependente',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300dependente',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300exterior',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300exterior',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300fgts',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300fgts',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infodeficiencia',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infodeficiencia',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infodirigentesindical',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infodirigentesindical',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infoestagiario',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infoestagiario',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infotrabcedido',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300infotrabcedido',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300mudancacpf',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300mudancacpf',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300oc',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300oc',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300remuneracao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300remuneracao',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300rg',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300rg',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300ric',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300ric',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300rne',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300rne',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300supervisorestagio',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300supervisorestagio',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300termino',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300termino',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='s2300trabestrangeiro',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='s2300trabestrangeiro',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='s2300afastamento',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300afastamento',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300ageintegracao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300ageintegracao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300brasil',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300brasil',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300cargofuncao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300cargofuncao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300cnh',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300cnh',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300contato',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300contato',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300ctps',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300ctps',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300dependente',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300dependente',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300exterior',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300exterior',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300fgts',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300fgts',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infodeficiencia',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infodeficiencia',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infodirigentesindical',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infodirigentesindical',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infoestagiario',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infoestagiario',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infotrabcedido',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300infotrabcedido',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300mudancacpf',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300mudancacpf',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300oc',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300oc',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300remuneracao',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300remuneracao',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300rg',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300rg',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300ric',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300ric',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300rne',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300rne',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300supervisorestagio',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300supervisorestagio',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300termino',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300termino',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300trabestrangeiro',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s2300trabestrangeiro',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
