# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1080', '0005_auto_20190202_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1080alteracao',
            options={'managed': True, 'ordering': ['s1080_evttaboperport', 'cnpjopportuario', 'inivalid', 'aliqrat', 'fap', 'aliqratajust'], 'permissions': (('can_view_s1080_alteracao', 'Can view s1080_alteracao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1080alteracaonovavalidade',
            options={'managed': True, 'ordering': ['s1080_alteracao', 'inivalid'], 'permissions': (('can_view_s1080_alteracao_novavalidade', 'Can view s1080_alteracao_novavalidade'),)},
        ),
        migrations.AlterModelOptions(
            name='s1080exclusao',
            options={'managed': True, 'ordering': ['s1080_evttaboperport', 'cnpjopportuario', 'inivalid'], 'permissions': (('can_view_s1080_exclusao', 'Can view s1080_exclusao'),)},
        ),
        migrations.AlterModelOptions(
            name='s1080inclusao',
            options={'managed': True, 'ordering': ['s1080_evttaboperport', 'cnpjopportuario', 'inivalid', 'aliqrat', 'fap', 'aliqratajust'], 'permissions': (('can_view_s1080_inclusao', 'Can view s1080_inclusao'),)},
        ),
    ]
