# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r4010', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r4010benefpen',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='r4010benefpen',
            name='r4010_detded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010benefpen_r4010_detded', to='r4010.r4010detDed'),
        ),
        migrations.AlterField(
            model_name='r4010benefpen',
            name='reldep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010despprocjud',
            name='r4010_infoprocjud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010despprocjud_r4010_infoprocjud', to='r4010.r4010infoProcJud'),
        ),
        migrations.AlterField(
            model_name='r4010despprocjud',
            name='r4010_inforra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010despprocjud_r4010_inforra', to='r4010.r4010infoRRA'),
        ),
        migrations.AlterField(
            model_name='r4010despprocjud',
            name='vlrdespadvogados',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010despprocjud',
            name='vlrdespcustas',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010detded',
            name='indtpdeducao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010detded',
            name='r4010_infopgto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010detded_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
        migrations.AlterField(
            model_name='r4010detded',
            name='vlrdeducao',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010fci',
            name='nrinscfci',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010fci',
            name='r4010_infopgto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010fci_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
        migrations.AlterField(
            model_name='r4010ideadv',
            name='nrinscadv',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010ideadv',
            name='r4010_despprocjud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010ideadv_r4010_despprocjud', to='r4010.r4010despProcJud'),
        ),
        migrations.AlterField(
            model_name='r4010ideadv',
            name='tpinscadv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010ideadv',
            name='vlradv',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010ideopsaude',
            name='nrinsc',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010ideopsaude',
            name='r4010_evtretpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010ideopsaude_r4010_evtretpf', to='efdreinf.r4010evtRetPF'),
        ),
        migrations.AlterField(
            model_name='r4010ideopsaude',
            name='vlrsaude',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010idepgto',
            name='natrend',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='r4010idepgto',
            name='paisresid',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='r4010idepgto',
            name='r4010_evtretpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010idepgto_r4010_evtretpf', to='efdreinf.r4010evtRetPF'),
        ),
        migrations.AlterField(
            model_name='r4010infodependpl',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='r4010infodependpl',
            name='r4010_ideopsaude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010infodependpl_r4010_ideopsaude', to='r4010.r4010ideOpSaude'),
        ),
        migrations.AlterField(
            model_name='r4010infodependpl',
            name='reldep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010infodependpl',
            name='vlrsaude',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010infopgto',
            name='dtfg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='r4010infopgto',
            name='inddecterc',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='r4010infopgto',
            name='r4010_idepgto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010infopgto_r4010_idepgto', to='r4010.r4010idePgto'),
        ),
        migrations.AlterField(
            model_name='r4010infopgto',
            name='vlrrendbruto',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010infopgtoext',
            name='dsclograd',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='r4010infopgtoext',
            name='frmtribut',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='r4010infopgtoext',
            name='indnif',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010infopgtoext',
            name='r4010_idepgto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010infopgtoext_r4010_idepgto', to='r4010.r4010idePgto'),
        ),
        migrations.AlterField(
            model_name='r4010infoprocjud',
            name='indorigrec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010infoprocjud',
            name='nrproc',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='r4010infoprocjud',
            name='r4010_infopgto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010infoprocjud_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
        migrations.AlterField(
            model_name='r4010infoprocret',
            name='nrprocret',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='r4010infoprocret',
            name='r4010_infopgto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010infoprocret_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
        migrations.AlterField(
            model_name='r4010infoprocret',
            name='tpprocret',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010inforeemb',
            name='nrinsc',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010inforeemb',
            name='r4010_ideopsaude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010inforeemb_r4010_ideopsaude', to='r4010.r4010ideOpSaude'),
        ),
        migrations.AlterField(
            model_name='r4010inforeemb',
            name='tpinsc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010inforeemb',
            name='vlrreemb',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010inforeembdep',
            name='nrinsc',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010inforeembdep',
            name='r4010_infodependpl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010inforeembdep_r4010_infodependpl', to='r4010.r4010infoDependPl'),
        ),
        migrations.AlterField(
            model_name='r4010inforeembdep',
            name='tpinsc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010inforeembdep',
            name='vlrreemb',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010inforra',
            name='descrra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='r4010inforra',
            name='indorigrec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010inforra',
            name='qtdmesesrra',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=4),
        ),
        migrations.AlterField(
            model_name='r4010inforra',
            name='r4010_infopgto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010inforra_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
        migrations.AlterField(
            model_name='r4010inforra',
            name='tpprocrra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010origemrec',
            name='cnpjorigrecurso',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010origemrec',
            name='r4010_infoprocjud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010origemrec_r4010_infoprocjud', to='r4010.r4010infoProcJud'),
        ),
        migrations.AlterField(
            model_name='r4010origemrec',
            name='r4010_inforra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010origemrec_r4010_inforra', to='r4010.r4010infoRRA'),
        ),
        migrations.AlterField(
            model_name='r4010rendisento',
            name='r4010_infopgto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r4010rendisento_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
        migrations.AlterField(
            model_name='r4010rendisento',
            name='tpisencao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r4010rendisento',
            name='vlrisento',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010scp',
            name='nrinscscp',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='r4010scp',
            name='percscp',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=5),
        ),
        migrations.AlterField(
            model_name='r4010scp',
            name='r4010_infopgto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r4010scp_r4010_infopgto', to='r4010.r4010infoPgto'),
        ),
    ]
