# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s1250', '0013_auto_20190525_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s1250ideprodutor',
            options={'managed': True, 'ordering': ['s1250_tpaquis', 'tpinscprod', 'nrinscprod', 'vlrbruto', 'vrcpdescpr', 'vrratdescpr', 'vrsenardesc', 'indopccp'], 'permissions': (('can_view_s1250ideProdutor', 'Can view S1250IDEPRODUTOR'), ('can_view_menu_s1250ideProdutor', 'Can view menu S1250IDEPRODUTOR'))},
        ),
        migrations.AlterModelOptions(
            name='s1250infoprocj',
            options={'managed': True, 'ordering': ['s1250_tpaquis', 'nrprocjud', 'codsusp', 'vrcpnret', 'vrratnret', 'vrsenarnret'], 'permissions': (('can_view_s1250infoProcJ', 'Can view S1250INFOPROCJ'), ('can_view_menu_s1250infoProcJ', 'Can view menu S1250INFOPROCJ'))},
        ),
        migrations.AlterModelOptions(
            name='s1250infoprocjud',
            options={'managed': True, 'ordering': ['s1250_ideprodutor', 'nrprocjud', 'codsusp', 'vrcpnret', 'vrratnret', 'vrsenarnret'], 'permissions': (('can_view_s1250infoProcJud', 'Can view S1250INFOPROCJUD'), ('can_view_menu_s1250infoProcJud', 'Can view menu S1250INFOPROCJUD'))},
        ),
        migrations.AlterModelOptions(
            name='s1250nfs',
            options={'managed': True, 'ordering': ['s1250_ideprodutor', 'nrdocto', 'dtemisnf', 'vlrbruto', 'vrcpdescpr', 'vrratdescpr', 'vrsenardesc'], 'permissions': (('can_view_s1250nfs', 'Can view S1250NFS'), ('can_view_menu_s1250nfs', 'Can view menu S1250NFS'))},
        ),
        migrations.AlterModelOptions(
            name='s1250tpaquis',
            options={'managed': True, 'ordering': ['s1250_evtaqprod', 'indaquis', 'vlrtotaquis'], 'permissions': (('can_view_s1250tpAquis', 'Can view S1250TPAQUIS'), ('can_view_menu_s1250tpAquis', 'Can view menu S1250TPAQUIS'))},
        ),
    ]
